### ISSUE TITLE
Create a social media wall using the loklak API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#109]
**Objective**
Develop a social media wall app for loklak.

**Requirements**
- For project issues and questions use tracker of loklak server https://github.com/loklak/loklak_server
- Make use of loklak API http://www.loklak.org/api.html

**Expected Outcome**
- Sample of a similar social media wall is here: http://www.wallofsocial.com
- Final project should be hosted on FOSSASIA or loklak github

**Comment by shashank19gaurav** [comment]
Hi Mario, 
I would like to work on this mini project.

**Comment by sopu** [comment]
Hi @mariobehling, I would like to work on this project.

**Comment by sopu** [comment]
Hi @mariobehling, I would like to work on this project. 
Planning to use masonry for cascading grid layout and handlebars for templating.

**Comment by sopu** [comment]
I have created a basic layout for the wall. Please suggest the modifications required. 
![screenshot from 2016-01-30 03 34 29](https://cloud.githubusercontent.com/assets/6399612/12689380/987de6ca-c702-11e5-80bd-d6c9225cfb6c.png)

**Comment by sopu** [comment]
I have created a basic layout for the wall. Please suggest the modifications required. 
![screenshot from 2016-01-30 03 34 24](https://cloud.githubusercontent.com/assets/6399612/12689412/ba01d568-c702-11e5-9052-4b9f8dd93521.png)

**Comment by sopu** [comment]
@mariobehling please checkout https://github.com/sopu/loklak_server.git 
The page for 960px width. 

![screenshot from 2016-02-02 20 21 31](https://cloud.githubusercontent.com/assets/6399612/12752909/92ec8d8e-c9ea-11e5-91c6-24b4602e8b47.png)

**Comment by aayusharora** [comment]
@mariobehling,I have already implemented it in open-event webapp ,I have used loklak to fetch tweets successfully,and applied with animations like http://www.wallofsocial.com ,please check Twitter Wall #125,will be glad if I will be allowed to add some more features like
1.hyperlink rendering
2.more work on UX
Thanks .

**Comment by aayusharora** [comment]
@mariobehling ,Please check https://github.com/fossasia/open-event-webapp/pull/125 for Twitter wall implemented.

**Comment by aayusharora** [comment]
@mariobehling https://files.gitter.im/fossasia/open-event-webapp/XfBH/2.png ,already a view was there on gutter .
Please check to have the changes

**Comment by aayusharora** [comment]
![twitterwall](https://cloud.githubusercontent.com/assets/12194719/13451896/1f97cac0-e069-11e5-9ab3-fa9f99426731.gif)

**Comment by leonmak** [comment]
@mariobehling created one using Meteor,
![](https://github.com/leonmak/meteor-twitterwall/raw/master/public/ss.gif)
https://github.com/leonmak/meteor-twitterwall
http://meteortweetwall.meteor.com
Hosting requires nodejs
