### ISSUE TITLE
GSOC 2016 Official Fossasia Website

### ISSUE THREAD

**Issue by manishbisht** [fossasia/labs.fossasia.org#110]
Hello Everyone,

I want to make some contributions on Fossasia. So I have one idea can we make the official website of the GSOC 2016 like on the domain gsoc16.fossasia.org or the other domain you like. On that page all the details related to mentors and ideas will be put there and we can write there some useful tips for the students to get selected in GSOC 2016.
It will be very useful for the students and also we as the fossasia contributor have some place where all the details of the mentor and students can be kept.

Hope you all will like this.

Thanks :)

**Comment by SilentFlame** [comment]
@manishbisht  yes thats a good idea indeed. As recently we had an official website for just the GCI-16 participants and mentors.

Would love to contribute to this thing, I'm in.

**Comment by alan-aipe** [comment]
Ya.. thats a nice idea.. I will also like to join ... Count me in @manishbisht  @SilentFlame

**Comment by manishbisht** [comment]
@mariobehling Can we three work for the GSoC Webiste ? @SilentFlame @alan-aipe

**Comment by ashutoshsaboo** [comment]
I have been working on Web Development since a long time. I would appreciate if I could work on this. So, Can I contribute to making this website, with all the relevant links? So, we can get started now itself! :)

**Comment by mariobehling** [comment]
The focus of FOSSASIA is to see the development of software. Also students should keep information on their blog or on projects site. GCI is a different thing as it has an educational focus as well. Currently there is no need for a website. Please put your energy into software projects.

**Comment by mariobehling** [comment]
If you want to help there are more than 90 issues here: https://github.com/loklak/loklak_webclient/issues
