### ISSUE TITLE
Improve the game Flappy SVG

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labs.fossasia.org#111]
**Context**
[Flappy SVG](http://fossasia.github.io/flappy-svg/) is in open source game which you can contribute to.

**Objective**
Learn about how to contribute to projects on github and improve the game. We have [tasks](https://github.com/fossasia/flappy-svg/tree/master/tasks#tasks) you can choose from and several [issues](https://github.com/fossasia/flappy-svg/issues) you can solve. 

**Requirements**
- Choose a [task](https://github.com/fossasia/flappy-svg/tree/master/tasks#tasks) or an [issue](https://github.com/fossasia/flappy-svg/issues) and solve it.

**Expected Outcome**
- Your contribution is in the [fossasia/flappy-svg](https://github.com/fossasia/flappy-svg) repository.

**Comment by Abhi2424shek** [comment]
@niccokunzmann @mariobehling do we still need this? If you want someone to close an issue take the issues i have closed and open a new issue to make the game more interesting like the characters are not looking good nor is the backgrounds.

Another proposal would be to make an issue to enhance the game where the user should design the JavaScript to solve the splitting issue, #108

What do you think?

**Comment by 0x48piraj** [comment]
I think we should close this issue and should open a new one for **labyrinth**

What do you all think @mariobehling @niccokunzmann @abishekvashok ?

**Comment by niccokunzmann** [comment]
@0x48piraj Sure, feel free to open the issue for the labyrinth.
