### ISSUE TITLE
Add IoT features to the Open Tweet Platform loklak.net and offer more visualizations with maps

### ISSUE THREAD

**Issue by Orbiter** [fossasia/labs.fossasia.org#112]
Add IoT features to the Open Tweet Platform loklak.net and offer more visualizations with maps. Currently there are many feature requests open for the loklak.net portal.

**Potential feature projects include:**
- View more data on maps
- Analyse tweets in comparison to other data
- Support development of sentiment analysis
- Implement Internet of Things devices

**Links**
- [Github Project](https://github.com/loklak)
- [Issue List](https://github.com/loklak/loklak_webclient/issues)
- [Chat](https://gitter.im/loklak)
- [Mailing List](https://groups.google.com/forum/#!forum/loklak)

**Comment by Aadesh-Magare** [comment]
Hello
I am Aadesh.
I would love to work on loklak.net (I think it would be a good entry point for me to open source contributions)
can you please point me in right direction to get started ? (some pr-requisites maybe?)

**Comment by sopu** [comment]
@Orbiter while working on some issues, I found that some of them can be closed as the required changes are visible on the master branch and some of them have open PRs. It would be great if this can be looked into. 
Cheers!!

**Comment by jig08** [comment]
@sopu It will be very helpful if you could point to them :)

**Comment by sopu** [comment]
Open PRs for issues: 445, 520, 558, 562
Issues which have (some work done but) not been followed up or are resolved and not closed: 455, 407, 377(fixed), 330, 319 (few of those)
