### ISSUE TITLE
Internet of Things IoT prototype using RPi/Odroid/Arduino hardware and a loklak back-end

### ISSUE THREAD

**Issue by Orbiter** [fossasia/labs.fossasia.org#113]
The loklak.org server is capable of storing tweet-like geo-enriched event-tracking data. All the server storage and indexing infrastructure is there to provide a back-end for a community-driven platform of IoT devices. We need a prototype which shows the combination of a small smart device, a measurement task and a loklak sever which stores the messages from the IoT device.
The task would be, to take care of the hardware, the software on the hardware and a delta analysis for the loklak_server.

**Comment by sakshamgupta006** [comment]
Hi I am new to Foss Asia......I am really interested in this IoT prototype...
I am bit confused regarding the part that what information from the IoT device shall be uploaded ion the loklak server (according to that only h/w be managed and s/w will be written). 
Please can you be more descriptive as to exactly what you require....

Thanks!!

**Comment by TheekD** [comment]
Hi, I'm an undergraduate following a Integrated computer engineering major. I have done projects on IoT and worked with R Pi and Arduino. I'm really excited this project and need assistance on learning about the loklak.org server further. Can you help me on that.

**Comment by crakensio** [comment]
Hi,
I came across this on GSOC project ideas. I was looking for projects on Hardware prototyping. I was impressed by the loklak.org server capabilities. Being a p2p Lover, and a FOSS enthusiasts I would love to add value to this project.

If you provide detailed description on the requirement i would love to  contribute.
