### ISSUE TITLE
Create loklak apps to display and the track the success of FOSS projects

### ISSUE THREAD

**Issue by Orbiter** [fossasia/labs.fossasia.org#114]
Each FOSS project can measure it's success with a wide range of tracking data: i.e. how many users, how large is the data, how many commit, how many contributors, how large is the geographic distribution. The tracking of such kind of success parameters can be done with measurement microblog-like data packets which can be stored and provided by a loklak server. loklak already provides an 'app' infrastructure which is simple and easy to use, please see https://github.com/loklak/loklak_server/blob/master/html/apps/apps.md
This project could have many instances, one for each FOSS project that shall be tracked. The work would include:
- select a FOSS project
- select the success-measurement data for this project
- describe a visualization of such data (i.e. on a map, a histogram, a  graph)
- describe a metadata format for such data which shall be encapsulated as IoT data for loklak
- create a data harvester which collects measurements and pushes it into a loklak server
- create a visualization app for that data as loklak app
- make a delta analysis to discover which functions should be implemented in loklak_server to realize what you need.

**Comment by SaptakS** [comment]
Hi @Orbiter. I have been working with FOSSASIA for sometime now and have used loklak server during GCI to mentor students. I would really love to work on this project. I am very enthusiastic about web technologies and FOSS. I have knowledge of HTML, CSS, Javascript, and various other frameworks of javascript such as angular js, jquery, node js, etc., and python. I would like to know what kind of technologies are you thinking of using in this project. Hoping to hear from you soon.

**Comment by dpocock** [comment]
One of the projects under Debian in 2015 involved tracking data from different projects:

http://danielpocock.com/aggregating-tasks-multiple-issue-trackers-gsoc-2015-summary

and it could be interesting to build on that or use similar concepts, such as the iCalendar data format, where applicable.

**Comment by SilentFlame** [comment]
I am a computer science student from IIIT-Hyderabad, India.
I have a good grip in HTML, CSS, javascript, python,etc and had worked on MEAN stack js framework in several of my college project. I have been contributing to FOSSASIA and Open Source from last few months.
I am very much interested in FOSS and web-development, and at the same time enthusiast to learn more and more.
I'm really interested in this Idea, and has cloned the loklak_server and started testing some of the present apps to get a better understanding.
To get myself involved in this project I need some guidance as to understand what exactly we need as an end-result from this project.

Points I need some more clarification are:
- Exactly what kind of FOSS projects are we considering of tracking.
-  How do we decide the success-measurement data for the considered project.
-  does the success-measurement data should remain the same for all the projects or we need project specific success-measurement data(like no. of users, no. of commits, etc.)
- What exactly is the end-result of the project.

It would be very helpful if you can guide me to initiate this project.

**Comment by leonmak** [comment]
@Orbiter @mariobehling Not sure if this is the right place to ask this, but are the mentors open to using MeteorJS for any of the loklak fossasia ideas?
I've been playing around with loklak server, and also created a prototype for a twitter wall, [meteortweetwall.meteor.com](http://meteortweetwall.meteor.com) ([github repo](https://github.com/leonmak/meteor-twitterwall))
I think meteor can also be used for the idea on "creating apps to track success of FOSS projects", because of it's realtime and cross-platform features.

**Comment by shaheenkdr** [comment]
@Orbiter  Since I had worked on the Loklak Wall app, can I apply for this project? 
I'd really love to work on this one too!
