### ISSUE TITLE
Change link on ideas page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#115]
Currently the links on the ideas page are e.g. "http://labs.fossasia.org/ideas.html#loklak-description"
Please change them to "http://labs.fossasia.org/ideas.html#loklak" taking out "-description".

**Comment by SaptakS** [comment]
Ok.

**Comment by niksj** [comment]
Is it done or
Anyone working on this? 
I would like work on this issue..
