### ISSUE TITLE
Improve the Open Event Organizer Server and implement missing features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#117]
The FOSSASIA Open Event Project makes it easy for events and conferences to create Web and Mobile micro Apps with schedules and speaker infos. Please support the team, fix bugs and add features to the project.

**Components of Open Event**

The project comprises of a data schema for easily storing event details, a server and web frontend that are used to view, modify, update this data easily by the event organisers, a mobile-friendly webapp client to show the event data to attendees, an Android app template which will be used to generate specific apps for each event. Each specific component's source code has it's own Github Repo, links provided in the subsections below . This repository is for tracking milestones and issues, and maintaining a wiki about the project. Also, documentation about the JSON Schema, and how to use the template will be hosted on this repo.

**Organizer Server**

The server manages all the data of the event. Backed by a database, it provides API endpoints to fetch the data, and also to modify/update it. 

**Links**
- [Github Repo](https://github.com/fossasia/open-event-orga-server)
- [![Join the chat at https://gitter.im/fossasia/open-event-orga-server](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/fossasia/open-event-orga-server?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Application for the project**

Please have a look at the application template at Google. Also consider the following:
- Test the project and submit bugs reports to show your interest in the project
- If possible fix a bug or implement a feature before applying
- Make a plan with milestones and clear deliverables for your project

**Comment by SaptakS** [comment]
Hi @mariobehling . I have been working on the open event organization server for some time now. I have prior knowledge of Flask, PostgreSQL, python and all the other components used in this project. I would really like to take up this project for GSOC.

**Comment by niranjan94** [comment]
Hello @mariobehling . I have created a similar web application in PHP (but with a lot of additional features to assist the organizers of events). I was thinking of adding a few of those features into the open event organization server as a part of my GSoC 2016 project.

**Comment by niranjan94** [comment]
@mariobehling who are the possible mentors for this project ?

**Comment by niranjan94** [comment]
@mariobehling @rafalkowalski 
I have submitted the draft of my proposal through the Google Summer of Code 2016 portal. But, I have not added a mentor in it yet, as I'm not sure who the mentors are for the project.
