### ISSUE TITLE
Change "View on Github" to normal link style, ensure links with images do not have a red surrounding and fix other issues

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#118]
1. [x] Please see below. The links should be displayed in the same way as on the labs main page: 
   ![screenshot from 2016-03-01 02 39 39](https://cloud.githubusercontent.com/assets/1583873/13404896/f024bc34-df56-11e5-82c1-527276c7405e.png)
2. [x] Please ensure images do not have a link surrounding as below:
   ![screenshot from 2016-03-01 02 41 04](https://cloud.githubusercontent.com/assets/1583873/13404945/246e8e2a-df57-11e5-8136-d81bb9ee3cd3.png)
3. [ ] Render markdown in same way as on GitHub e.g. Lists should show up, but currently they do not.
4. [x] Decrease size of "Read More on Github" to normal link size

**Comment by kamishettysreeja25** [comment]
@mariobehling  
I would like to work on this

**Comment by SilentFlame** [comment]
@mariobehling I have some questions regarding the issue:

- Point1: `The links should be displayed in the same way as on the labs main page: ` do you mean that color of the link should not change while hovering on it.

- Point2: only one link of `Gitter chatroom` contains image, either make all as image and I can remove the Underline, or make all as just a link.

- Unable to follow up on point3.

**Comment by mariobehling** [comment]
Many links are still not rendered. Anyone ideas?

**Comment by aviaryan** [comment]
> Many links are still not rendered. Anyone ideas?

As Showdown.js is being used for converting markdown to HTML, we can use its simplifiedAutoLink property. https://github.com/showdownjs/showdown

```
simplifiedAutoLink: (boolean) [default false] Turning this on will enable GFM autolink style. This means that .......
```
I have opened pull #130 for this.

**Comment by SilentFlame** [comment]
@mariobehling 
as @aviaryan is working on 3rd part I corrected the 4th one in #131 .

**Comment by aviaryan** [comment]
>  Render markdown in same way as on GitHub e.g. Lists should show up, but currently they do not.

@mariobehling I don't understand this. Aren't lists preview correctly. A screenshot would be very helpful.

**Comment by mariobehling** [comment]
The changes also influenced the existing links. Instead of changing existing CSS, it would be better to choose the same CSS for the same kind of links designs.

![screenshot from 2016-04-03 01 00 15](https://cloud.githubusercontent.com/assets/1583873/14227775/ae1aca4a-f937-11e5-8121-2dd30447d750.png)

**Comment by SilentFlame** [comment]
@mariobehling  you mean for the common links we should keep them as they are now but for links like this i.e `inner-links` should be handled with different CSS style.
am I right?

**Comment by SilentFlame** [comment]
making all the class containing `h1 a` to have similar CSS style of one kind and the class with `inner-links` class inside to have other CSS style.

**Comment by aayusharora** [comment]
@SilentFlame , I am working on the same , Is this the only link affected?

**Comment by SilentFlame** [comment]
@aayusharora I guess this is only as per this page is concerned, and I have resolved it but waiting for @mariobehling's response on the above before making a PR.

**Comment by aayusharora** [comment]
@SilentFlame ,ok .

**Comment by aayusharora** [comment]
@SilentFlame , If you are working on it please check this , other links do not change to blue color ,  only this one changes on click.
![Uploading 1.PNG…]()

**Comment by SilentFlame** [comment]
@aayusharora  oh yes, great you pointed.
let's wait for @mariobehling's response on your asked question.

**Comment by mariobehling** [comment]
@aayusharora @SilentFlame My main concern is: Please do not change the existing CSS, but rather change the html. All styles are already available in the CSS. All FOSSASIA sites use the same CSS. If you change existing CSS, it will change the style somewhere else on the style. I reverted all CSS changes. "Read more on Github" should use another style, than the currently assigned one - to make the size smaller.

![screenshot from 2016-04-03 10 05 27](https://cloud.githubusercontent.com/assets/1583873/14230302/b16baad8-f983-11e5-9130-cc344359a21e.png)

**Comment by SilentFlame** [comment]
@mariobehling or we can just assign a different CSS to the unique class they have as going through their links, class-name all are very general and if we alter them we need to add CSS style in .css files to reflect the changes.
In that situation adding new styles to the current CSS with the unique classes of these links would do the expected work.In that way it does not affect other links anywhere else too.

**Comment by aayusharora** [comment]
@SilentFlame ,why to make unique classes if we have them already?

**Comment by SilentFlame** [comment]
@aayusharora not making unique classes, I mean making styles in the `.css` file specific to these unique classes. what you say?

**Comment by aayusharora** [comment]
@SilentFlame , we should only change the markup , not to do any changes in css.

**Comment by aayusharora** [comment]
@mariobehling , Check this please #133
