### ISSUE TITLE
Develop new features for the Open Event Android app, improve performance and usability

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#119]
Your task is to develop new features, improve the usability and performance of the the Open Event Android app. You can take ideas from lots of existing apps. Part of the project is also to support the development of other Open Event components to work together with the app. Related projects such as [redata](https://github.com/opendatacity/re-data) are also expected to be taken into account for future development.

**Components of Open Event**

The project comprises of a data schema for easily storing event details, a server and web frontend that are used to view, modify, update this data easily by the event organisers, a mobile-friendly webapp client to show the event data to attendees, an Android app template which will be used to generate specific apps for each event. Each specific component's source code has it's own Github Repo, links provided in the subsections below . This repository is for tracking milestones and issues, and maintaining a wiki about the project. Also, documentation about the JSON Schema, and how to use the template will be hosted on this repo.

**Open Event Android App**

A native Android app template which shows all information about the event like Sessions, Speakers, Map of location, Sponsors etc. Each event needs to make a copy of this template, change only a handful of basic stuff like icon, package name, backend URL, and generate a unique app for their own event. The idea is the create a template from which anyone can generate an app in 10 minutes, without having any knowledge of Android development.

**Links**
- [Github Repo](https://github.com/fossasia/open-event-android)
- [Mailing List](https://groups.google.com/forum/#!forum/open-event)
- [Gitter Chat](https://gitter.im/fossasia/open-event-android)

**Application for the project**

Please have a look at the application template at Google. Also consider the following:
- Test the project and submit bugs reports to show your interest in the project
- If possible fix a bug or implement a feature before applying
- Make a plan with milestones and clear deliverables for your project

**Comment by Devastrix** [comment]
@mariobehling 
I've started working on improving the UI of the app. And I've thought of some new features. I would really like to work on this project for GSOC.

**Comment by pheonixlegend** [comment]
I would be more than happy to work on this as it would mean the world to me if i get into the GSOC program. I can do this using json, php n mysql for communication and i can also do a great UI using material design for the android app template. I have already started working on it.

**Comment by the-dagger** [comment]
@mariobehling  Can you please have a look at my proposal and let me know if there are any changes that I should make.
Thanks,
Harshit
[GSoCFOSSAsiaProposal.pdf](https://github.com/fossasia/labs.fossasia.org/files/180677/GSoCFOSSAsia.pdf)

**Comment by opticod** [comment]
Hi all mentors, @mariobehling 
I have submitted my draft proposal **"Develop new features for the Open Event Android app, improve performance and usability"** for review to Google. I will be happy to incorporate any changes required for my proposal.

I've been contributing in open-event-android for some time now. Some of my contributions are:

PRs : https://github.com/fossasia/open-event-android/pulls?utf8=%E2%9C%93&q=author%3Aopticod

Issues Reported : https://github.com/fossasia/open-event-android/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aopticod

Hoping for Best ,
Thank You,
Anupam Das|opticod
Indian Institute Of Technology, Patna
