### ISSUE TITLE
Improve UX add features for the Open Event Web App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#120]
Your task is to develop new features, improve the usability and performance of the the Open Event Web App. You can take ideas from lots of existing apps. Potential features could be social media features. Part of the project is also to support the development of other Open Event components to work together with the app. Related projects such as [redata](https://github.com/opendatacity/re-data) need to be taken into account and supported if this is needed for development progress.

**Components of Open Event**

The project comprises of a data schema for easily storing event details, a server and web frontend that are used to view, modify, update this data easily by the event organisers, a mobile-friendly webapp client to show the event data to attendees, an Android app template which will be used to generate specific apps for each event. Each specific component's source code has it's own Github Repo, links provided in the subsections below . This repository is for tracking milestones and issues, and maintaining a wiki about the project. Also, documentation about the JSON Schema, and how to use the template will be hosted on this repo.

**Open Event Android App**

A mobile-friendly webapp, which shows all information about the event like Sessions, Speakers, Map of location, Sponsors etc. The idea is to make a ready-to-port webapp, that can be wrapped into iOS, Windows, Chrome etc apps - ie. those platforms we are not immediately supporting natively..

**Links**
- [Github Repo](https://github.com/fossasia/open-event-webapp)
- [Mailing List](https://groups.google.com/forum/#!forum/open-event)
- [Gitter Chat](https://gitter.im/fossasia/open-event-webapp)

**Application for the project**

Please have a look at the application template at Google. Also consider the following:
- Test the project and submit bugs reports to show your interest in the project
- If possible fix a bug or implement a feature before applying
- Make a plan with milestones and clear deliverables for your project

**Comment by SaptakS** [comment]
@mariobehling I have been working on the open-event-webapp project for some time now along with @creativepsyco and @championswimmer . I would really to take up this project for GSOC and contribute to make enhancements and add features.

**Comment by aayusharora** [comment]
@mariobehling ,I am working for open-event-webapp with @mananwason and @creativepsyco ,@championswimmer, I have added some new feature like New Twitter Wall #125,its under review ,apart from that I am doing proper testing and reported some important UX bugs and have fixed them .For ex:#123 UX issue in search By Title, Search By Speaker ,solved here #124.
                                I want to continue with this and want to add more features to it as a GSOC project.

**Comment by joerx** [comment]
I'd be interested in mentoring this one.

**Comment by ashutoshsaboo** [comment]
@joerx @mariobehling Hi. I wanted to work towards this. But just a confusion. Are the applicants supposed to build both the Android App as well as the Web App? Or are they only supposed to build on the Web App? 

Thanks! :smile:

**Comment by championswimmer** [comment]
They are separate GSOC tasks

**Comment by mariobehling** [comment]
@ashutoshsaboo We can talk about, if projects can be done together or better separately. What we need at the moment is to see that students are able and can code. Other questions can be worked out easily. 

There are a number of small issues for the schedule on the website, where interested contributors could work on for example: github.com/fossasia/2016.fossasia.org/issues

**Comment by iamonuwa** [comment]
Am a Nigerian, from the website, I found out that this organization is interested in asian developers. Can I apply from Nigeria?

**Comment by aayusharora** [comment]
@mariobehling ,Please suggest possible mentors for this project , so that I can discuss the proposal before finalizing .

**Comment by PMArtz92** [comment]
Hi im also interested about this project i have done some UI mockups for this project i'll send those

**Comment by PMArtz92** [comment]
@aayusharora , @mariobehling I have question about UI part of this, does the UI part also included in this project or can i proposed a new UI design for this app??
