### ISSUE TITLE
Implement APIs from various social media platforms and develop app components for open data social media analysis

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#121]
Social media analytics can be very helpful in finding out interesting facts at events and international incidents.

Think of what is happening at conferences. Participants and organizers often want to know:
- During which sessions people tweeted most?
- Who gets more mentions?
- Which track gets more tweets? (track specific hashtag?) etc…

**Task**

Implement APIs from various social media platforms in loklak and develop app components for open data social media analysis in the loklak web client or as app components. Specifically think of services in Asian countries as well. Check out the [loklak web client issue tracker](https://github.com/loklak/loklak_webclient/issues) for ideas.

**Required Skills**

Javascript, REST APIs, HTML5, CSS3, AngularJS/JQuery, Knowledge of loklak API

**Links**
- [Github Project](https://github.com/loklak)
- [Issue List](https://github.com/loklak/loklak_webclient/issues)
- [Chat](https://gitter.im/loklak)
- [Mailing List](https://groups.google.com/forum/#!forum/loklak)

**Comment by cyberkoi** [comment]
hey @mariobehling, I am extremely keen on getting onboard this project. I've had previously open source experience with Javascript, EmberJS, HTML5, CSS3 where I co-wrote a plugin for Discourse.org, see project [here](https://github.com/team-melbourne-rgsoc2015/discourse-adplugin). 

Currently a final-year student finishing the Diploma of IT. I learn fast and find that this project is most suitable! I've been exposed to Java, C, Python and SQL, am a huge social media user (facebook, twitter, tumblr etc.) and grew up in Asia for more than half of my life. This project resonates with me on many levels and I'm confident of delivering. Is there an email address to contact you at? Would love to have a chat.

**Comment by kancharlahemant** [comment]
Hi @mariobehling , I am a student doing my masters in computational linguistics in IIIT-H(India), and I am well exposed to all asian languages. I am very interested especially in the data analysis part. I have some very interesting ideas to discuss. Please get back to me.

**Comment by rishabhs95** [comment]
Hi @mariobehling, I am a student pursuing Bachelors in Information Technology from BIT, Mesra(India), and this project looks very interesting and suits my current skill set too. I have experience in working with different Web APIs and implementing them on Web Applications using different frameworks(php, laravel, angularjs and nodejs). I would like to further discuss about this idea and can you guide me about the further steps needed to be taken? Any specific tasks?

**Comment by prateek1095** [comment]
Hi @mariobehling ,
I am very much interested in taking this project.I have experience on working with Html5,css3Javascript,AngularJs,Bootstrap and have made many web applications. 
I have previously contributed to the tweetheatmap which is made using loklak search 
api and have some very interesting ideas to implement in it. I would love to discuss these 
ideas with you .
Thanks,
Prateek

**Comment by animesh2049** [comment]
Hi @mariobehling ,
I am a student of IIIT Hyderabad presently pursuing BTech in computer science.
I am well familiar with the uses of api's (have used youtube and facebook api's for some data extraction purposes) also I am well familiar with the technologies like  Javascript, REST APIs, HTML5, CSS3, JQuery. I would like to contribute for this project. Please guide me through steps to initiate this project.

**Comment by prashant2018** [comment]
Hi @mariobehling ,
I am a student of KIIT University(India) and would love to contribute to this project. I have experience with REST APIs, Web Scrapping, Data Visualisation and Analytics.I am comfortable with Python, Java ,C,C++,HTML5,CSS3,SQL,Database Designs,Django,Javascript and always ready to learn.
Thankyou,
Prashant Kumar

**Comment by shubhamG9** [comment]
Hi @mariobehling ,
I am very interested in this project and would love to contribute to this project. I am a student of VIT Pune(India) and familiar with HTML5, CSS3,Javascript , Jquery, python,AngularJS. I would love to discuss this project with you and it would be very helpful if you could guide me with further steps.

**Comment by Prakhash** [comment]
Hi all,
I'm Prakhash a final year student from University of Moratuwa, Sri Lanka. I'm very much interested in this project. Other than few project usages, I don't have a language specific fluency in javascript, but I have worked a lot in Data mining & information retrial related areas, worked in social media platforms like YELP and I have a good understanding about REST APIs. I believe this a very suitable project for me and  I would like to contribute for this project.

Thank you
Prakhash
