### ISSUE TITLE
Develop new features for the Engelsystem used for Volunteer coordination at the FOSSASIA Summit

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#126]
FOSSASIA uses the Engelsystem hosted by the FFII at https://engel.ffii.org. The system was originally developed for events of the Chaos Computer Club in Germany. There are number of possible improvements of the system, e.g. integration with other services, more features for Admins e.g. contact exports of volunteers, better localization and support of Asian languages.

Development: https://github.com/engelsystem/engelsystem/
Issues/Bugs: https://github.com/engelsystem/engelsystem/issues

**Comment by kamishettysreeja25** [comment]
@mariobehling  
Can You please tell me who are all  the possible mentors for this project .I can't find them in the  ideas page.
