### ISSUE TITLE
convert project variables

### ISSUE THREAD

**Issue by eMBee** [fossasia/labs.fossasia.org#13]
convert the fields on the bottom of each project to yaml variables so they can be shown in the page and in the overview.

**Comment by samarjeet27** [comment]
@eMBee, do you want to define the variables in the frontmatter or a data file ?

**Comment by eMBee** [comment]
in the front matter for each file

**Comment by samarjeet27** [comment]
Fixed 
https://github.com/fossasia/labs.fossasia.org/pull/16
