### ISSUE TITLE
Set up a loklak server on a VPN or in the cloud

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#134]
There are step by step instructions how to set up a loklak server as a peer here: https://github.com/loklak/loklak_server#how-do-i-install-loklak-download-build-run

The loklak site also lists a number of video tutorials: http://loklak.org/tutorials.html

After a short while your peer should show up here: http://loklak.org/api/peers.json

Please tweet to @lklknt on Twitter after the completion of the installation. Thank you.

**Comment by adarsh-ideal** [comment]
Setup complete on heroku: http://young-beach-26300.herokuapp.com/
![screenshot from 2017-01-01 23-12-31](https://cloud.githubusercontent.com/assets/12227945/21582353/cdabef50-d079-11e6-80cb-3fb6f2d56959.png)

**Comment by 0x48piraj** [comment]
### Setup complete on **Surge** !

**_Deploy Link : [http://pr-637-fossasia-loklaksearch.surge.sh](http://pr-637-fossasia-loklaksearch.surge.sh)_**


Ping @mariobehling :heart:

**Comment by abishekvashok** [comment]
@0x48piraj you need to deploy `loklak_server` and not `loklak_search`

**Comment by 0x48piraj** [comment]
**Setup complete on Heroku !**

**_Deploy Link : [https://loklak-piyush.herokuapp.com/](https://loklak-piyush.herokuapp.com/)_**

Ping @mariobehling :100:

**Comment by simsausaurabh** [comment]
@mariobehling is this issue still valid ? Since loklak server is already deployed on cloud.

**Comment by mariobehling** [comment]
Please avoid asking for each issue if it is still valid. This is a mini-project that is always valid. Surely, we need people who set up more loklak peers.
