### ISSUE TITLE
Create a Linux distro for events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#135]
Basis Linux Mint

Important 
- [ ] Use LXQT
- [ ] Switch off notifications
- [ ] Switch off screensaver and sleep modus
- [ ] Switch off system sounds
- [ ] disable bookmarks in browser
- [ ] Install ownCloud and Dropbox
- [ ] Pre-set start system without password
- [ ] install Gtalk/Hangout
- [ ] install Firefox, Chrome, Chromium
- [ ] set Chromium as default
- [ ] set custom start page and set "re-start with last opened tabs" (in case laptop is crashing)
- [ ] install git
- [ ] change desktop background with custom image
- [ ] update to latest version (without password)
- [ ] switch off screen dimming
- [ ] switch off power management saving features
- [ ] link to the slide folder from the desktop (edit "make a link")
- [ ] authide panel
- [ ] install local language keyboards
- [ ] install VLC and set as standard video player
- [ ] install LibreOffice, Gimp, Inkscape
- [ ] set search engine and distro referrals

**Comment by ajmalazeez007** [comment]
@mariobehling I would like to work on this.

**Comment by mariobehling** [comment]
@ajmalazeez007 Great. Please let us know the steps you are working on. Cheers.

**Comment by mariobehling** [comment]
@ajmalazeez007 Hi, it looks like you got busy elsewhere. I am unassigning this issue. Get back to us, if you would like to re-take it.

**Comment by adarsh-ideal** [comment]
@mariobehling I want to work on this.

**Comment by adarsh-ideal** [comment]
Can I use mate flavour.

**Comment by adarsh-ideal** [comment]
@mariobehling Should I switch all system sounds

**Comment by adarsh-ideal** [comment]
@mariobehling Sir! Please give me the answers so that I can complete the build fast.

**Comment by adarsh-ideal** [comment]
@mariobehling One thing more, could this be a GCI task?

**Comment by mariobehling** [comment]
> - Can I use cinnamon flavour.

Yes.

> - Should I switch off all system sounds.

Yes.

> -  Fx??

Firefox.

> - What do you mean by deactivate home folder.

Forget about this for now.

> - Authohide panel (Which panel)?

Bottom panel. If you are using Cinnamon, please set to "Intelligently auto-hide panel"

Please also document how you create the distro. The idea of this project is not just to use some remix, but to actually build the distro with scripts. In the first step, you can create a prototype with some automatic build tools. Please let us know what you are using and how you do it.

**Comment by adarsh-ideal** [comment]
@mariobehling Should I remove libreoffice to minimize size of distro or do we need it?

**Comment by adarsh-ideal** [comment]
### Method I am using to create distro:
- Using LiveCD image. Extracted filesystem.squashfs.
- Setup a chroot environment and create required mount points.
- Did the required changes
- Built the ISO image using mkisofs.

**Comment by mariobehling** [comment]
> Should I remove libreoffice .. to minimize size of distro or do we need it?

We need it.

> and other useless software 

which one?

**Comment by meets2tarun** [comment]
Can one use susestudio.com to build the distro ?

**Comment by mariobehling** [comment]
@meets2tarun The goal is to build the distro from scratch through a script.

**Comment by meets2tarun** [comment]
Can we use LFS ?

**Comment by mariobehling** [comment]
> LFS

I am not familiar with LFS. If the distro is build from scratch and provides an automatic build process in the end we reach our goal.

**Comment by meets2tarun** [comment]
What's your way to build a distro ?

**Comment by mariobehling** [comment]
See: https://github.com/fossasia/meilix

**Comment by Abhi2424shek** [comment]
@mariobehling LFS means Linux from scratch it would need to be cross compilled ti be used for many architectures and contains many unwanted programs which can be steipped of in an event OS, @meets2tarun i recommend to remove some unwanted programs. @mariobehling, however it is well documented and help can be found 24/7 everywhere on the internet, if you guys want to build it then I am also ready to help, how ever note that the whole system including the tool chain would be build from scratch. IMO LFS is a learning experience. But we could use either way, you can decide for that, I would happy to help @meets2tarun :)

**Comment by meets2tarun** [comment]
@Abhi2424shek @mariobehling  we will work on this

**Comment by Abhi2424shek** [comment]
`we` ---- I am sorry I can't code, without a PC. I would be happy to help. @meets2tarun

**Comment by xeon-zolt** [comment]
i am sorry but i am still little unclear what do you mean by linux distro for events
i am very interested in this project

**Comment by xeon-zolt** [comment]
i think that archiso can be used to make a custom linux distro and all those can be added as configuration scripts and even better write a installer that can take configuration from git during the installer according to event

**Comment by SpEcHiDe** [comment]
I am interested in working on this issue. Can anybody guide me on how to proceed?

**Comment by hiamandeep** [comment]
@mariobehling I am very much interested in this. Ubuntu Customization Kit (UCK) can be used on its derivative distro, since Linux Mint is a derivative of Ubuntu it can be used on it too.
How about I proceed with this?

**Comment by meets2tarun** [comment]
@hiamandeep UCK will not give such freedom to customize the OS to the extent which is being needed for this issue.

**Comment by gayanW** [comment]
Unpacking, chrooting, then doing necessary customizations, modifications and clean up can satisfy most of the listed requirements IMHO.
May be we could also try the standard Debian live-build approach if there's no particular reason for using Mint.

**Comment by rnikhil275** [comment]
Hey, I am Nikhil. R from India. I am interested in working on this project as part of GSoc '17. I was wondering what the scope of the project is ? What should be the final outcome ? Is just a distro file with the above requirements enough ? Should the scripts and other necessary build process be reproducible and portable so that it can reproduced on some other distro with similar DE, PPA etc ?

I don't know who the mentors are yet. From what I gather from the conversation above, maybe @mariobehling can help me out in explaining the scope of the project and the final deliverables ?

**Comment by meets2tarun** [comment]
@mariobehling @Abhi2424shek 
Sir
Checkbox 11 (which is newly added) is meant to apply for only chromium (default) or all 3 browsers.
The start page and 'restart with last opened tabs' can be done itself in a browser but as mention, these should be already done during installation of OS.
And if chromium crashed due to the uncertain crash of PC, then chromium and chrome generally ask for the restore tabs rather of opening the 'last opened tabs'. 'Restart with last opened tabs' is primarily beneficial if close the chrome accidently and then opened it to see the environment as before closing.
In such case redirecting start page to http://2017.fossasia.org is effective for the first time only.

Pre-installation of both chrome and chromium doesn't seem fine here since both have the same purpose and it's going to contribute in increasing in size also.
Checkbox 5 the bookmarks disabling, I think it's also not a good option since we are opening the tabs from 'last opened tabs' and if one needs bookmarks for future purpose, he is not going to keep that tab open and opened tabs takes RAM (especially chrome and chromium).

**Comment by ggandhi27** [comment]
Guys I liked the idea of this project.
I am very much interested in contributing to this project.

**Comment by ggandhi27** [comment]
Sir , 
I am interested in the project idea and want to start work on this. 
@mariobehling  sir I just want to know that we have to contribute to this project https://github.com/fossasia/meilix ?

**Comment by xeon-zolt** [comment]
@mariobehling  i have made a partial compile script to compile a distro with above requirements https://github.com/xeon-zolt/Event-linux

**Comment by simsausaurabh** [comment]
@mariobehling 

I want to add some more suggestions and i am willing to work on these - 

1. creating media server.
2. Setting brightness to default each time system reboots.
3. Gedit plugins to make it more user friendly.
4. Blog from home.
5. script to disable Bluetooth( default enabled ) in every reboot.

**Comment by meets2tarun** [comment]
- [x] Use LXQT (Issue #??)
- [ ]  Switch off notifications
- [ ]  Switch off screensaver and sleep modus 
- [ ]  Switch off system sounds (https://github.com/fossasia/meilix/pull/112)
- [x] disable bookmarks in browser (Issue #??)
- [ ] Install ownCloud/NextCloud client
-https://download.owncloud.org/download/repositories/stable/owncloud/
- [x]  install Dropbox
- [ ]  Pre-set start system without password (DONE, happens in live image)
- [ ]  install Gtalk/Hangout
  - unofficial app yakyak 
  - chromium extension app
  - pidgin messenger configured for hangout (only chatting not video/calling)
  - ".desktop" file which opens a browser which supports hangout on the hangout page in /usr/share/applications
- [ ]  install Firefox (Issue #??) 
- [ ] Chromium
- [ ]  set Chromium as default
- [x]  set custom start page and set "re-start with last opened tabs" (in case laptop is crashing)
- [x]  install git (Issue #??)
- [ ]  change desktop background with custom image
- [ ]  update to latest version (without password)
  - [X] sudo apt-get update happens to the system before the ISO is created
- [ ]  switch off screen dimming (https://github.com/fossasia/meilix/pull/113)
- [ ]  switch off power management saving features (https://github.com/fossasia/meilix/pull/110)
- [ ]  link to the slide folder from the desktop (edit "make a link")
- [x]  authide panel (Issue #??)(https://github.com/fossasia/meilix/pull/109)
- [ ]  install local language keyboard layouts
  - might be a user configuration
  - There are a limited number of keyboards, same like with packages
  - all keyboards are preinstalled
  - there is a menu somewhere which may only appear if you as a user can choose between several languages. There, these languages should appear
  - TODO: Create an issue for this
- [x]  install VLC
- [ ] VLC  set as standard video player
- [x]  install LibreOffice, Gimp, Inkscape
- [x]  set search engine
- [ ]  distro referrals: Amazon Referral link: When someone buys on ISO, supports This iso

Discard:
- [ ] install chrome (https://github.com/fossasia/meilix/issues/117)

**Comment by tabesin** [comment]
Switch off notifications is ticket #133. It does not mean de-installation of the notifications demon but killing off startup messages.
Switch off system souncs means systems sounds, not sound as such.

**Comment by abishekvashok** [comment]
Can we get updates here?

**Comment by mariobehling** [comment]
Please follow up here: https://github.com/fossasia/meilix-generator/issues/111

**Comment by Kreijstal** [comment]
A small script containing automating some of the issues here, as a sketch
```bash
#!/usr/bin/bash
sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo apt-get install -y apt-transport-https w3m openssh-server vlc weechat git adobe-flashplugin browser-plugin-freshplayer-pepperflash nautilus-dropbox lxqt dconf-cli chromium-browser libxss1 libappindicator1 libindicator7 apt-transport-https ca-certificates curl software-properties-common
curl https://repo.skype.com/data/SKYPE-GPG-KEY | sudo apt-key add -
echo "deb https://repo.skype.com/deb stable main" | sudo tee /etc/apt/sources.list.d/skypeforlinux.list
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
sudo apt-get update
sudo apt-get install -y skypeforlinux docker-ce sublime-text-installer
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb
sudo apt-get install -f
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
source ~/.bashrc
nvm install 6

dconf write /org/cinnamon/desktop/interface/clock-show-date true

##### Sound settings.
dconf write /org/cinnamon/sounds/login-enabled false
dconf write /org/cinnamon/sounds/logout-enabled false
dconf write /org/cinnamon/sounds/unplug-enabled false
dconf write /org/cinnamon/sounds/tile-enabled false
dconf write /org/cinnamon/sounds/plug-enabled false
dconf write /org/cinnamon/sounds/switch-enabled false

##### Power settings.
dconf write /org/cinnamon/settings-daemon/plugins/power/button-power "'interactive'"
dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-inactive-ac-timeout 0
dconf write /org/cinnamon/settings-daemon/plugins/power/critical-battery-action "'hibernate'"
dconf write /org/cinnamon/settings-daemon/plugins/power/idle-dim-time 90
dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-inactive-battery-timeout 0
dconf write /org/cinnamon/settings-daemon/plugins/power/lid-close-ac-action "'nothing'"
dconf write /org/cinnamon/settings-daemon/plugins/power/lid-close-battery-action "'nothing'"
dconf write /org/cinnamon/settings-daemon/plugins/power/idle-brightness 100
dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-display-ac 600
dconf write /org/cinnamon/settings-daemon/plugins/power/sleep-display-battery 600

#no notifications
dconf write /org/cinnamon/desktop/notifications/display-notifications false
#wget https://ixquick-proxy.com/do/spg/show_picture.pl?l=english&rais=1&oiu=https%3A%2F%2Fi.ytimg.com%2Fvi%2FopTDVE-dwEo%2Fmaxresdefault.jpg&sp=a489742ed186d2cff71453b508e3308e
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
ssh-add ~/.ssh/id_rsa
```
