### ISSUE TITLE
Track Emojis on Twitter and show them on a map using the loklak API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#136]
Track Emojis on Twitter and show them on a map using the loklak API. Let's get inspired by the Emoji tracker: https://github.com/mroth/emojitracker

Can we show emojis used on twitter on a map and generate statistics for regions to track the mood of people around the world?

**Comment by enigmaeth** [comment]
@mariobehling I want to work on this project. Is there any issue with this project being labeled as GCI?

**Comment by mariobehling** [comment]
@enigmaeth No problem. Anyone can take up this issue.

**Comment by PolBaladas** [comment]
Hi, can I still work on this project?

**Comment by mariobehling** [comment]
@PolBaladas Sure, it is perfectly fine to get two implementations.

**Comment by PolBaladas** [comment]
Thanks! 
https://github.com/PolBaladas/Loklak_EmojiTracker

**Comment by PolBaladas** [comment]
Would it be better:
     1. to search for a specific emoji (search bar) and display its istances on the map
     2. to search for all emojis and render them on the map

**Comment by mariobehling** [comment]
> 2. to search for all emojis and render them on the map

Maybe start with 2 and see how it goes and in future we could think of an emoji heatmap

> Can loklak get "streaming" tweets?

We do not have that currently. This is more challenging and would take some time. Please try to do without it for now.

**Comment by PolBaladas** [comment]
Okay, atm it looks like searching for specific emojis can't be done using loklak's search API. Same thing with Twitter's. 

This is indeed a challenge....

**Comment by singhpratyush** [comment]
Hi!

This project seems to be very interesting. Please guide me for going further in it.

Just a few questions -

* What should the map look like?
  * Number of emoji at the selected location.
  * Popping up emojis on the map as they are Tweeted.
* The `emojitracker` project mentioned turns out to be providing real time data. Do we need to do the same? If yes, how shall we use loklak's API for the purpose?
* Are there any restrictions or suggestions for technologies to be used?
* Where can we discuss about this (IRC, Gitter, ML)?

**Comment by mariobehling** [comment]
https://gitter.im/loklak

**Comment by MehndirattaPiyush** [comment]
@mariobehling has this issue has been assigned to @singhpratyush  or its still open.

It seems intriguing to me and i want to start contribution to fossasia.

**Comment by isuruAb** [comment]
It seems like really interesting .I would like to contribute this one.

**Comment by kamsuri** [comment]
Hi @mariobehling , I'm interested in this project for GSoC'17. Please let me know how can I start contributing to this project. 
Thank you

**Comment by singhpratyush** [comment]
I have drafted and submitted a proposal for this project. Please review and give feedback.

**Comment by 0x48piraj** [comment]
Any updates @singhpratyush ?

**Comment by singhpratyush** [comment]
This was implemented by @kavithaenair during GSoC 2017.

@mariobehling: This issue can be closed now.
