### ISSUE TITLE
Identify and Fix Issues for 2012 FOSSASIA Summit page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#137]
There are a number of design and code issues with the FOSSASIA 2012 site at http://2012.fossasia.org
1. Please identify issues.
2. List them in the issue section of the repository https://github.com/fossasia/2012.fossasia.org/issues
3. Fix the issues and discuss possible questions in the issue tracker

Repository: https://github.com/fossasia/2012.fossasia.org

**Comment by 0x48piraj** [comment]
> If I reference the issues like https://github.com/fossasia/2012.fossasia.org/pull/154, it will uselessly reference and will notify all the reviewers, developers, maintainers which interacted with the following Pull Requests. So, I'll refrain from doing this :+1: 

- **_# 154_**
- **_# 120_**
- **_# 100_**
- **_# 94_**
- **_# 41_**
- **_# 46_**

> **_However, You can see any Pull Request by using `https://github.com/fossasia/2012.fossasia.org/pull/` + `PR_Number`_**

Ping @mariobehling :heart_decoration:
