### ISSUE TITLE
Get 2009 Event Website online at 2009.fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#139]
In 2009 the FOSSASIA community organized the GNOME.Asia summit. Unfortunately the site has been lost, but there is a snapshot on the Internet Archive here: https://web.archive.org/web/20130827220300/http://2009.gnome.asia/

**Comment by jig08** [comment]
@mariobehling If required, I can help with this

**Comment by mariobehling** [comment]
Ok, great. Yes, please do.

**Comment by shubham-padia** [comment]
@mariobehling  fossasia/2009.fossasia.org#1 intends to add  files  for  the `2009.fossasia.org` website which was built upon on `cordobo-theme-park-2` wordpress theme . [Click here](http://shubhamp.in/wp/) to see the replica of `2009.fossasia.org`  in action . The web archived site can also be viewed [here](https://web.archive.org/web/20120324000651/http://2009.gnome.asia/index.html).

**Comment by mariobehling** [comment]
Thank you so much! I had to change the links to your page in the DB, but now it works. Next steps are:
* [ ] to import the Vietnamese pages
* [ ] to show images in WP media
* [ ] to add a dropdown menu to FOSSASIA event probably using https://codex.wordpress.org/Appearance_Menus_Screen

**Comment by mariobehling** [comment]
Thanks for your support!
