### ISSUE TITLE
link to mentor contact details

### ISSUE THREAD

**Issue by eMBee** [fossasia/labs.fossasia.org#14]
it would be nice to have a way to connect to mentors when reading a project.
we have mentor contacts on fossasia.github.io, but i can't see a way to link to there.

**Comment by todipratik** [comment]
how about having a list of all mentors (along with their github, web and social profile links) in a file. And displaying these along-side the name of the mentors

**Comment by eMBee** [comment]
well, i want to avoid duplicate details, but maybe we need to do something like that.

**Comment by ty221** [comment]
My last commit to fossasia.github.io may be helpful @eMBee : https://github.com/fossasia/fossasia.github.io/commit/a964f61d8f6a6c419f66549f613eaf6e223ffad4
