### ISSUE TITLE
Design a logo for FOSS.vn

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#141]
We need a logo for http://foss.vn

Requirements
* Use Inkscape or another Open Source tool.
* Offer logo in svg
* All logo components need to be vector graphics
* Make a pull request to upload the logo to https://github.com/fossasia/foss.vn/

**Comment by rohanagarwal94** [comment]
@mariobehling I completed this mini-project and my pull request got merged too. Please close this.
