### ISSUE TITLE
Update with Wordpress Cordoba theme and add menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#143]
- [ ] add a dropdown menu to FOSSASIA event probably using https://codex.wordpress.org/Appearance_Menus_Screen -> https://github.com/Cordobo/green-park-2/issues/26
- [ ] Add Support for Theme Customization API https://github.com/Cordobo/green-park-2/issues/9
- [ ] Make all sidebars widget ready
- [ ] Disable Advertising area ("Advertisement")
- [ ] Make theme responsive

**Comment by nidhinmahesh** [comment]
Hello, I am interested in doing this as I have done something like this for my project.

**Comment by mariobehling** [comment]
Great, please go ahead.

**Comment by Abhi2424shek** [comment]
@nidhinmahesh updates?

**Comment by nidhinmahesh** [comment]
extremely sorry for the delay. My exams just got over. I am halfway done and rest will be completed soon!

**Comment by Abhi2424shek** [comment]
Sure
