### ISSUE TITLE
Import student articles of GSoC students into blog

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#144]
Please import the posts into the Wordpress blog. Preferably offer a Wordpress XML import file.
http://zyzo.github.io/categories/#fossasia

**Comment by abhishekg785** [comment]
@mariobehling 
I will like to work on this.
Can you give an explanation of the task ?

Thanks
Abhishek Goswami

**Comment by mariobehling** [comment]
@abhishekg785 Cool.

How it works with us usually. Just start working on things and follow up on the way. No need to get assigned. Cheers.

**Comment by YashKumarVerma** [comment]
claiming @mariobehling

**Comment by YashKumarVerma** [comment]
XML export available here : https://github.com/YashKumarVerma/demoContent/blob/master/exportedDocs.wordpress.2017-12-17.xml

**Comment by mariobehling** [comment]
Thanks! 

Good start, but the xml only imports two articles. Please check that all GSoC and FOSSASIA articles get imported. Cheers.

**Comment by YashKumarVerma** [comment]
sorry @mariobehling  actually i did the entire thing but while exporting, didn't check that some of the posts were drafts. now all are there 😄 
![screenshot 236](https://user-images.githubusercontent.com/14032427/34082361-9fa58a04-e382-11e7-8461-d95b354d07e7.png)

**Comment by YashKumarVerma** [comment]
here's the new exported file 👍 
https://github.com/YashKumarVerma/demoContent/blob/master/exportFile.xml

**Comment by YashKumarVerma** [comment]
@mariobehling

**Comment by YashKumarVerma** [comment]
😐

**Comment by mariobehling** [comment]
Good job! Well-done!

**Comment by YashKumarVerma** [comment]
Thanks :sparkles
