### ISSUE TITLE
Contribute to FOSSASIA knitting projects

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/labs.fossasia.org#145]
There are some people in FOSSASIA, like me, who work on creating clothes from knit work.
You can learn to contribute to the different software by reading on [knitting.fossasia.org/](http://knitting.fossasia.org/).

There are various ways to contribute. I invite you
- to edit [the site](http://knitting.fossasia.org/) with me to make even clearer, how to start and contribute to the projects listed on the site.
- to contribute to the projects listed on the site.

**Comment by rahulchawla1995** [comment]
can i help u in editing this site....i am more than willing to contribute to this mini project

**Comment by niccokunzmann** [comment]
@rahulchawla1995 sure, you can. I just clarified that you can contribute to all projects on the site. They already have some issues. If you find out something you would improve, you can create an issue to discuss it. If you have any questions, you can ask.

**Comment by 0x48piraj** [comment]
@niccokunzmann 

I can jazz this website. Should I ?

**Comment by 0x48piraj** [comment]
@mariobehling, As I got inputs from @niccokunzmann, I think the issue already has been resolved. :+1:
