### ISSUE TITLE
Create a sitemap.xml and html site of fossasia.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#147]
Please create a sitemap as outline in https://github.com/fossasia/fossasia.org/issues/46
- [ ] sitemap.xml at http://fossasia.org/sitemap.xml
- [ ] an index.html sitemap at http://fossasia.org/sitemap/
- [ ] Include subdomains and the blog

**Comment by Abhi2424shek** [comment]
@mariobehling can I write a script that generates a sitemap when travis runs and checks the code at the repository if the files match and if submit a new PR from travis, so that we don't have to do anything when a new file is added via a commit.

**Comment by Abhi2424shek** [comment]
This is done @mariobehling
