### ISSUE TITLE
Help to build a custom Linux distribution

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#150]
The relevant repository for this task is here: https://github.com/fossasia/meilix

If you have solved one of the point also confirm it here https://github.com/fossasia/meilix/issues/3
- [ ] Update script to latest ubuntu version 16.10 and compare to lubuntu version (http://bazaar.launchpad.net/~lubuntu-dev/ubuntu-seeds/lubuntu.yakkety/view/head:/desktop-qt)
- [ ] Create a meta package for the distro (some useful documentation https://blends.debian.org/blends/apb.html)
- [ ] Add additional language packs and fonts for Asian languages
- [ ] Add skype 
- [ ] Substitute qupzilla browser with Google Chrome in meta package
- [ ] Define specific search engines
- [ ] Substitute SMPlayer with VLC in meta package
- [ ] Substitute nomacs with lximage-qt
- [ ] Take out 2048 (Qt) - Sliding block puzzle game
- [ ] Take out nobleNote - Application to take notes
- [ ] Take out usb-creator-kde
- [ ] Add our repo as additional PPA
- [ ] Create and define
- [ ] Krita
- [ ] Enhance and and change lubuntu-qt-desktop for use in community distro

Optional: \* instead of using LXQT from launchpad use LXQT from github repo https://github.com/lxde/lxqt (more info also here: https://github.com/selairi/compile-lxqt-ubuntu)

**Comment by balumenon96** [comment]
Hi, I just completed my GSoC project with Debian. I can help you guys with this. I have tried something similar for my college. What should I do to start with this project?

**Comment by mariobehling** [comment]
Hi, please join our slack channel here https://fossasia.slack.com/messages/linux/ 

Anyone who needs an auto invite, can get it here http://fossasia-slack.herokuapp.com/

First step, please start by building the distro with the data in the repository here: https://github.com/fossasia/meilix

Second step: Create a subissue of a point you want to work on (See https://github.com/fossasia/meilix/issues/3 for an overview) and help to solve them step by step.

Would be great to get this going!

**Comment by Abhi2424shek** [comment]
@mariobehling i am in with this... Can I,

**Comment by Abhi2424shek** [comment]
@mariobehling skype was done already... So tick that sir :)

**Comment by Abhi2424shek** [comment]
@mariobehling please post the updates here too...

**Comment by Abhi2424shek** [comment]
@mariobehling please can you update the progress here too with respect to the meilix project!

**Comment by mariobehling** [comment]
@Abhi2424shek Feel free to do it. Cheers.

**Comment by Abhi2424shek** [comment]
@mariobehling not having push access to edit the check boxes sir, however I may close this issue in the near future for sure.

**Comment by mariobehling** [comment]
Ok, got it. Thanks.

**Comment by Abhi2424shek** [comment]
I am still on progress, i am mentioning because I don't want you all to be annoyed.

**Comment by Abhi2424shek** [comment]
Still in progress,

**Comment by abishekvashok** [comment]
Wasn't this solved? @mariobehling
