### ISSUE TITLE
Enhance susper.com search with search options, new design, internationalization features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#152]
The [susper.com](http://susper.com) search engine is using the yacy peer to peer network to gather results. It uses enhanced search features. The front end is developed with backbone.js.

Please help 
- to update the theme to the latest search engine site
- add more search options
- implement internationalization features

You find the repository here: https://github.com/fossasia/susper.com/issues/

The code is at https://github.com/fossasia/susper.com

**Comment by abhiwer** [comment]
sir,
if you can add more search options example....
If I type some word with or without meaning...
>It can show / crawl the web for its meaning as well as word with tlds<domains>extensions.
It would be best.

>

**Comment by ragnerok** [comment]
I would like to take this one up !
Could you be a little bit more specific as to what other search options need to be added and what kind of theme is required ?
Thanks

**Comment by mariobehling** [comment]
@ragnerok Ok, great. Please go ahead and follow up about details in the repo.

**Comment by Marauderer97** [comment]
@mariobehling I would like to work on this over the summer. Where can I find more details about this project?

**Comment by sudheesh001** [comment]
To those who want to contribute to the project, please set it up, send a patch to the project and at the same time, please draft the proposal and share it across. The gitter channels are open for discussion

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 there are alot new issues raised on the repo regarding enhancements , and mostly all enhancement issues on the repo will fall into this project.go through them.

**Comment by 94151** [comment]
@mariobehling I want to work on this issue. can you please provide me more details regarding this issue?
