### ISSUE TITLE
Implement support for export/import of other formats for the FOSSASIA event system

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#153]
The goal of this project is a) to implement the Open Event format in other systems and apps (frab, Giggity etc.) and b) to implement other formats in Open Event.

There is one relevant issue in the event server project already: Propose and implement import support for other formats https://github.com/fossasia/open-event-orga-server/issues/2185

**Open Event**: The Open Event Project offers event managers a platform to organize all kinds of events including concerts, conferences, summits and regular meetups. The components support organizers in all stages from event planning to publishing, marketing and ticket sales. Automated web and mobile apps help attendees to get information easily. There are four components of the project:

1. The Open Event Format Definition [[JSON Schema Sample](/sample/)]

2. The Open Event Orga Server [[Repository](https://github.com/fossasia/open-event-orga-server)]

3. The Open Event Android App Generator [[Repository](https://github.com/fossasia/open-event-android)]

4. The Open Event Web App Generator [[Repository](https://github.com/fossasia/open-event-webapp)]

The source code of each component has its own repository and technology stack. The software applications can be hosted as stand alone solutions or they can be integrated as microservices into the Open Event Orga Server through APIs. 

**Communication**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event and **Our chat channel** is here: https://gitter.im/fossasia/open-event

**Open Event Format Definition**: The Open Event project enables the exchange of data between all components as well as with other services through a standardized Format. The Open Event repository provides a sample implementation of the format. It includes JSON files for all relevant event information and binary data for images and audio files. **Repository:** https://github.com/fossasia/open-event

**Open Event Orga Server**: The Open Event Orga Server enables organizers to manage events from concerts to conferences and meet-ups. It offers features for events with several tracks and venues. Event managers can create invitation forms for speakers and build schedules in a drag and drop interface. The event information is stored in a database. The system provides API endpoints to fetch the data, and to modify and update it. Organizers can import and export event data in a standard compressed file format that includes the event data in JSON and binary media files like images and audio. The **Repository**: https://github.com/fossasia/open-event-orga-server and the **Communication Channels**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event. Our chat channel is on Gitter here: http://gitter.im/fossasia/open-event-orga-server

**Demo version**: 
A demo version is automatically deployed from our repositories:
* Deployment from the master branch - http://open-event.herokuapp.com
* Deployment from the development branch - http://open-event-dev.herokuapp.com
* Developer documentation gh-pages - http://dev.eventyay.com

**Comment by Jatinbalodhi96** [comment]
If this issues is still open and not assigned can you @mariobehling tell me more about it?

Thanks 
Jatin

**Comment by Abhi2424shek** [comment]
@Jatinbalodhi96 the first one is fixed and the second one is almost, can you comment on the issue mentioned, currently we need to accept imports from xCal format more only

**Comment by bhaveshAn** [comment]
> I hope its already done in Open Event Server at https://github.com/fossasia/open-event-server/blob/development/app/api/imports.py and https://github.com/fossasia/open-event-server/blob/development/app/api/exports.py

@SaptakS 
If I am getting wrong then please correct.

**Comment by mariobehling** [comment]
It is not working continuously and we need someone to work on this for version two and ensure it works.

**Comment by ssirowa** [comment]
@meets2tarun, I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.

**Comment by ssirowa** [comment]
@mariobehling , I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.
