### ISSUE TITLE
Add asksusi to project list on site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#154]
Add asksusi.com to project site.

**Comment by jig08** [comment]
@mariobehling Could we close this issue, seems to have been resolved. 

<img width="1280" alt="screen shot 2016-09-07 at 8 22 13 pm" src="https://cloud.githubusercontent.com/assets/9291400/18316594/d9a36334-7538-11e6-8232-146a085557b9.png">
