### ISSUE TITLE
Fix issue of speaker images in 2016 site.

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#157]
Speaker images are squeezed in some resolutions in the 2016 fossasia site at http://2016.fossasia.org

Speaker Images not scaled properly https://github.com/fossasia/2016.fossasia.org/issues/74

**Comment by sandmanx** [comment]
@mariobehling I feel you can close this with respect to PR https://github.com/fossasia/2016.fossasia.org/pull/112

**Comment by jig08** [comment]
@sandmanx Thanks !
