### ISSUE TITLE
Develop a simple Query Server that stores a query string on a server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#164]
Write a simple web server application that can be used to process a query string. This string shall call the Google search result scraper at https://github.com/fossasia/searss and the output from the scraper is written to a file, named with the query string as file name.

Follow up to: https://github.com/fossasia/labs.fossasia.org/issues/163

**Comment by mjnovice** [comment]
@mariobehling Just curious, what is the motivation behind it ?

**Comment by mariobehling** [comment]
This is a follow up to #163 and could enable scientists to collect Google search results in a specific area that could be analysed e.g. with Kibana.

**Comment by enigmaeth** [comment]
@mariobehling I have developed the query-server [here](https://github.com/enigmaeth/query-server) using the rss-generator at [searss](https://github.com/fossasia/searss) in #163 .

This takes care of #165 (when a query is done for a string, which already exist in the file storage) also.

Please take a look at this.

**Comment by mariobehling** [comment]
Awesome! Let us go through it.

Please make a pull request to: https://github.com/fossasia/query-server

**Comment by enigmaeth** [comment]
@mariobehling Hey I had my term exams!
We can continue on this server. I hope to start with fixing the open issues on the **[fossasia/query-server](https://github.com/fossasia/query-server)** repo. Working on closing this issue soon from labs.fossasia.org .
Thanks.

**Comment by enigmaeth** [comment]
@mariobehling This can be closed now. 

The repo is here :  https://github.com/fossasia/query-server
And the server is deployed here : https://query-server.herokuapp.com/

**Comment by enigmaeth** [comment]
@mariobehling This can be closed now.

The repo is here : https://github.com/fossasia/query-server
The server is deployed here : https://query-server.herokuapp.com/
