### ISSUE TITLE
Implement a DoubleTerm Check as an Add-on for Query Server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#165]
This is a follow up to the Query Server development project at https://github.com/fossasia/labs.fossasia.org/issues/164

Whenever a query is done for a string, which already exist in the file storage for the query server, just nothing should happen. There should be no action in case of double-occurring queries.

**Comment by enigmaeth** [comment]
@mariobehling Should we close this one now?

**Comment by mariobehling** [comment]
@enigmaeth Good. Thank you. Still waiting for the feedback of @Orbiter as well.
