### ISSUE TITLE
Implement an additional trigger in Susper to send search queries to a second service

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#166]
The susper repository is hosted here https://github.com/fossasia/susper.com

Please implement an additional trigger in Susper to send search queries to a second service.

When Susper retrieves search results from its back-end, it shall send the query to an additional back-end server. There should be no processing of the result and no waiting for the result. There should be a configuration option for this second back-end address.

There are many use cases for this.

One purpose could be that the search results of one search engine can be compared with the results of another. 

Another way is to provide answers for AI systems, that are most relevant.

It would also allow to collect data of search results and compare them scientifically giving scientists a tool at hand to validate search results and compare them over time.

At this point of time many possibilities can be imagined for the service, but it would be too much to go into detail as the next steps depend on the development path. At this point of time, the main goal is to implement the additional trigger, so the next steps will be possible.

**Comment by sandeepm96** [comment]
Sir, if you could be more elaborate about why the query needs to be send to an additional back-end. I am a bit unable to understand the problem statement.

**Comment by mananpal1997** [comment]
@sandeepm96 I think that one server should be duty-free, and only serve as I/O to a user while the other server will handle all the processing. If processing is also done on the same server, interaction with other user may be affected.
@mariobehling Am I correct?

**Comment by mariobehling** [comment]
Updated the description with more info.

**Comment by mariobehling** [comment]
Please follow up for details here: https://github.com/fossasia/labs.fossasia.org/issues/166

**Comment by tirth97** [comment]
@mariobehling  Is this issue fixed or can I take it up as a GSOC proposal. I had a few AI algorithms in mind if the project is to be implemented based on most relevant information.

**Comment by mariobehling** [comment]
Please start contributing to learn more about the details of the project. Contributing to a project will give you a good chance to become a GSoC student.

**Comment by subhahu123** [comment]
@mariobehling  i want to work on this issue

If i'm not wrong , u re saying that susper should have a toggle switch button on its nav bar to switch to another back end search engine other than yacy and apache solr ....
but these search engine (like yacy) is also depends on others like they use others api to find the results .
what does this means ( this issue )

**Comment by subhahu123** [comment]
@mariobehling  And what can be others backend servers like 
 duckduckgo api (not completely accessible)
bing search api ( unlimited queries per day free)
yahoo ( basically depend on bing )
