### ISSUE TITLE
Github Repository link not aligned properly!

### ISSUE THREAD

**Issue by amarlearning** [fossasia/labs.fossasia.org#168]
Fossasia GitHub repository link not aligned properly!
![screenshot from 2016-11-12 04-19-45](https://cloud.githubusercontent.com/assets/9383897/20232613/82d1feb4-a88f-11e6-88e5-e939616b2f7e.png)

**Comment by ashwini0529** [comment]
@amarlearning  Please check https://github.com/fossasia/labs.fossasia.org/pull/169

**Comment by rajeev29five** [comment]
@jig08  i think all the links on webpage should be aligned for better look , for instance the links in the screenshort below and other links on the page.

![issue](https://cloud.githubusercontent.com/assets/16323302/20265166/84df14c8-aa95-11e6-89f1-02fc2cc53c0f.png)

**Comment by ashwini0529** [comment]
Assign this to me. I'll do it.
