### ISSUE TITLE
Propose and implement a "teaching mode" for Susi

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#172]
The question behind this project is:  How can users teach Susi and improve the answers?

An idea is to offer a "teaching mode" in the Susi app. This teaching mode in its most simple form could provide a feedback loop. As Susi provides an answer to a question an addition option is shown to the user: e.g. Was this answer correct? Yes/No.
The user can give feedback in the app and with the help of machine learning Susi can improve future answers.

To achieve this, it needs to be
a) implemented in the server (https://github.com/fossasia/susi_server) and,
b) in the app. https://github.com/fossasia/susi_android

Please propose and implement this feature.

**Comment by Orbiter** [comment]
For the implementation in the app (b) the following process would be appropriate:
- In case that the user does not like the answer, the user is able to click a button at/near/somewhere at the answer line named with (i.e.) "enhance answer", "give feedback", "propose different answer" etc (one of them, to be decided).
- after the user clicked that button a screen containing the following entities is shown
 - alternative answers (if any)
- an input field "propose your own answer".
- When any of the options provided is used, the client sends a normal query to the backend containing the sentence "on '<the original query>' answer '<the now proposed answer>'".
- the app then continues with whatever susi responds on this  request. Maybe it says 'thank you' or also askes the user to help out with another information topic.

**Comment by Abhi2424shek** [comment]
Can I work on this @mariobehling @Orbiter

**Comment by y73isc00l** [comment]
@mariobehling @Orbiter  I have already implemented such a system in an app which I had made as part of a college competition.The app's backend is in flask and heavily relies on python library nltk,the data of each user conversation in stored in firebase and more the user interacts with the bot in different categories,the more the bot learns questions and answers.If you would like I would like to send the apk of the app created.Please tell the channel through which I can send.I would like to merge the capabilities of both SUSI and my app to create a chatbot that can be created without writing any code.
The link to code's backend repository [https://github.com/y73isc00l/botguise](url)

**Comment by mariobehling** [comment]
@y73isc00l Nice. Do you have a link to a live system to test your work? There are different options to start getting engaged in the SUSI AI project. Please join us on the chat channel and start checking out the SUSI server to understand how we can add the teaching mode.

**Comment by y73isc00l** [comment]
Actually it is an android app and you can download it from drive folder https://drive.google.com/folderview?id=0B8m3ShszCn_kQXFzWU04QmxLRk0

**Comment by y73isc00l** [comment]
The training mode is only properly working nice in the Harry potter pack.If you find any error like servor down please ping I will solve it and get back to you.

**Comment by y73isc00l** [comment]
The app makes API calls to the server botguise3134.cloudapp.net

**Comment by vaibhavsingh97** [comment]
@mariobehling @Orbiter I would like to work on this 😄 
Would love to share my approach to implement teaching mode.
