### ISSUE TITLE
Improve the CMS and Editor for SUSI Skills

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#173]
The questions behind this project are:
* How can users teach Susi?
* How can users add rules to Susi?
* How can users add an API (Skill, Action)?

For the first question there is a mini project here: https://github.com/fossasia/labs.fossasia.org/issues/172

Some ideas for a solution for the other questions below. Currently Amazon Alexa/Echo also offers a way to add so called Skills, that seems very complicated. We are looking for an easier way.

A possible flow of the editor app:

Step 1. Choose an existing API for a questions/answer schema. Could be a dropdown menu of APIs.

Step 2. Choose an attribute from the API, e.g. from the data field in a JSON, RSS etc. It could be "description", "link", "author", "integer", "date" or any field provided in the API data fields.

Step 3. Create a question pattern for Susi, for example "Where is *1?" 

Step 4. a) "*1" is the item provided by the API field. Answer could be e.g. "*1 is located at ...."

Step 4. b) It would be useful to categorize answers here, e.g. geolocation, region, country, city, date, time, age (free categorization might be best as it would allow a hug number of contributors to choose the best categories and as it would allow the system to adapt to new world developments, e.g. think of a category "US elections 2016")

Step  5. Test your answers in a test form field. The field shows a box "Ask Susi! Type your question here" and the generated answer based on the data entered from step 1-4. (It only caters for this one rule)

Step 6. The user confirms if the answer is correct or wrong. There is a questions and two buttons: Is this the correct answer you are looking for? Button a) Yes, Save. Button b) No, Continue Editing. (This will send you back to step 1)

Step 7. a) If the answer was "yes, save", the user will see the following message "Thank you! An administrator will look over your contribution. After we confirm the functioning, we will release it in Susi."

Step 7 b) If the answer was "no" the user will be send back to Step 1. All data should still be there, that the user can edit.

Step 8. There should be an admin section in the editor, where administrator get a list of all new rules. The should be able to click on them, test them, edit them and release them.

Other feature required are: A way to change permissions and different groups similar to Mediawiki.

Future features are allowing editing of rules by users and search functionalities.

**Comment by zamhaq** [comment]
@mariobehling I want to work on this during gsoc. One doubt, this editor can be web based, right?

**Comment by anshumanv** [comment]
@zamhaq I think it was done last year - https://github.com/fossasia/susi_skill_cms nonetheless I think it was not completed, so we can improve and complete it!

**Comment by zamhaq** [comment]
@anshumanv cool. Thanks for the info.

**Comment by mariobehling** [comment]
This is ongoing work. We need developers to work on this.

**Comment by priyankark** [comment]
@mariobehling Would be interested in working on this for GSOC . I am a beginner ...how do you suggest I start? Also I have developed a few Alexa skills and now their editor is really good with the recent update of their UI (February 15, 2018). Could consider gaining some ideas for features from that too.

**Comment by priyankark** [comment]
@anshumanv Thank you!
