### ISSUE TITLE
Fix the 2010.fossasia.org speaker and sessions display views

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#176]
It looks like during an update of the 2010 FOSSASIA summit site the display of speakers and sessions has been lost. The data is still in the system. However, the views are not working. 

Please indicate your understanding of Drupal and fix this issue. FOSSASIA mentors will give you access to the system.

**Comment by Abhi2424shek** [comment]
I would love to take it up but can only touch my pc after april, so if you could wait, i would

**Comment by Aakash-DD** [comment]
Is this issue still open?
i want to work on this
