### ISSUE TITLE
Enhance system features and organizer flow in server app, integrate with communication tools and social media

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#178]
The goal of this project is to make it easier for organizers to use the system. This includes implementing a more coherent design across pages and enhancing the system for speed improvements and security.

Specifically this projects aims to get improvements in the following areas:
* Improve the organizer features and flow of the server application
* Enhance the mailing system and options
* Implement better social media integration
* Implement stress and security tests of the system

**Open Event Orga Server**: The Open Event Orga Server enables organizers to manage events from concerts to conferences and meet-ups. It offers features for events with several tracks and venues. Event managers can create invitation forms for speakers and build schedules in a drag and drop interface. The event information is stored in a database. The system provides API endpoints to fetch the data, and to modify and update it. Organizers can import and export event data in a standard compressed file format that includes the event data in JSON and binary media files like images and audio.

**Repository**: https://github.com/fossasia/open-event-orga-server

**Communication**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event. Our chat channel is on Gitter here: http://gitter.im/fossasia/open-event-orga-server

**Demo version**: 
A demo version is automatically deployed from our repositories:
* Deployment from the master branch - http://open-event.herokuapp.com
* Deployment from the development branch - http://open-event-dev.herokuapp.com
* Developer documentation gh-pages - http://dev.eventyay.com

**Comment by ssirowa** [comment]
@meets2tarun, I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.
