### ISSUE TITLE
Implement search and big data services with machine learning in the server application, enable automatic import of events and enhance event analytics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#179]
The aim of this project is to develop Open Event into a one stop resource for events and a big data hub holding information on all kinds of events across the web.

To achieve this we need to implement search and big data services with machine learning capabilities = in the server application. Another part of this is to enable automatic import of events from other platforms and enhance event analytics.

The project will include to add the ability to connect to a [query server](https://github.com/fossasia/query-server) deployment and query for events.

Also compare open issues in this area: https://github.com/fossasia/open-event-orga-server/labels/search%20project

**Open Event Orga Server**: The Open Event Orga Server enables organizers to manage events from concerts to conferences and meet-ups. It offers features for events with several tracks and venues. Event managers can create invitation forms for speakers and build schedules in a drag and drop interface. The event information is stored in a database. The system provides API endpoints to fetch the data, and to modify and update it. Organizers can import and export event data in a standard compressed file format that includes the event data in JSON and binary media files like images and audio.

**Communication**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event. Our chat channel is on Gitter here: http://gitter.im/fossasia/open-event-orga-server

**Demo version**: 
A demo version is automatically deployed from our repositories:
* Deployment from the master branch - http://open-event.herokuapp.com
* Deployment from the development branch - http://open-event-dev.herokuapp.com
* Developer documentation gh-pages - http://dev.eventyay.com

**Comment by enigmaeth** [comment]
I am interested in taking up this project for Google Summer of Code, 2017.
I have worked on the [query-server](https://github.com/fossasia/query-server) in question and it has been deployed [here](https://query-server.herokuapp.com). 

@mariobehling  What should be our aim while implementing machine learning capabilities? 

Should I start with working around on this issue [Implement the query-server as a microservice](https://github.com/fossasia/open-event-orga-server/issues/2675)? This issue is about automatic import of events from eventbrite/Google/Bing into Open-Event server. 

Please let me know how should I proceed from here.
Thanks.

**Comment by mariobehling** [comment]
> Should I start with working around on this issue Implement the query-server as a microservice?

Yes, exactly. Please get started with that and let's explore from there step by step. There will be a lot of details on the path to get the import right and we need to fix issues on the way. So, Machine Learning will be the next step after that. Think of how we could plugin SUSI AI to Open Event and let users ask questions like "What is going on tonight?". The a number of events are displayed based on the users profile and past etc. This would required AI capabilities, but before we get there, let's get the basics right.

**Comment by SparshBansal** [comment]
@mariobehling I would like to work on this too. I am a machine learning enthusiast and would love to contribute here. I have done many machine learning projects and I think this a great opportunity for me.

**Comment by tirth97** [comment]
@mariobehling I would like to work on this Project for GSOC. I have some past experience in Information Retrieval models from my previous internships.

**Comment by tirth97** [comment]
@mariobehling a doubt about the project:
The machine learning capabilities are to be implemented by importing SUSI.AI functionalities into open event or to be used to optimize searching for the open event?

**Comment by bhaveshAn** [comment]
I am interested to work on this using python packages.
@SaptakS @shubham-padia @niranjan94 Can you Please help me get the exact idea what we'll be doing in this.
For search I am well versed with Query-Server https://github.com/fossasia/query-server/commits?author=bhaveshAn
