### ISSUE TITLE
Enhance Android app generator web UI and integrate it as a Microservice with other Open Event apps (server)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#181]
The Android App Generator was develop as a stand alone version to be able to progress with the development easily. Apps can be integrated as microservices with the server. In order to achieve this, APIs are required. These need to be available through secure connections.

Another part to integrate the apps is to follow a common design approach. The Android app generator needs to follow a common UI and also the Android app itself should use a similar approach to fonts, colors and elements.

Part of this project is also the integration of features across Open Event apps while ensure that the app functions in offline mode.

**Android App Generator:** The Open Event Android project consists of two components. The App Generator is a web application that is hosted on a server and generates an event Android app from a zip with JSON and binary files or through an API. The second component we are developing in the project is a generic Android app - the output of the app generator. The mobile app can be installed on any Android device for browsing information about the event. Updates can be made automatically through API endpoint connections from an online source (e.g. server), which needs to defined in the provided event zip with the JSON files. The Android app has a standard configuration file, that sets the details of the app (e.g. color scheme, logo of event, link to JSON app data).

**Repository:** https://github.com/fossasia/open-event-android

**Communication:** Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event and our chat channel is on gitter here: https://gitter.im/fossasia/open-event-android

**Comment by ssirowa** [comment]
@mariobehling , I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.
