### ISSUE TITLE
Android App Generator: Enhance testing, implement video/screen test coverage and submissions to tracker

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#182]
The app generator has an increasing number of features and a more general approach is needed to ensure all areas of the app are covered. In this project we aim to improve the automatic app testing and develop extensive tests, preferably with automatic video and screenshot coverage of issues. We would also like to see semi-automatic issue submission for errors to the tracker implemented.

**Android App Generator:** The Open Event Android project consists of two components. The App Generator is a web application that is hosted on a server and generates an event Android app from a zip with JSON and binary files or through an API. The second component we are developing in the project is a generic Android app - the output of the app generator. The mobile app can be installed on any Android device for browsing information about the event. Updates can be made automatically through API endpoint connections from an online source (e.g. server), which needs to defined in the provided event zip with the JSON files. The Android app has a standard configuration file, that sets the details of the app (e.g. color scheme, logo of event, link to JSON app data).

**Repository:** https://github.com/fossasia/open-event-android

**Communication:** Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event and our chat channel is on gitter here: https://gitter.im/fossasia/open-event-android

**Comment by nohadrweesh** [comment]
Hi @mariobehling  I'd like to ask if this project is available for gsoc18? and if yes ,could you please tell me which functionality to start with
