### ISSUE TITLE
Open Event Web App Generator: Integrate app as microservice and implement interaction and sharing features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#184]
The Open Event Web App Generator was implemented as a stand alone solution in order to be able to focus on the development instead of integration question. The idea is to bring different services with the [Orga Server](https://github.com/fossasia/open-event-orga-server) together as microservices.

Therefore the goal of this project is to integrate the Web App Generator as a Microservice with server application and enable user interaction and data sharing with server app.

**Open Event Web App Generator:** The Open Event Web App project has two components a) an event website generator and b) the actual generated website output. The web generator application can generate event websites by getting data from event JSON files and binary media files, that are stored in a compressed zip file. You can also access the application through a REST API. Websites that are generated by the "web app generator" can be uploaded to any web location, e.g. on Github pages or any server (e.g. via ftp).

**Repository:** https://github.com/fossasia/open-event-webapp

**Communication:** Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event and our chat channel is on gitter here: https://gitter.im/fossasia/open-event-webapp

**Comment by ssirowa** [comment]
@mariobehling , I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.
