### ISSUE TITLE
API integrations as console services in Susi AI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#187]
Susi has the option to integrate console services already. The goal of this project is to outline and implement a UI flow and data integration into Susi AI.

**Comment by In-vincible** [comment]
@mariobehling I want to work on this issue, can you guide me where to start?

**Comment by sujayvenaik** [comment]
@mariobehling 
Whats basically needs to be designed in this ?
I get the idea but need to be more clear

**Comment by niccokunzmann** [comment]
@In-vincible @sujayvenaik You can reference this and ask in the susi server implementation so you can reach the team.

I **assume**: it means that you can say something like "find file xy" and it uses the console program "find". But there might be more services and the idea is to make it easy in the UI to add them.
