### ISSUE TITLE
Enhance the AAA and permissions system to be fully functional and add encryption

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#189]
A basic AAA (Authorization, Authentication, Administration) has been implemented in Susi AI. The aim of this project is to make this system fully functional and offer features that users and developers expect. These include offering all account services from sign up to account deletion to offering encrypted API access for user groups. Also implement a permissions system and offer services depending on the permission set.

**Comment by PrP-11** [comment]
@mariobehling @anshumanv I want to work on this issue and #194 for GSOC '18 but I don't know how to proceed and can you explain more about what type of encrypted API access is required , is it Nodejs token authentication or something else and which technologies we will be using for this project and how to proceed ?
