### ISSUE TITLE
Develop organizer features for Open Event server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#192]
The server has already an established flow, but a number of desired features are still lacking. These include a rating system for proposed sessions for an event organization team or custom emails to speakers and attendees. Please put together a list of desired features with description and wireframes or screenshots and implement them.

**Open Event Orga Server**: The Open Event Orga Server enables organizers to manage events from concerts to conferences and meet-ups. It offers features for events with several tracks and venues. Event managers can create invitation forms for speakers and build schedules in a drag and drop interface. The event information is stored in a database. The system provides API endpoints to fetch the data, and to modify and update it. Organizers can import and export event data in a standard compressed file format that includes the event data in JSON and binary media files like images and audio.

**Repository**: https://github.com/fossasia/open-event-orga-server

**Communication**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event. Our chat channel is on Gitter here: http://gitter.im/fossasia/open-event-orga-server

**Demo version**: 
A demo version is automatically deployed from our repositories:
* Deployment from the master branch - http://open-event.herokuapp.com
* Deployment from the development branch - http://open-event-dev.herokuapp.com
* Developer documentation gh-pages - http://dev.eventyay.com

**Comment by xSooDx** [comment]
Hi @mariobehling 

My name is Saurabh Sood and I am interested in working on this project for GSoC.
I am familiar with HTML, CSS, Javascript and Python, and am currently working on Flask for my college projects.

**Comment by rahultiwari999** [comment]
@mariobehling No deployment exists from the master branch at  http://open-event.herokuapp.com 
Please check.

**Comment by anshumanv** [comment]
@rahultiwari999 check https://open-event-api-dev.herokuapp.com/
Link in the ideas page needs to be updated.

**Comment by debasree88** [comment]
My name is Debasree and I m interested on working on this project in gsoc 2018.. my skill is android.

**Comment by harsh-jindal** [comment]
@mariobehling @anshumanv Can I work on this for GSOC 2018 ? I know javascript and have basic idea of SQL.
