### ISSUE TITLE
Implement full feature set of Organizer Android App for Open Event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#193]
The organizer app for open event offers the basic features. In order to achieve a full featured Android app a number of features need to be added. Please make a list of desired functions and implement it.

**About**: The main feature of the app is: Scan a QR code, check in attendees and keep it inline with the orga server data. 

Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event

Our chat channel is on gitter here: https://gitter.im/fossasia/open-event-orga-app

**Repository**: https://github.com/fossasia/open-event-orga-app

**Comment by iiecdev** [comment]
Hello, what  i supposed to do if i want to work on it?

**Comment by rohanagarwal94** [comment]
@mariobehling i was thinking of implementing a live feed for the open-event-android application generated from posts from equivalent Facebook event page and posts from organiser specified hashtag on twitter o drive user engagement in the app. Would love to hear your thoughts on this.

**Comment by MLPJ** [comment]
Hi @mariobehling ,
I would like to work on this project for GSOC. Am I suppose to come-up with new features for the app? Or improve the existing features?

**Comment by tirth97** [comment]
Hi, @MLPJ @mariobehling 
I was also interested in this project, is there any way I can contribute to it?

**Comment by ssirowa** [comment]
@mariobehling , I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.

**Comment by CodingWitcher** [comment]
I'm interested in this project, though I don't know where to start from...(to be honest, this is my first project on Github)... Could someone help me out here?
