### ISSUE TITLE
Enhance AAA System (Authentication, Authorization, Accounting) and add external accounts

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#194]
The Susi AI Android app accesses the Susi Server to handle data. The server currently already has a rudimentary AAA system. The aim of this project is to enhance the system by adding additional features, e.g. settings control and to connect the system with external accounts like Facebook and Google. The information shared through these accounts should be accessible by Susi AI. You need to implement functionalities that make use of the external accounts data, e.g. enable Susi to query "City of User" as defined in Facebook account and to use this information for context of conversations.

**Comment by samsruti** [comment]
@mariobehling This is one of the best features that needs to be included in the Susi Android App. I would love to work on this project for GSoC 2017.

**Comment by supreme96** [comment]
@mariobehling  Hi! Is there a thread on which discussions regarding this issue are taking place. Could you direct me to that thread.

**Comment by SpEcHiDe** [comment]
@mariobehling I would like to work on this. But, how do I start?

**Comment by nikramakrishnan** [comment]
Is this only a server side project, or does it require making changes in the Android App?

**Comment by mariobehling** [comment]
The major part is on the server side. The lesser part is on the apps. As there are many applicants for Android projects usually, the chance to get into GSoC for server side projects could be higher.

**Comment by nikramakrishnan** [comment]
@mariobehling Great! I asked because I had an intention of contributing to server-side, rather than Android development. I'm interested. Is this in the scope of GSoC '18?

**Comment by anshumanv** [comment]
@nikramakrishnan yes, it's in the scope, you can start contributing early to ease your work at the end.
Good luck! :smile:

**Comment by nikramakrishnan** [comment]
> e.g. settings control and to connect the system with external accounts

Can anyone explain what is `settings control` here exactly means?

**Comment by DNS-404** [comment]
@mariobehling @anshumanv Can I add login through Google, Facebook, GitHub etc to SUSI web application using Firebase as part of GSoC '18? How should I proceed? 😅

**Comment by anshumanv** [comment]
Idea is cool, but I don't think that's comprehensive enough for a GSoC project, in particular, we need work done on the server side for this IMO, but sure we can have auth through 3rd party services like fb, twitter, github.

**Comment by DipanshKhandelwal** [comment]
@anshumanv so firebase is not needed? And we have to use 3rd party API's right?

**Comment by psikarwal** [comment]
@DipanshKhandelwal, yes I think so. All API calls should be done by SUSI server on the behalf of user.

**Comment by prateekiiest** [comment]
Has there been any recent work on the server side till now?

**Comment by mariobehling** [comment]
@prateekiiest This is a kind of parent issue. Please help to improve this in the susi server repo.
