### ISSUE TITLE
Develop the loklak apps service into a fully featured apps site and add more apps

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#195]
The site at http://apps.loklak.org shows a number of apps as a showcase. The next goal is to develop the site into an apps site, where users can a) download apps that are shown here and get information on how to integrate them and b) where users can use the apps and test them. Furthermore the aim is to increase the number of apps on the service. Please make a list of new apps you could develop and integrate and propose a way to enhance the listing similar to existing mobile app stores.

**Comment by djmgit** [comment]
One more query, will the site continue to remain hosted on github or will get its own server. Does the scope of this project includes creating a backend using some web framework ?
