### ISSUE TITLE
Show loklak search results as auto-refreshing media wall

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#196]
The view of the search results is currently showing as a list of results. The aim of the project is to offer an additional view as a wall.

* Part of this issue is also to implement an "advanced search" page that offers an extensive list of search outputs including:
    * for specific media (images, video) 
    * options to limit searches to specific keywords, accounts, number of tweets
    * specify facets that should not show up in the search, e.g. certain accounts.
* Also implement direct URLs
* Additional features might include color options for the walls

Please investigate existing wall services, propose a list of features and implement them.

**Comment by pranayyelugam** [comment]
@mariobehling  where should we display this additional view ? and also  what do you mean by
      `Also implement direct URLs` ? Could you explain?

**Comment by Hitekshaa** [comment]
Hello, mario!!
I am Hiteksha Basiya, As i understood we should have to give advance search in new display page but i would like to ask about the  video search in advance will display link or at the same page video can be played ?

**Comment by mariobehling** [comment]
@Hitekshaa Please follow up with these kind of questions in the gitter channel, where the team can answer: https://gitter.im/loklak/loklak

**Comment by Hitekshaa** [comment]
Thank you
