### ISSUE TITLE
Develop the front end for a Susper Search Appliance

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#197]
The Susper Search Appliance uses [Yacy-Grid](https://github.com/yacy/yacy_grid_mcp). Currently only the backend exists, that can be used via terminal. The goal of this project is to offer users a simple UI for a Susper Search Appliance, that allows users to run a local distributed search engine.

## Task
It is your task to develop a web front end, the Search Appliance, for the next version of the grid search engine.

## Required Knowledge
* Understanding of search appliances
* Knowledge of html, js, front end frameworks, css, APIs, and general web technologies

## Communication

Please join us on the Susper Gitter channel (https://gitter.im/fossasia/susper.com).

There is a susper repositories for the search portal https://github.com/fossasia/susper.com

Please star the repository, so we can know about your interest and fill in the [pre-application form](http://fossasia.org/apply-students).

## Background Info
A good way to start is to read up on Open Source and proprietary search appliances such as the discontinued Google Search Appliance. A good starting point is the Wikipedia: https://en.wikipedia.org/wiki/Google_Search_Appliance

For background info on the first version of the Yacy Search Appliance please have a look at the following link: http://yacy.net/en/Applications.html

**Search Appliance:**
Topic-Oriented Search and Search Engine for Projects

You can operate as a single search appliance without networking with other peers. Such a search instance can be used for:
* Search for projects - a combination of wikis, forums and websites
* Topic-oriented search engine - combine a search for several web pages from different domains into a single search portal.
* Companies can host their own search engine in order to help guard company secrets (a company may give away secrets with the search words employees submit to a search portal).
* The search engine helps to preserve your anonymity when searching

**Your own search portal!**
If you run a YaCy peer, you have your own search engine. You can use it either to provide search functionality for your own search portal, or you can join a community of search engine peers to share your web index with the web index of other YaCy peer owners. If you search with YaCy your search requests are anonymous because they go to your computer and not to a central search portal server. No central server can log your searches.

**Integration of a search window in your own web pages**
YaCy provides simple code snippets to support the integration of YaCy search into your own web pages. There is also a search widget (pops up on your web pages if you like that) and demonstration snippets are provided by the YaCy administration interface. You only need to copy-paste the code into your pages.

**Privacy and Security**
Your private search requests are never stored, monitored or evaluated for commercial purposes.
If you are searching for terms related to product development and innovation, you can potentially give away information about your company activities. To maintain your business secrets, you need your own search engine (which can easily be created with YaCy).

## Project Repository
First steps are to start the work in your own repository and show us some initial ideas, issues and mockups.

**Comment by pranayyelugam** [comment]
@mariobehling There's already a frontend at [here](http://susper.com) . Do we have build a new UI or develop the existing one.

**Comment by ShishirBondre** [comment]
@mariobehling Are talking about the fornt some which  what related to google search UI or we have to redsign a new one

**Comment by amarlearning** [comment]
@mariobehling Susper already got some front-end. Do you think that should be redesigned ?

**Comment by ShishirBondre** [comment]
@mariobehling  Yes i think redesign must take place because more features from ui can be predicted and the user can more accurately search for a given query

**Comment by mariobehling** [comment]
The Susper Search Appliance will have the same features as the Google Search Appliance, that is coming to its end of life. The new Yacy framework to offer additional services is nearly finished. So, we need someone who understands the features and UI of the Google product.

**Comment by katsik** [comment]
I would start by making the live search smoother, or providing some auto-completion feature. Thoughts?

**Comment by mariobehling** [comment]
@katsik Please search online about the `Google Search Appliance`. This will help you to understand what are the requirements for this project. Thanks!

**Comment by JPRMarketing** [comment]
We have a lot of our Google Search Appliance customers switching to Yippy Search Appliance.  It is the same technology as IBM Watson http://www.yippyinc.com/google-search-appliance-replacement

**Comment by Akarsh-TS** [comment]
I have the exact knowledge of how the Google Search Appliance works and the system architecture of Google search, So if I can get assistance I would love to work on this project

**Comment by mariobehling** [comment]
@Akarsh-TS Ok, great! First steps are to start the work in your own repository and show us some initial ideas, issues and mockups.

**Comment by 94151** [comment]
@mariobehling I am good to design front end. And also I read about search appliance. if i would get assistance I will definitely work on this.

**Comment by mariobehling** [comment]
Hope to see the applications of all of you. You can also base your application on existing issues. Basically we need developers who want to help getting the app running reliably. So, there is a lot to do to make this happen. So, good luck with your application!

**Comment by akalanka95** [comment]
We want to build the Susper Search Appliance with the performance like Google UI and the features are provided by the new Yacy framework.That's it.

**Comment by tushar-nitave** [comment]
@mariobehling I have checked front end and I think a lot of finishing needs to be done. I will be able to design the front end so that along with smoother performance it will be aesthetically appealing to users.
