### ISSUE TITLE
Improve existing Susi AI Bots and create new ones

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#198]
There are number of Susi AI Bots. Some require the command line to start. Generally the bots are in an early prototype stage. Please help to develop the bots into fully functional bot applications. Make a list of the bots and propose the addition of bots for other services, e.g. Zulip. Develop the bots and showcase them running on different media networks.

**Comment by roydipayan003** [comment]
Hey @mariobehling can i work on this project in GSoC?

**Comment by Abhi2424shek** [comment]
@roydipayan003 sure you can.

**Comment by roydipayan003** [comment]
Hey abishek nice to hear back. I am new to the open source society and i
would like to contribute to the Susi AI project of fossasia group.
Can you help me to get started?

**Comment by Abhi2424shek** [comment]
Sure @roydipaayan003 pls read the readme  in the susi server project, there are some bots present already, pls see through the susi bot repositories. Thankyou.

**Comment by y73isc00l** [comment]
Hey I would like to work on this project for GSOC 2017.
Can somebody tell me the link to prerequisites for project?

**Comment by Abhi2424shek** [comment]
Good knowledge of susi, @y73isc00l for the list of bots needed pls see, https://github.com/fossasia/susi_slackbot/issues/1

@mariobehling wouldn't it be best to post that list here?

**Comment by sujayvenaik** [comment]
I have previously worked on AI Chat bots and its development. And have a fair idea.
We can certainly integrate the bot at various spaces such as Facebook, Slack and even Skype.
The product i worked on was configured to Fb messesnger making use of web hooks.
Even made use of Nginx Server for load balancing and other purposes.

Thus, i am interested to work on this.
Skype can also be a platform.
As, i explored it certainly also seems possible on WeChat.
Further how can i start on this ? We have the interaction beta-code or we have to build it from scratch the interaction messages as well ?

**Comment by Abhi2424shek** [comment]
We need:
Viber
Google Talk/Hangout and
Gitter
bots @sujayvenaik. You will have to make a new repo under your github account make the app working and then it will be adopted to fossasia.

**Comment by sujayvenaik** [comment]
@Abhi2424shek 
So basically i have to start working now or first get the proposal accepted and then start ?

**Comment by Abhi2424shek** [comment]
@princu7 how is the procedure?

**Comment by Princu7** [comment]
@Abhi2424shek Not really sure @mariobehling can explain this better

**Comment by y73isc00l** [comment]
I had posted this comment on other open issue so I am reposting it.      @mariobehling @Orbiter I have already implemented such a system in an app which I had made as part of a college competition.The app's backend is in flask and heavily relies on python library nltk,the data of each user conversation in stored in firebase and more the user interacts with the bot in different categories,the more the bot learns questions and answers.If you would like I would like to send the apk of the app created.Please tell the channel through which I can send.I would like to merge the capabilities of both SUSI and my app to create a chatbot that can be created without writing any code.
The link to code's backend repository https://github.com/y73isc00l/botguise

**Comment by y73isc00l** [comment]
The link to the apps apk is https://drive.google.com/folderview?id=0B8m3ShszCn_kQXFzWU04QmxLRk0

**Comment by y73isc00l** [comment]
The project idea is similar to that is Susi AI bot which aims to work on building an interface from which people can easily build their own chatbot.Thus I would like to work on this project as part of my gsoc project.

**Comment by y73isc00l** [comment]
Can somebody send link to chat channels

**Comment by karanpathak** [comment]
Hey @mariobehling , I would like to work on improving existing Susi AI bots in GSOC2017. How can I get started?

**Comment by mariobehling** [comment]
@karanpathak Please check out the bots in the FOSSASIA repos and start contributing to understand the project better. Thanks!

**Comment by shrey-jain** [comment]
Hey, I am new to the open source society and i
would like to contribute to the Susi AI project of fossasia group.
Can you help me to get started?

**Comment by sujayvenaik** [comment]
@Abhi2424shek 
Do i have to mail my proposal elsewhere as well other than uploading on the Gsoc dashboard. ?

**Comment by thelastpolaris** [comment]
Though I found this project was done during GSoC 2017, is still ok to work on new bots for GSoC 2018?

**Comment by mariobehling** [comment]
Yes, the existing bots are not finished. A lot of works needs to be done and missing features implemented.

**Comment by Priya997** [comment]
Hello sir, am interested in working on this project during gsoc2018. Please guide me through the procedure.

**Comment by djmgit** [comment]
@Priya997 Hi, its great that you are interested in working on this project. Please go through susi_server code and its APIs. Also check out the already existing bots. Try to fix issues as this will help you in understanding the code better. Best of luck :)

**Comment by ssirowa** [comment]
@mariobehling  @djmgit  I would like to work on this during GSoC. Can you help me in getting started?

**Comment by rishiraj824** [comment]
@ssirowa Start cloning the projects and get familiar with the APIs. Participate in the issue trackers and contribute to the projects.

**Comment by adi020897** [comment]
I would like to work on this in GSoC how should I go about it?

**Comment by TheDreamSaver** [comment]
Hi, I would like to work on the SUSI Alexa skill for GSoC. How can I start with it?

**Comment by Manveer695** [comment]
@Ashish Jha Hi, you can clone the repo susi_alexa_skill. The skill was made
using aws lambda function. You can check the code and documentation from
the repo. Best of luck.

**Comment by Manveer695** [comment]
Also, I have tried to explain it through this blog post -
https://blog.fossasia.org/integration-of-susi-ai-to-alexa/ . It can prove
to be of great help. Cheers!

**Comment by TheDreamSaver** [comment]
I referred to the code but it is using Amazon Literal Slot which is no longer supported in different English locales.
So now we cannot send direct queries which we receive as the user input. Rather we have to map all sorts of different intents to the different use cases for the bot. 
So is there any list of use cases one may use the susi alexa skill for?

**Comment by SudhanvaMG** [comment]
Hello, I would like to work on this .
Do we need to select the existing repos on these bot (like fb and twitter bots ) and work on improving them ?
