### ISSUE TITLE
Develop the next generation Knitting Editor

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#199]
The knitting editor is an application that can give out a format for knitting machines as well as instructions for hand knitting. Tis project is about developing the next generation Knitting Editor with additionally required features. The areas of the project are: a) hand knitting, b) the editor and c) hand knitting.

Please make a list of features and implement them. Document your work and include pictures of test runs.

A number or relevant feature request below.

* Editor: insert instructions ayab next-gen must have
* Editor: remove instructions ayab next-gen must have
* Find out more about knitting in progress wontfix
* handknit: create example to knit
* handknit: use diffs for humans
* handknit: say where to add and remove meshes
* handknit: show repetitions
* handknit: include basic patterns ayab next-gen
* Create Tutorial Videos must have ready

Issues: https://github.com/fossasia/kniteditor/issues

**Comment by souravsingh** [comment]
@mariobehling I am interested in working on the project.

**Comment by niccokunzmann** [comment]
@souravsingh If you have any questions about the editor, you can also ask me @niccokunzmann or open an issue in the editor. I was one of the developers of the kniteditor in last years GSoC.

If you like, you can work on an issue and I can guide you until you finished it so you can peak through how it works.
Any way, is there anything I can tell you?

**Comment by subhahu123** [comment]
@mariobehling  something like this
![screenshot from 2019-01-05 23-31-49](https://user-images.githubusercontent.com/34541684/50727551-78942800-1142-11e9-92a6-88c51e9dfd8a.png)
