### ISSUE TITLE
fix build warning

### ISSUE THREAD

**Issue by eMBee** [fossasia/labs.fossasia.org#20]
every time changes are pushed, the following warning is sent:

The page build completed successfully, but returned the following warning:                        
                                                                                                  
GitHub Pages recently underwent some improvements                                                 
(https://github.com/blog/1715-faster-more-awesome-github-pages) to make your site faster and more 
awesome, but we've noticed that labs.fossasia.org isn't properly configured to take advantage of  
these new features. While your site will continue to work just fine, updating your domain's       
configuration offers some additional speed and performance benefits. Instructions on configuring  
a subdomain for use with GitHub Pages can be found at                                             
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages#subdomains, and of  
course, you can always get in touch with a human at support@github.com. For the more technical    
minded folks who want to skip the help docs: your site's a subdomain, but is set up as an A       
record. It should be a CNAME to `your-username.github.io`.                                        
                                                                                                  
For information on troubleshooting Jekyll see:                                                    
                                                                                                  
  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

**Comment by ty221** [comment]
To fix this issue, access to domain management is necessary. I think only @mariobehling fix this bug. 

What should be done?

1. Current FOSSASIA Labs A record (now it is [A] labs.fossasia.org -> 192.30.252.153) should be changed to CNAME record pointing to fossasia.github.io ([CNAME] labs.fossasia.org -> fossasia.github.io)

**Comment by ty221** [comment]
DNS Error Fixed.
