### ISSUE TITLE
Update Phimpme Image App with latest Android features and enable social media connections

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#200]
The [Phimpme app](https://github.com/fossasia/phimpme-android) was developed already for several years. The next goal in the development is to update the app using latest Android standards and get it ready for app stores and Fdroid. Please also make a list of your feature ideas and outline how to implement them. 

Additional features to be implemented are for example:
* Use standard upload APIs of loklak server, Wordpress, Drupal and Typo3
* Enable social media features
* Connecting accounts
* Adding filters
* Share with friends

**Phimp.me Android App:** Phimp.me is a Photo App for Android that aims to replace proprietary photo applications. It offers of features such as taking photos, adding filters, editing images and uploading them to social networks.

**Repository:** https://github.com/fossasia/phimpme-android/

**Communication:** Please join our chat channel on Slack: http://fossasia.slack.com/messages/phimpme/. You need to invite yourself first here: http://fossasia-slack.herokuapp.com/

**Comment by vaibhavsingh97** [comment]
@mariobehling I am interested in contributing in Phimpme app. Kindly guide me how can i start contributing me?

**Comment by Subhankar29** [comment]
@mariobehling Hello, I am contributing to the phimpme for a while. I am interested and curious working for GSOC this fall. Till now I don't know who all are the mentors? The GSOC page doesn't have a lot of information.

**Comment by rohanagarwal94** [comment]
@mariobehling I have been contributing in Phimpme and open-event-android for a while now. Would love to make this app the go-to-camera app for everybody. I was thinking of implementing a GIF creator in this app which could be shared across the social media platforms by the users. Would love to hear your thoughts on it :) .

**Comment by mariobehling** [comment]
@rohanagarwal94 We could discuss all kinds of features, but right now some basics do not work and we also need a server component for people to login. Getting the basics right is our first priority and if we could have the basic features of Instagram in an Open Source app, that would be a big achievement. Please focus on that first before going too much into detail. Cheers.

**Comment by rohanagarwal94** [comment]
@mariobehling thank you for your inputs. Will keep that in mind.

**Comment by Subhankar29** [comment]
@mariobehling so are you looking forward to implementing sharing feature like Instagram timeline?

**Comment by YoyoAnandra** [comment]
Sir, I want to participate in GSOC 2018 is this project available GSOC 2018 , I would like to work on this Project.

**Comment by Ananthusubramanian** [comment]
@mariobehling Sir, is this project for gsoc 2018 ?, if so can I work on this project.

**Comment by ssirowa** [comment]
@mariobehling Sir, I would like to take up this project for GSoC 2018. Can you please help me get started?
