### ISSUE TITLE
Add more features to Knitting Pattern Library

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#201]
**About Knitting Pattern Library**

The knitting pattern library enables tailors, artisans and home knitters to use a common pattern for knitting machines and hand made knits.

**Task**
The knitting patterns covered are still relatively simple. The goal of the project is now to add more advanced patterns and forms. Please make a list of possible features and propose a plan for implementation.

**Links**
- [Github Repository](https://github.com/fossasia/knittingpattern)
- [Chat Channel](https://gitter.im/fossasia/knitapps)

**Comment by Asutosh989** [comment]
Hi @mariobehling, I am interested to work on this. I have cloned the repo but confused as how to include new patterns. Could you please guide me?
