### ISSUE TITLE
Ideas Page not showing all issues tagges "GSoC"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#203]
The page http://labs.fossasia.org/ideas.html uses the GitHub API and gets all issues with the label "GSoC". unfortunately not all issues are showing up.

Please help to get all GSoC issues showing up on the page.

**Comment by meets2tarun** [comment]
I just match and saw that all the GSoC ideas are listed there .

**Comment by Abhi2424shek** [comment]
You solved it!
![screenshot_2017-02-10-21-37-34-611_com android chrome](https://cloud.githubusercontent.com/assets/8947010/22833936/98baad3e-efd9-11e6-85cc-eab1b29cc2e7.png)
Close it.
