### ISSUE TITLE
Create a Jekyll compatible design implementation of the FOSSASIA style and add it to our Knitting site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#204]
We often need to create a simple mini-site. We want to be able to create a md file with markup and add a Jekyll style. One example is the Knitting lab site. It does not use the FOSSASIA style yet. 

Please create a Jekyll implementation of the FOSSASIA design and add it to http://knitting.fossasia.org/

The repository: https://github.com/fossasia/knitting.fossasia.org

Relevant to: https://github.com/fossasia/knitting.fossasia.org/issues/11

**Comment by championshuttler** [comment]
Hello I am interested in doing this. Can you guide me.

**Comment by ravikp7** [comment]
Do you mean a Jekyll theme ?

**Comment by aviaryan** [comment]
@championshuttler @ravikp7 
In this issue, we have to update the knitting.fossasia.org site to follow same design as other FOSSASIA websites. Also the design should properly use Jekyll templates for its implementation and should not be hardcoded in each HTML page.

Examples of FOSSASIA design :- 
https://github.com/fossasia/fossasia.org
https://github.com/fossasia/labs.fossasia.org

**Comment by championshuttler** [comment]
@aviaryan and @ravikp7 Please can you  give me some time to study about the jekyll theme properly ? I am really interested in this project but i need guidance because i am new to open source and want to contribute

**Comment by Abhi2424shek** [comment]
@championshuttler find info about Jekyll here: https://jekyllrb.com/docs/home/ like you include files in PHP you could do it with Jekyll and serve it. The labs current you uae static content which is not good instead we need to use Jekyll which supports data imports as well.

**Comment by zamhaq** [comment]
Can I still try this ? Is the issue still not resolved ?

**Comment by abishekvashok** [comment]
@zamhaq you are free to do so :)

**Comment by zamhaq** [comment]
@abishekvashok Is there any timeline before which I need to submit the PR?
and should the design be similar to the main FOSSASIA site?

**Comment by abishekvashok** [comment]
@zamhaq 

> @abishekvashok Is there any timeline before which I need to submit the PR?

No timelines in open source, you are free to take all the time in the world provided you do it and let us know that you are doing it

>  should the design be similar to the main FOSSASIA site?

Yes

**Comment by zamhaq** [comment]
@abishekvashok where do I contact you when I need help, this thread itself?

**Comment by abishekvashok** [comment]
@zamhaq pls keep all contacts open. I am just a developer like you.

Also pls read our best practises; http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/
That will get you started.

**Comment by Subhash-Saurabh** [comment]
I am really interested in doing this and I have bit of knowledge of jekyll . Can I do this??

**Comment by niccokunzmann** [comment]
Sure, if you like, please go ahead.

**Comment by shubham-sr** [comment]
Is this issue still open @mariobehling ?

**Comment by mariobehling** [comment]
Yes. Still open.
