### ISSUE TITLE
Enhance the firmware for PSLab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#205]
For the PSLab project we need a completely Open firmware and hardware schematics. There are already [schematics in pdf format](https://github.com/fossasia/pslab/raw/development/docs/pslab-schematics.pdf). In order to progress to the next level of development these files need to be implemented in code and added to the repository.

Please create a list of features for the firmware and sample implementations for tests. Add your schematics to the PSLab repo and create a fully functional hardware, that can be freely used by others.

**PSLab** is a new addition to FOSSASIA Science Lab. This tiny pocket lab provides an array of necessary equipments for doing science and engineering experiments. It can function like an oscilloscope, waveform generator, frequency counter, programmable voltage and current source and also as a data logger. The control and measurement functions are written in Python programming language. Pyqtgraph is used for plotting library. A variety of experiments can be performed using GUI applications written in python. PSLab is interfaced and powered by USB port of the computer.

**Repository:** https://github.com/fossasia/pslab

**Website:** http://pslab.fossasia.org

**Comment by siebenHeaven** [comment]
Hi @mariobehling  ,I am interested in applying for GSoC with this idea.I would like to know more about the issue - will contributing to it need a PSLab hardware on my side? Also what exactly will implementing the firmware involve?
