### ISSUE TITLE
Develop a short message publisher with numerous attachments for loklak

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#207]
The first version of the loklak tweet message publisher offered the ability to post messages to loklak and twitter. The feature of the prototype in the [loklak webclient](https://github.com/fossasia/loklak_webclient) was that it could post maps to loklak as an attachment and it converted the map attachment into an image for twitter.

The next step is to develop an app based on this prototype as an Angular2 application as follows:
* A tweet like app that uses the same number of tweet characters as twitter and posts messages to loklak
* App makes use of the loklak accounting system
* Part of that project is to enhance the loklak server accounting system and APIs to make it fully usable for the app user
* The user should be able to add a twitter account to the loklak server account (all account data should be stored on loklak server)
* The app should work as a stand alone version and it should be possible to plug it into the service of loklak.net (loklak_search)
* As data is not stored on the app, but on the loklak server, there is no need for server side scripts and it should be possible to run the app as a Github pages service.
* The feature of the app is that it can add other attachments including
   * Add a map as an attachment and show a map in the tweet (generate this map as a picture when cross-posting to twitter itself) - This feature exists already in the web client and loklak server
  * Add text/code as an attachment and generate it as an image when cross-posting to twitter itself 
  * Propose more suitable attachments

**Comment by mohsini172** [comment]
I want to contribute in this project where to start

**Comment by SarishiNoHara** [comment]
HI, @mariobehling this project is great! I've currently write a draft proposal for this project. It will be great if you can review and leave some comments to help me improve the proposal.
Here is the link:
[](https://docs.google.com/document/d/1uIq8HmToQwELz_a6F_R1Fqyuo-_ggnymV5F52LJ348c/edit?usp=sharing)

**Comment by harshitkhandelwal-4414802715** [comment]
hi....I want to contribute to this project as a Gsoc project... so pls tell me where to start.
