### ISSUE TITLE
Change the loklak wok Android into two apps a) as an independent library and b) into a loklak app with search and tweet features

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#208]
The loklak wok Android app, currently shows the list of tweets getting collected in a beautiful way. 

The next goal is to develop the app in two ways:
a) The data collection of the app should be an independent library
  * Developers should be able to add the library to other apps (First steps to do this have been taken)
  * The current app is using Processing to show the list of tweets. This choice was good to get the app running quickly, however it increases the footprint of the app and complicates the development of the app. Therefore, please implement the features using technologies with a smaller footprint
b) The full featured `loklak app` should enable users to search loklak and to tweet to the loklak server (and cross-post to twitter using the loklak server)
  * This app should make use of the loklak accounts
  * It should also enable attachments
  * The app should also still be able to collect tweets using the independent loklak wok library and portray them

**Comment by Rishabhk07** [comment]
Hi @mariobehling how to approach tweeting to loklak server, by authenticating twitter user or something else ?

**Comment by luvattri3** [comment]
@mariobehling sir i a
m new to this app! can you can you tell me what are we trying to solve the issues here

**Comment by Nishchay-sopho** [comment]
@mariobehling I would like on this idea for GSOC 2018.

**Comment by ssirowa** [comment]
@mariobehling , I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.
