### ISSUE TITLE
Documentation Apps Project

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#210]
At FOSSASIA we are using a number of documentation tools and there are a few different approaches. The goal of this project is to develop and implement a number of tools, that help us to build dev websites fully automatically from GitHub repositories that provide full features including search. In this project we aim for two technology stacks to be implemented:

1. Use GitHub pages with Jekyll and Javascript.
2. Generate static sites in GitHub pages using Sphinx.

A first prototype implementation can be seen on http://dev.loklak.org, which is generated from the docs files in the loklak repository at https://github.com/loklak/loklak_server/.

**Comment by harshitcodes** [comment]
Hi @mariobehling,
The project looks interesting and since I have some experience using GitHub pages and Jekyll, I believe I can get this done using some guidance.
If you can give some pointers on how shall I proceed with the first step in terms of a sample project or exploring how sphinx works.

Thanks!

**Comment by Abhi2424shek** [comment]
@harshitcodes it's about building a tool that will generate a site from the docs provided in the repository. You may use either of the two approaches to do so. Create a repo on your account locally and see make it work, then we can import it to fossasia solving the issue. It would be great if you could package it to be called from Travis.

**Comment by harshitcodes** [comment]
@Abhi2424shek thanks!
I'll just get on with this right away and let you know once it is done.

**Comment by Abhi2424shek** [comment]
Sure @harshitcodes

**Comment by harshitcodes** [comment]
@Abhi2424shek 

I tried generating the HTML pages for the docs of a repository using sphinx.
If you can take a look and let me know if this is what you are looking for. I have just added a single line for testing as of now.

My repository: [Deep Learning Neural Net](https://github.com/harshitcodes/Udacity_DLND_first_neural_network)

Published site: [http://harshit-tyagi.in/Udacity_DLND_first_neural_network/](http://harshit-tyagi.in/Udacity_DLND_first_neural_network/#)

**Comment by Abhi2424shek** [comment]
@harshitcodes what the issues states to be wanting is some script which can be called via Travis or other CIs that can build docs and push it to gh-pages. You can build the docs either with the Sphinx method or the method we use in loklak.

**Comment by pri22296** [comment]
Hi @Abhi2424shek 
I have experience with generating documentation using sphinx. I think I can get this project done with some help. If you could just guide me on where to proceed so that i can make myself more familiar to the technology which I would need to use for this project.
Thanks

**Comment by mariobehling** [comment]
@pri22296 Please have a look at the loklak project. We are already generating documentation here: https://github.com/loklak/loklak_server/tree/gh-pages by using Travis and a script. As a next step, could you help to implement the same for SUSI AI? Check out this issue here, please https://github.com/fossasia/susi_server/issues/70

**Comment by Abhi2424shek** [comment]
@mariobehling why don't we build something like a ruby gem or something similar that can be called from Travis or other CI so that, you can generate the docs and push them back with the help of a config file, this would indeed save our time  of including the files for each repo and is more a radical solution, wht is your opinion?

**Comment by pri22296** [comment]
@mariobehling I have built the documentation for [susi-server](https://github.com/fossasia/susi_server) using sphinx. I will now be adding a script similar to (https://github.com/loklak/loklak_server/blob/development/.utility/push-docs-to-gh-pages.sh) to push the docs to github pages and then file a PR.

Built Documentation: (http://susi-server.readthedocs.io/en/latest/index.html)

**Comment by sch00lb0y** [comment]
Is this specific for fossasia or can be used by any organization

**Comment by sch00lb0y** [comment]
@mariobehling  github bot which generates doc to the integrated repository . does this will fulfill your requirements !!
Thanks Balaji

**Comment by aviaryan** [comment]
> @Abhi2424shek: why don't we build something like a ruby gem or something similar that can be called from Travis or other CI so that

Yes we will have to build something like that. We need to be very careful when choosing a language for this project. A language with good file handling, string manipulation (with regex) and decent system capabilities should be the way to go IMHO. Views???

> @sch00lb0y: Is this specific for fossasia or can be used by any organization

I think we may initially start with a fossasia based theme but ideally we should like to make it customizable so that it can be used by any organization.

**Comment by sch00lb0y** [comment]
@aviaryan i think go-lang will be suffice to handle multiple repository.
could you explain me how to start ? or shall i create my own repository and work on it ??

**Comment by aviaryan** [comment]
@sch00lb0y I was also thinking the same. Plus, with golang we would be able to enjoy unmatched build speeds. And it's library is rich enough to incorporate our other needs such as String handling, file IO and system.

> could you explain me how to start ? or shall i create my own repository and work on it ??

I am not sure. For now, I guess the best you can do is work on a proposal and submit it (as a draft). Potential mentors would review it and provide you with feedback. You can then continue to improve the proposal as per their feedback.

**Comment by sch00lb0y** [comment]
@mariobehling @aviaryan 
https://docs.google.com/document/d/1VxAm4m-eSNFO5bi3bR8qJBAxNMKiOx20tTgyBLeCC6A/edit please review my draft and tell me is there any thing you want to add
Thanks!!
Balaji

**Comment by aviaryan** [comment]
@sch00lb0y Just saw your draft. I see that you are specifying Golang, Redis and Mongodb as technologies. Can you please be clear on why these are needed (do this in the proposal). 
Also as a rule, always try to provide as much detail as possible in the proposal.

**Comment by sch00lb0y** [comment]
Thanks @aviaryan for your review. i have drafted once again according to your suggestion. this time i have added process diagram also pls check and let me know 
https://docs.google.com/document/d/1VxAm4m-eSNFO5bi3bR8qJBAxNMKiOx20tTgyBLeCC6A/edit#

**Comment by aviaryan** [comment]
@sch00lb0y Hi. I just had a quick look at your doc.. One thing I feel that is missing is that you are missing how the documentation will be generated. That is, what is the input what will go into the system and what will come out. Another way to understand this is, suppose your system has been built. How will I be able to use it to generate docs for my project? What extra text apart from project's codebase will I have to write for generating docs? It can't generate the docs automatically, right?

**Comment by sch00lb0y** [comment]
@aviaryan  yeah,absolutely. you have to define dockie.yaml file like travis.yaml file in the repo which specify the path of the doc, then we'll be cloning the repo and generate doc using jekyll by making use of the path specified in the yaml file, at last dockie will push the generated html to gh-pages. i hope this process flow solves your problem if you found any problem please ask me.
Thanks!

**Comment by aviaryan** [comment]
@sch00lb0y Ok. Please mention it clearly in your proposal so that it will become clear for everyone else. Cheers 👍

**Comment by sch00lb0y** [comment]
@aviaryan Thanks

**Comment by sk9331657** [comment]
@mariobehling  Is this Project Open for improvements?? What other improvements needs to be implemented??

**Comment by anshumanv** [comment]
@sk9331657 the project is here - https://github.com/fossasia/yaydoc you can check it out yourself and propose improvements that you think can be implemented.

**Comment by sk9331657** [comment]
@anshumanv I want to ask about particular improvements to be made as it is mentioned in issues.
