### ISSUE TITLE
Site not working!

### ISSUE THREAD

**Issue by uttu357** [fossasia/labs.fossasia.org#211]
Maybe there is some change in Cloudfare security policies due to which CNAME are not being allowed.
![screenshot from 2017-02-24 03 36 19](https://cloud.githubusercontent.com/assets/15570642/23281232/7f1e7446-fa42-11e6-83f3-a592c916f2b2.png)

**Comment by mariobehling** [comment]
Strange. It is working here for me. Any ideas?

**Comment by jig08** [comment]
Working for me as well.

**Comment by aviaryan** [comment]
Cloudflare faced a [major incident](https://techcrunch.com/2017/02/23/major-cloudflare-bug-leaked-sensitive-data-from-customers-websites/) recently so maybe that was a temporary outage because of that. @uttu357

**Comment by uttu357** [comment]
yeah working now.. closing this.. :)
