### ISSUE TITLE
Create an Open Event Format file of Mozilla event as a showcase

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#213]
The last Mozilla corporation event was held in Hawai https://hawaiiallhands2016.sched.com/

Please convert this to the last version of the Open Event format (based on the API). Ensure you support the last version of the API of the server.

Please follow up on details of this project here: https://github.com/fossasia/open-event/issues/131

**Comment by muarachmann** [comment]
@mariobehling i am an open source enthusiast and contribute to Susi android app, and open event. I am interested in working on this. With guides of course thanks.
