### ISSUE TITLE
Compare Mycroft with SUSI AI and evaluate skills import options

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#215]
Mycroft (https://mycroft.ai) is doing a great job to tell people about the project. Lots of people know it. Please compare it with SUSI AI and Mycroft. There are a number of skills (https://github.com/MycroftAI/mycroft-skills). Can we import them to SUSI? This issue is related to both the Android client and the SUSI server.

Please follow up in the dedicated issue here: https://github.com/fossasia/susi_android/issues/566

**Comment by souravsingh** [comment]
@mariobehling I would be interested in working on this.

**Comment by sayak119** [comment]
@mariobehling can I do this as a part of my Codeheat blog post along with their comparison with Alexa as I have worked with it.

**Comment by sayak119** [comment]
@mariobehling please review https://docs.google.com/document/d/1zvXwiwMozf1JE8Rng5r03YMfZymsY4lNwEmRR6CETY0/edit?usp=sharing
