### ISSUE TITLE
Develop a loklak ticker for desktops and servers

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#217]
The loklak Android app shows all kinds of tweets that are harvested by the app. This is a nice idea - to see random tweets and other social messages that are collected by a personal loklak service.

Your task is to develop one of the following components:
1. A loklak desktop message ticker using the desktop version (a) a simple web ticker and (b) a ticker showing messages on a world map
2. A loklak server web ticker using the server version a) a simple web ticker and (b) a ticker showing messages on a world map

**Comment by rijuldhir** [comment]
I am new to FOSSASIA. Can I try this ?

**Comment by jig08** [comment]
@rijuldhir Sure !

**Comment by isaeef** [comment]
is this issue still open ???

**Comment by 0x48piraj** [comment]
**_Status of this issue ?_**
Ping @jigyasa-grover @mariobehling
