### ISSUE TITLE
Build an analytics tool for SUSI.AI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#223]
Metrics for conversations are different to search. An examples of a tool is botimize.io. Please propose and build an analytics tool.

**Comment by Harshdeep1996** [comment]
Hi @mariobehling , I would like to contribute to this issue. What is the right way to go about it?

**Comment by mariobehling** [comment]
@Harshdeep1996 Please go through [this app](http://www.botimize.io/) and propose how to integrate something similar in SUSI.AI.

**Comment by Harshdeep1996** [comment]
Right, I will go through it, and update here once I have an idea of how to go about it.

**Comment by riktimmondal** [comment]
I will like on work on it.But the link of the app you told is see is not working.How to approach it?

**Comment by anshumanv** [comment]
@Harshdeep1996 here you go https://github.com/fossasia/susi_server

**Comment by anshumanv** [comment]
Started working on a basic prototype, will post soon. :+1:

**Comment by donjin-master** [comment]
hi mariobehling , i want to contribute in this issue can we add a voice command to make it more practical i am just thinking about it

**Comment by vipuldcoder** [comment]
Hi, I love to contribute, how to get started

**Comment by Donyme** [comment]
What dataset will this tool essentially analyse?Can you please be specific!

**Comment by anshumanv** [comment]
@Donyme probably we can cache the api calls made to the server and depending upon those data, we can build a front-end to display the statistics.

**Comment by zaynkorai** [comment]
I have read this issue and done with analysis of [getbotimize](https://dashboard.getbotimize.com/summary-overview)
- There are no further details how to get start with it. Like
  - Technology Stack?
  - It will be directly connected to susi_server Api's or chat.susi.ai?
  - Repo of this project

few more details related to this issue will be really helpful to get started with it.
like design of the tool, would it be dito of botimize or many things needs to be changed. 

Also suggestions or furthers details you think, I need to know before starting this, will be really helpful.

**Comment by anshumanv** [comment]
Hey @zaynkorai, I can add a few points. :smile: 
* Have you checked out the SUSI Apps family? All of them are React front-end so mostly to keep things aligned we can have a React front-end to display the statistics/analytics to the users.
* I should be connected to the susi_server where we would be caching the api calls to perform the analysis upon, I don't think chat.susi.ai will come in the picture.
* We can start a personal repo for now and once the basic environment is setup we can import it in the organisation.
* For now let's keep it aligned with the botimize design, we can iterate over design again to make changes as required or as we get suggestions.

**Comment by Orbiter** [comment]
Please consider to use grafana since I already implemented a grafana data endpoint in the package ai.susi.server.api.monitor. Have a look into the class MonitorQueryService which responds to time-series data queries. That class currently responds with random data to show that the data endpoint is already working.

All you need is to replace the random data with i.e. logging information. There can be also several classes of logging information; those classes must be provided with MonitorSearchService.

To use that data endpoint Grafana must use the simple json data endpoint from https://grafana.com/plugins/grafana-simple-json-datasource

**Comment by Orbiter** [comment]
A second option could be maybe https://nasa.github.io/openmct/

**Comment by Orbiter** [comment]
Ok, to get Susi's memories (the chat logs) just get the following object:
DAO.susi.getMemories()

Then you have a SusiMemory object which provides the getAllMemories() method.
It's not clear what to do with that now, but thats the starting point to generate a history for timeseries entries which are needed for the grafana simplejson API.

**Comment by zaynkorai** [comment]
Getting hard time with grafana

**Comment by stealthanthrax** [comment]
@mariobehling @anshumanv @Orbiter ,are we planning to create just a dashboard and use a third party API like chartJS or build that too??

**Comment by AnupKumarPanwar** [comment]
@mariobehling I've gone through the [](http://www.botimize.io/) demo. I would love to work on this analytical tool for SUSI. More specifically on the server side.

**Comment by DipanshKhandelwal** [comment]
@mariobehling @anshumanv Is android app for analytics for SUSI.AI a good idea ?

**Comment by anshumanv** [comment]
Certainly, we can have an android app for this, could help track analytics on-the-go.

**Comment by DipanshKhandelwal** [comment]
@Orbiter What are your views on it?

**Comment by Troy96** [comment]
Greetings!

This project seems interesting to me. Please  guide me as to how should I approach the problem.

**Comment by Jitender46559** [comment]
Hii @mariobehling can i contribute in this project.
