### ISSUE TITLE
Add additional projects to project page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#224]
The project area is at http://labs.fossasia.org/#projects

Please add the following projects:

* yaydoc
GitHub: https://github.com/fossasia/yaydoc
URL: http://yaydoc.fossasia.org
Mailinglist: https://groups.google.com/forum/#!forum/yaydoc
Chat: https://gitter.im/fossasia/yaydoc

* query-server
GitHub: https://github.com/fossasia/query-server
URL: https://query-server.herokuapp.com
Mailinglist: https://groups.google.com/forum/#!forum/fossasia
Chat: https://gitter.im/fossasia/query-server

**Comment by abishekvashok** [comment]
@mariobehling did you really posted it here?
