### ISSUE TITLE
Add and improve Wikipedia articles on FOSSASIA

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#227]
The current Wikipedia article on FOSSASIA was too long and full of exact copies of the website and therefore was deleted. Please create a relevant Wikipedia article on FOSSASIA on Wikipedia and improve it step by step.

https://en.wikipedia.org/wiki/Draft:FOSSASIA

**Comment by abhinavralhan** [comment]
Hi @mariobehling, would you like me to take this up?

**Comment by mariobehling** [comment]
@abhinavralhan Would be great. The draft is here and was rejected: https://en.wikipedia.org/wiki/Draft:FOSSASIA

It needs to be improved.

**Comment by abhinavralhan** [comment]
@mariobehling any suggestions to what you require?

**Comment by mariobehling** [comment]
@abhinavralhan Please go to https://en.wikipedia.org/wiki/Draft:FOSSASIA and work with the Wikipedia community to improve this post, so it can get accepted. Maybe work with Wikipedians around you as well.

**Comment by abhinavralhan** [comment]
Sure @mariobehling, I will get to right away.
Also, could you tell me if I become a FOSSASIA contributor/member after this? If yes, how do I add it to my profile?

**Comment by mariobehling** [comment]
@abhinavralhan This question is out of scope of this issue. We have chat channels for such questions. You are a contributor if you actually start to contribute. We will invite you after a few days to the project then. Hope we can keep the discussion short. Would be great to see contributions and focus on issues. I am not able to reply to out of scope questions on issues anymore.

**Comment by abhinavralhan** [comment]
@mariobehling thank you :)

**Comment by abhinavralhan** [comment]
Hi @mariobehling , I made a few changes and sent it for review yesterday. If you're the one reviewing it, let me know if it needs more work. Thought I'd just inform you. Thanks.

**Comment by mariobehling** [comment]
@abhinavralhan It is the Wikipedia community reviewing it and I dont know how fast they are. Would be great if you get the article online.

**Comment by abhinavralhan** [comment]
@mariobehling if by getting it online you mean getting the article reviewed and accepted, I will make it happen :)

**Comment by abhinavralhan** [comment]
@mariobehling I tried submitting it but it was rejected by 'Sulfurboy' who stated that - "This still fails notability in my opinion. Significant articles only mention the company in passing. The rest is mostly press releases."
Apologise for the late response but they take 2 weeks to respond, what do you suppose I do next?

**Comment by mariobehling** [comment]
@abhinavralhan Wikipedia has their own ways to work on things. The issue here is about working with that community. If you know someone who is an active Wikipedian in your area, maybe you can work with them to resolve this as I am not an active Wikipedian. There is no discussion needed here.

**Comment by accakks** [comment]
@mariobehling Can I work on this if @abhinavralhan isn't working currently?

**Comment by hpdang** [comment]
@accakks Sure, please go ahead. Maybe find some Wikipedians around you who have experience. It seems the draft is not merged due to some WP policies.

**Comment by accakks** [comment]
@hpdang @mariobehling I have re-submitted the draft making some changes and adding more references. I'll inform you of further progress.

**Comment by mariobehling** [comment]
Thanks, but I don't think this will be accepted as there are a number of errors are now in the references and they are asking for more sources. Looks like you are adding only Melange as a source.

**Comment by 0x48piraj** [comment]
@mariobehling 
I'm on it. I'll try to make a breakthrough :1st_place_medal:

**Comment by sk9331657** [comment]
@mariobehling I have gone through the draft and I think it needs improvement. Can I work on it??

**Comment by mariobehling** [comment]
There is no need to ask me. Just go ahead.

**Comment by VaaibhaviSingh** [comment]
Hi @mariobehling, can I work on the draft?
