### ISSUE TITLE
Chrome extension for SUSI.AI

### ISSUE THREAD

**Issue by zamhaq** [fossasia/labs.fossasia.org#230]
**What exactly the chrome extension should do?**
The chrome extension can be a chat window to the SUSI AI. 

**What is the problem the extension solve or what functionality does it provide?**
The user will be able to access and chat with SUSI from any browser tabs and not having to go to the dedicated tab like when using web client. This will increase the accessibility for the users.

**Do you have an example of an existing extension that does something similar?**
Unfortunately, No. But I am very much excited to implement it. I'll get started this weekend if you guys allow it. Thanks.

@mariobehling

**Comment by mariobehling** [comment]
> The user will be able to access and chat with SUSI from any browser tabs and not having to go to the dedicated tab like when using web client. This will increase the accessibility for the users.

I am unclear what the UI looks like and how to access it. So, I am looking forward to see your idea implemented. Simply start in your own repo. Cheers.

**Comment by zamhaq** [comment]
@mariobehling I have implemented basic prototype. Still a lot more work is need to be done. But you can get the general idea. Here is a screenshot. 
![susiscreen](https://user-images.githubusercontent.com/20766601/30594375-6c3ebaf8-9d6b-11e7-9e62-305b01fa48d4.png)
The popup will allow to chat with SUSI from any tab without having to go to webclient for SUSI. One can use the extension if he wants simple queries from susi.
Here is the repo link https://github.com/zamhaq/susi-chrome-extension.
Instructions are provided in the **readme.md**. Please checkout and provide feedback. The UI will be improved more and also tell me if you can add the repo to Fossasia organisation now or more amount of code is required ? I was thinking that If you could add the repo to Fossasia organisation then more people would be able to contribute.
Thanks. Please provide feedback.

**Comment by zamhaq** [comment]
@mariobehling Please review.

**Comment by mariobehling** [comment]
Great job!

Please follow up here now: https://github.com/fossasia/susi_chromebot

Also check how to get others to star the project and tweet about it with a screenshot. Cheers!
