### ISSUE TITLE
Please provide me JSON definition list of all repos and filemasks, so they can be imported to weblate

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#231]
1. OPEN EVENT
* https://github.com/fossasia/open-event-android
* https://github.com/fossasia/open-event-webapp
* https://github.com/fossasia/open-event-frontend
* https://github.com/fossasia/open-event-theme
* https://github.com/fossasia/open-event-orga-app

2. PSLAB
* https://github.com/fossasia/pslab-android

3. PHIMPME
* https://github.com/fossasia/phimpme-android

4. SUSI.AI
* https://github.com/fossasia/susi_android
* https://github.com/fossasia/susi_iOS
* https://github.com/fossasia/susi_server
* https://github.com/fossasia/susi_skill_cms
* https://github.com/fossasia/chat.susi.ai
* https://github.com/fossasia/admin.susi.ai
* https://github.com/fossasia/accounts.susi.ai
* https://github.com/fossasia/dev.susi.ai

5. SUSPER
* https://github.com/fossasia/susper.com

6. LOKLAK
* https://github.com/fossasia/loklak_search
* https://github.com/fossasia/loklak_wok_android

Please provide me JSON definition listin all repos and filemasks, so they can be imported to weblate. Example:
```
{
    "name": "Organizer Server",
    "slug": "organizer-server",
    "repo": "https://github.com/fossasia/open-event-orga-server.git",
    "branch": "development",
    "filemask": "app/translations/*/LC_MESSAGES/messages.po",
    "template": "",
    "new_base": "app/translations/messages.pot",
    "file_format": "po",
    "license": "GPL-3.0+",
    "license_url": "https://spdx.org/licenses/GPL-3.0+"
}
```
Please add the JSON files here: https://docs.google.com/document/d/1DRaedsMml6KPS9z92X197j6BqNiqqG9k52XAGh0n15M/edit

**Comment by techpool** [comment]
I would like to take this up.

**Comment by ParthS007** [comment]
I want to work on this.

**Comment by vaibhavsingh97** [comment]
I also want to work on this

**Comment by tulikavijay** [comment]
I would like to work on this too.

**Comment by rupav** [comment]
I too would like to work on this :)

**Comment by vaibhavsingh97** [comment]
@mariobehling Do we need to create new doc? As the doc link you provided creates untitled document

**Comment by mariobehling** [comment]
Use this doc for all json files, please.

**Comment by mariobehling** [comment]
Seems like a lot of people are interested in this. Each file should only take a few minutes, but it would add up for one person. So, it would be great as a community effort. Please add the JSON snippets here: https://docs.google.com/document/create?usp=drive_web&folder=0AIn_k1amQnpyUk9PVA&authuser=0

**Comment by bhaveshAn** [comment]
@mariobehling Please let me know about 
> "filemask": "app/translations/*/LC_MESSAGES/messages.po",
    "template": "",
    "new_base": "app/translations/messages.pot",
    "file_format": "po",

for `open-event-orga-server` these values were relating to `translations` directory but what about a repo which do not have `translations`
For example, for `open-event-webapp`:
> src/backend/*.js
src/selenium/*.js

so  can we use filemask can be : `src/*/*.js` ?

**Comment by mariobehling** [comment]
>  what about a repo which do not have translations

In a repo that does not have translations, we need translations. Please open an issue in those repos and help to make it happen.

**Comment by abishekvashok** [comment]
@mariobehling is this still needed?
