### ISSUE TITLE
Website: Avoid flickering/moving items on top menu and when scrolling over dropdown menu items

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#232]
The icons have a moving effect. Please avoid this effect and adapt it to the same way it works on http://fossasia.org

**Comment by kubami9** [comment]
Icons in the navigation? Then it's not only icons but all positions in the nav after scrolling. I can work on it 👍

**Comment by duttaditya18** [comment]
On it!

**Comment by duttaditya18** [comment]
#239 fixes this.
