### ISSUE TITLE
Improve readability of projects section 

### ISSUE THREAD

**Issue by Ploypiti** [fossasia/labs.fossasia.org#240]
### Expected results
Nicely arranged project section, improved readability, better UX.
### Actual results

**Images & Texts**
The descriptions and images in project section are messed up, eg. text and image are inseparable.

![screenshot - lab](https://user-images.githubusercontent.com/32614202/34028184-eb7ab6e8-e193-11e7-8473-b3b8711c1cca.jpg)

And the image is a way too large and was unable to read what's included in the image, and the meaning of the project may be changed, but to be honest, screenshot of the website or project is merely important since all details are already provided in the text box--in my opinion, logo alone is enough, but in some case *selected interface* would be better, eg. in case of Susi AI and LokLak we should add image of chat interface and result of the search respectively, **not the whole screenshot of the page**

![screenshot - lab2](https://user-images.githubusercontent.com/32614202/34028350-0a187990-e195-11e7-8e18-c1919b89ad8d.jpg)

**Responsivity**
The image was cut half on Ipad and does not exist on phone devices. For Ipad, this is another reason we should use an image that can represent the meaning of the project at a glance, however, there's no need to worry about the image on phone.

Below is Ipad interface, padding is unstable and different in each text box.

![screenshot - ipad](https://user-images.githubusercontent.com/32614202/34028592-bdf5c4c6-e196-11e7-8707-4217d1b36fbc.jpg)

### Steps to reproduce the issue

- [ ] Add more representative and clear images or screenshot
- [ ] Fix padding on Ipad

Working on this :v: Any suggestion is highly welcomed (and needed)

**Comment by 0x48piraj** [comment]
1 month of inactivity, Taking this up :100:
