### ISSUE TITLE
Add pointing location in Google map and position of sidebar social icons

### ISSUE THREAD

**Issue by simsausaurabh** [fossasia/labs.fossasia.org#248]
This issue suggests: 
 - ***Feature:***
 Clicking on location address should automatically point to the actual location on Google maps

![address](https://user-images.githubusercontent.com/16608864/34157020-c4573d5c-e4e5-11e7-8687-aa2483dc28cf.png)

 - ***Enhancement:***
Position of social link icons with copyright statement should be at bottom(footer section). It's a mere trivial to place it at bottom in side bar

![iconposition](https://user-images.githubusercontent.com/16608864/34157212-a64a2e40-e4e6-11e7-9d84-60e403269919.png)

**Comment by simsausaurabh** [comment]
@mariobehling I wan to work on it and please tell me whether I should re-position of social icons in side bar or not. Thank you.

**Comment by mariobehling** [comment]
Currently, this is low priority and not urgently needed. Therefore closing it.
