### ISSUE TITLE
Social links to be added in some places

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labs.fossasia.org#252]
##Working On it

**Comment by mariobehling** [comment]
Actually, we should keep the FOSSASIA sites aligned and we need a lot of help for the software projects at FOSSASIA. It is unclear what specifically you want to work on. There is little information provided in this issue. Therefore these kind of issues take up resources of developers and mentors to review stuff. Instead we need to focus on our applications. Low priority. Therefore closing.
