### ISSUE TITLE
Replace the image by SUSI.AI Official Logo

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/labs.fossasia.org#262]
Current image is good, but I think the below image should be preferred.

![](https://pbs.twimg.com/profile_images/904617517489979392/6Hff65Th.jpg)

Reviews needed - @hpdang @mariobehling @vaibhavsingh97 @ParthS007

**Comment by PulkitMishra** [comment]
Hi @0x48piraj , I have made the required changes. Please check.

**Comment by 0x48piraj** [comment]
Pardon me, but where to check @PulkitMishra  ?

**Comment by PulkitMishra** [comment]
@0x48piraj Please check the pull request that I created : https://github.com/fossasia/labs.fossasia.org/pulls

**Comment by 0x48piraj** [comment]
@PulkitMishra 
Got it! However, Please give the exact Pull Request link in future. :+1: 
Also, Link the Issue in your PR you solved :+1:

**Comment by PulkitMishra** [comment]
@0x48piraj Noted. Thanks.
