### ISSUE TITLE
Directed to wrong link on opening on clicking Susper github page under ideas

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/labs.fossasia.org#265]
<img width="731" alt="screen shot 2018-02-13 at 11 24 56 pm" src="https://user-images.githubusercontent.com/29942790/36165359-4feb5df2-1115-11e8-8409-3289147346c8.png">

**Code causing this error.**
Wrong link showing in the json data fetched from the API

**Would I like to work on this ?**
Yes

**Comment by mariobehling** [comment]
Seems to work for me.
