### ISSUE TITLE
Redesign and Restructure Badgeyay backend REST API

### ISSUE THREAD

**Issue by raju249** [fossasia/labs.fossasia.org#266]
Hi @mariobehling ,
I would like to propose this project of redesign and restructuring bageyay backend REST API.
I would like to work on the proposal and making it module driven so that any frontend client will be able to call it's API.
Request you to mark this with a GSoC label if you find it fit as a GSoC project.

Thanks

**Comment by abishekvashok** [comment]
Basically that would be too short won't it?

**Comment by raju249** [comment]
That will depend on what we do exactly.
Make badgeyay as a library or just a rest API backend. Also we can think of some new features.
Let me know what you think.

**Comment by mariobehling** [comment]
This issue should go into the badgeyay repository.
