### ISSUE TITLE
Build a bot for FOSSASIA

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/labs.fossasia.org#268]
As FOSSASIA community is growing and so as projects, We need bots to automate some of the process so developers and maintainers can focus on developing the projects. Right now, we have one bot which is enabled in some of the projects and can do basic task like adding labels, etc.
We can have bots which can do following:

1. Helping new contributors who joins FOSSASIA
     - [ ] Respond to user based on the query. For ex: If user asked that he is new to the FOSSASIA    Community and have experience in Python, Android than Bot can respond with the links  of relevant projects. Also, will share additional resources which will help newcomer.
    - [ ] Automatically add newcomer in `New contributor` team of FOSSASIA
    - [ ] Automatically, DM necessary steps to do like Execute Star me projects, Subscribe to mailing list, etc.
    - [ ] Automatically, can take survey to improve experience with FOSSASIA

2. Bot Configuration
   - [ ] Can configure bot at once place, i.e. we can define which repository, we want bot to be active.
   - [ ] Can add/remove labels (These labels will be same in all the repository like `LGTM`, `WIP`, `needs-rebase`, `do-not-merge`, etc)
   - [ ] Can define individual config on each repository
   - [ ] Can make releases
   - [ ] In Case of Android, bot can push update directly to Play Store, F-droid

3. Issues
      - [ ] Add labels to the issues (via command like `/Kind bug`, `/needs discussion`, `/on hold`, etc)
      - [ ] can assign user to the issues (If user is in the org teams)
      - [ ] can add `stale` label if issue is older than 90 days
      - [ ] Unassign user if he haven't submitted PR for the issue in the given time period, if user had re assigned themselves and still if he/she fails to send PR, than restrict user to reclaim (can be configured)
      - [ ] users can close and reopen issue (via command like `/close`, `/reopen`)
      - [ ] user can open issue through gitter
      - [ ] Helps user can self-assign issue through gitter or commenting on the issue itself

4. PR's 
    - [ ] Automatically add labels (like `needs-review`, `New-PR`, etc) to the PR  and add label depend on the size of the PR (like `size/xS`, `size/S`, `size/M`, `size/L`, etc)
    - [ ] Automatically assign maintainers for review (Github suggests users and also, who are actively reviewing PR's can be assigned to review PR)
    - [ ] One can approves a pull request (via command like `/lgtm`, `/approve`, etc). `Needs-Review` label will be removed when 2 maintainers approve the PR, until then Merge button is disabled. Only admin can merge the PR if approval is less than 2. [Only Users listed as maintainers, approves can use this]
    - [ ] Can assign and assign the user. [Only Users listed as maintainers, approves can user target user must be a member of the org that owns the repository] 
    - [ ] Request a review from the user [Only Users listed as maintainers, approves can use this] 
    - [ ] can manually start all the tests (via command `/retest`)
    - [ ] Automatically run linters on each PR which is used by the languages
    - [ ] Can merge/ rebase the PR
    - [ ] Automatically, update the branch once branch is out of update from the base branch.
    - [ ] Can close PR

5. Automatically, Move inactive contributors to the alumni list.
6. Automatically, promote contributors to developer team (maintainers can do it)

Note: This is a very large project and can be broken into different modules

**Comment by vaibhavsingh97** [comment]
@mariobehling Is this can be a part of GSOC? Can i send proposal for the same 😄

**Comment by mariobehling** [comment]
This is not mature enough to be a GSoC project. Our focus for GSoC is Open Event, SUSI.AI, PSLab, Meilix, Susper.

**Comment by stealthanthrax** [comment]
@vaibhavsingh97 , can we use hubot for this issue?

**Comment by pratiksinghchauhan** [comment]
Hi, I want to work on this project, I have earlier worked on several bots, can I use Dialogflow for this project or can you suggest me another framework to use?

**Comment by moulikcipherX** [comment]
Yeah, Sure I can also work on this project so can we have a team for this project. Or we have to work individually.

**Comment by may55** [comment]
Can I take this issue? Or If anyone working can I team up with you?

**Comment by pandaanwesh33** [comment]
Hello every one. I want to contribute to foss asia. I am a begineer in contributing to open source . I know c++. Can I contribute to this project . If no a little help will be highly appreciated.

**Comment by wilsantow** [comment]
Do you mean a personalized chatbot?
