### ISSUE TITLE
Monitoring SUSI.AI Chatbots

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/labs.fossasia.org#272]
There should be a service to monitor all SUSI.AI bots in one place that either they are active or not.As there are bots for many platforms and in order to provide non stop service all the bots should be active all the time. Checking the bots individually is hectic process and time consuming.

**Comment by DNS-404** [comment]
Hi! I'd like to work on this in GSoC '18. 😄
I’ll make a service(preferably a web app) that act as a centralised place to keep a check of all the SUSI AI Bots. It can include following features -

- Keep a track of which bots are offline and which are currently online. This can be done by sending a query to the bots whenever the user opens this web app. If a reply is received then it’ll show that the particular bot is online else it’s offline.
- Keep track of the number of users that are using SUSI AI bot on a particular platform. This will help us know that which platform is targeting most of the audience.
- Keep track of the total messages sent/received to and from the users to SUSI. This will help us in understanding that how much are the users interacting with SUSI AI Bots. Another subfeature with this can be to keep a track of the average messages per user sent/received to and from the users.
- Keep track of the average conversation time between a user and SUSI AI bot.

This can be made similar to [botimize.io](http://www.botimize.io/)
