### ISSUE TITLE
Configurations for Programming Events

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/labs.fossasia.org#279]
When we have programming workshops, it is hard to setup each computer with the same software. It would be nice to have a live image with the pre-installed software ready to use. This may include MIT App Inventor, an Android development environment, Visual Studio Code, git and more. It should be possible to choose this software from a menu. Also, since the live image changes will be removed, some persistent partition via network, owncloud, git or a decentral folder synchronization would be good. Also duplicating the usb device from itself to a number of other devices. This will include working with organizations from around the world to fulfill their customization needs.

**Prerequisite Knowledge**

Shell, Linux Kernel, Build Systems

**Possible Mentors**

Andre Rebentisch, Tarun Kumar, Harsh Lathwal

**Links**
* Website http://meilix.org
* Generator Repository: https://github.com/fossasia/meilix-generator
* Meilix Repository: https://github.com/fossasia/meilix

**Comment by vaibhavsingh97** [comment]
Hi! I would love to work on this and if I am not wrong than I have to make one iso which is ready to use when used live

**Comment by ssirowa** [comment]
@meets2tarun, I'm a Computer Science and Engineering Student at Indian Institute of Technology. I would like to work on this during GSoC. Can you help me get started.

**Comment by meets2tarun** [comment]
@vaibhavsingh97 
Exactly but a little improvement,
 `Anyone can make an iso` which is ready to use when used live `with its own pre-configuration`

**Comment by tabesin** [comment]
Interesting, time to get started with your GSoc applications, 27 March is deadline

**Comment by ojaswa1942** [comment]
I would lile to work on this during GSoC. Can someone help me get started?

**Comment by tabesin** [comment]
First write a proposal like this
https://docs.google.com/document/d/1NgmmMJLIdo5gMWLfg2Uv_j3x_r9VM2qhKtlR8kBSk9Q/edit
and call for reviews on the mailing list.

You just need to follow the Fossasia guidelines and answer all the questions, here
https://docs.google.com/document/d/1E4kNgrOSw64R2IAG45JSIgQL9Yxia-mG2dqlRcrUo-U/edit#

And if you want to take this item feel free to reuse and adapt the text in this ticket.

Otherwise plagiarism is strictly discouraged.

**Comment by subhahu123** [comment]
@meets2tarun @tabesin
If m not wrong u want live iso image or software which will create live iso image for us according our needs

**Comment by meets2tarun** [comment]
Yes @subhahu123

**Comment by subhahu123** [comment]
Like melix generator which generate iso according to our requirement

**Comment by subhahu123** [comment]
@meets2tarun  how can i convert a software into live software (which requires no installation )

**Comment by subhahu123** [comment]
is it about only for linux or all os

**Comment by subhahu123** [comment]
@meets2tarun  for this first , first we have to create a software which convert install only software to portable one or live software  Or  we are supposed to have a bunch of pre-maked portable software and we just have to make a tool to make iso for live run according to the requirement
