### ISSUE TITLE
Implementing advance  Features into Meilix Generator

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/labs.fossasia.org#280]
The aim of this project is to get the autonomous system for the generation of live images of Meilix for plug and play use with the user specific settings

Goals of the Project

- [x]  Generate a ISO using the latest Release of project meilix

- [ ]  Modify default wallpaper 

- [ ]  Add and remove apps from the live build using meilix generator

- [ ] Ability to choose the configuration for the DE (LXQT) like default theme , weather to keep notifications or not (https://github.com/fossasia/meilix-generator/issues/121)

- [ ]  Add pre made configurations for like OS with PEN tools , OS with media tools etc

- [ ] Feature for creating theme (to rebrand OS) which can change grub menu, plymouth , colors of the default theme

- [ ]  give ability to user to get OS uploaded to cloud of his choice

links to Project
https://github.com/fossasia/meilix-generator
https://github.com/fossasia/meilix

**Comment by yashLadha** [comment]
@xeon-zold I am intresetd to send a Patch for this during GSOC.

**Comment by meets2tarun** [comment]
@yashLadha 
Make sure to send your idea for review.
