### ISSUE TITLE
Make Badgeyay into Full Featured Solution for Events

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#281]
Badges are an essential items for conference. The Badgeyay project has developed rapidly over the last few months. The next step is to create a full featured solution that can compete with services like conferencebadge.com. Please compare Badgeyay to existing solutions, make a list of features and outline which features you could implement during GSoC. Also consider that Badgeyay could be used as a plugin for other conference services. Furthermore consider that a full-featured solution should also include login, authentication and billing options similar to conference badge.

**Prerequisite Knowledge**

Flask, Python, EmberJS

**Possible Mentors**

Parth S, Manish, Yash Ladha, Mario Behling

**Repositories/Links**

Please check out: https://badgeyay.com
Repository: https://github.com/fossasia/badgeyay

**Comment by yashLadha** [comment]
@mariobehling I would like to create a proposal for the same.

**Comment by yashLadha** [comment]
Can I add this project also in my proposal.

**Comment by rupav** [comment]
@mariobehling , I will send a proposal for the same.

**Comment by ParthS007** [comment]
@mariobehling  Sharing the proposal for the same on mailing list :+1: .
Thanks for including Badgeyay as a GSoC project this year :tada:

**Comment by vaibhavsingh97** [comment]
@mariobehling I am also sharing the proposal for the same 😄

**Comment by sagar-kalra** [comment]
@mariobehling Already made the proposal regarding changes in UI and will add login and signup too.

**Comment by mariobehling** [comment]
Ok, thanks for the feedback. We can definitely have several people working on the project. We need support for different sizes of badges etc. as well.

**Comment by gabru-md** [comment]
@mariobehling I've shared my proposal on gitter. Waiting for it to get reviewed and added it to the mailing list as well. :)

**Comment by vpsinghg** [comment]
I want to contribute on this project in GSoc  2019 .Can any body guide me how to get started on this project?

**Comment by Subhang23** [comment]
I would like to contribute under this project for GSoc 2019. Could somebody help me get started as to what to do?

**Comment by sk9331657** [comment]
@mariobehling @ParthS007  @gabru-md  @yashLadha  I have submitted my proposal using dashboard . Mentors ,please review the proposal and provide your precious reviews. :smile:

**Comment by hitman96** [comment]
I would like to contribute in this project as a part of GSoc 2019. How should I get started.
