### ISSUE TITLE
SUSI.AI Conversational Web - Plugin for Web Pages

### ISSUE THREAD

**Issue by Orbiter** [fossasia/labs.fossasia.org#288]
We currently have a web client for Susi, but this is not the right environment for the following use case:

Consider that you are running a web portal for your company, for a product or a service. You want to get in contact with your customer. To do so, you replace (a maybe existing) conventional "contact form" with a chat icon in a corner of your web page where you can chat with someone from the company. This chat will naturally ask you for your contact details in case you want to leave that information.

Such a company chat would contain three main elements:
- a company persona of Susi would answer most of the questions
- Susi aims to get the information from the user, contact data or other inquiries
- in case that Susi cannot answer, a human Customer Support Representative is contacted transparently in such a way that the customer does not recognize that Susi is replaced by a human.

To create such a service, we need the following:

- a plug-in for web-pages with the Susi chat
- a company version of our skill CMS to create use-case oriented persona and conversational web content subscription rules. This CMS must also have a plug-in mechanism to enhance company-question related chat with world knowledge as add-on modules
- a database server which serves as the data lake for the information that a customer has written into the chat conversation. That data lake must have a connection to the skill CMS set-up for subscription items to share the same data schema
- a Customer Support Representative interface to react on chat situations where Susi is not able to answer

**Comment by prshntsingh** [comment]
@Orbiter What are the skills required for this project?Please help.

I have knowledge of Python, Javascript, Django and Reactjs.
Can I work on this project ?

**Comment by agampreetsingh** [comment]
Hi @Orbiter  I would like to contribute on this issue. I have working my hands around with susi-server and I have tried making API calls from my own application with node.js.
I have also closely followed the issue [#198](https://github.com/fossasia/labs.fossasia.org/issues/198) and found a lot of similarity with working on the bot messages in the web-plugin and messages from other apps where the susi bot is integrated. 
I plan to make a web page which will provide the bot adding feature to the site.
I want to first add a plugin to add [chat.susi.ai](https://chat.susi.ai/) as an iframe on a webpage. Later I will build a CMS for the user.

Please suggest if you have something else in mind... 
Thank you :)
