### ISSUE TITLE
Need to add Meilix Project to the Website

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labs.fossasia.org#297]
Meilix Project is missing, should be added.

Working on it!

**Comment by abishekvashok** [comment]
I am sorry to tell that we have it already under the name Linux.

**Comment by saarthakchats** [comment]
Oh no, sorry then

**Comment by saarthakchats** [comment]
@abishekvashok 
Should I update the section with the image and links of meilix?

**Comment by saarthakchats** [comment]
I could reframe my issue message or completely discard it. As you say @abishekvashok

**Comment by abishekvashok** [comment]
Ping @mariobehling
