### ISSUE TITLE
Lubuntu should be replaced with Meilix

### ISSUE THREAD

**Issue by saarthakchats** [fossasia/labs.fossasia.org#301]
<img width="1364" alt="screenshot 2018-11-05 at 2 53 48 pm" src="https://user-images.githubusercontent.com/24372680/47989306-a2ad7780-e10a-11e8-9c57-c292d5ac9bba.png">

**Comment by rpotter12** [comment]
@saarthakchats yeah, you said right. Make a PR for this :)
