### ISSUE TITLE
The FOSSASIA logo is not aligned Properly

### ISSUE THREAD

**Issue by Hackerbone** [fossasia/labs.fossasia.org#312]
**The FOSSASIA logo is not aligned properly as shown below**

![screenshot 2018-11-08 at 11 03 41 am](https://user-images.githubusercontent.com/20267705/48179633-14bdd080-e346-11e8-9e41-6b89e0d45661.png)

I would like to work on this Issue :D

**Comment by Hackerbone** [comment]
Can I be assigned to work on this?

**Comment by akshit15013** [comment]
Can I work in this issue ?
