### ISSUE TITLE
Add and correct information for section "SUSI.AI iOS App" and add app image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#319]
The new section "SUSI.AI iOS App" needs correct info, links and app image. Please help to do it.

**Comment by jogendra** [comment]
Anyone who is taking this issue can take this image for the background image for SUSI iOS. I designed this for SUSI iOS Readme. https://github.com/fossasia/susi_iOS/blob/f5c3aa937ceefe09d43d5645bb5ab0af1ae0f48a/docs/_static/susi_app_mask.png
