### ISSUE TITLE
Add and correct information for section "PSLab Hardware" and add app image 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#321]
The new section "PSLab Android App" needs correct info, links and app image. Please help to do it.

**Comment by parammittal16** [comment]
@mariobehling can I do this?

**Comment by aayusharora** [comment]
Hi @parammittal16 Please go ahead  :)

**Comment by parammittal16** [comment]
@mariobehling @aayusharora where can I find the info and images and other stuff ??

**Comment by Aishh2k** [comment]
@mariobehling
