### ISSUE TITLE
Change projects into an "overview" design like on codeheat.org

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#324]
Over time a lot of projects were added to FOSSASIA. It is a bit difficult to get a good grasp of projects. Therefore please change the project listing into an overview style similar to codeheat.org. Keep the icons on the bottom of each project.

![screenshot from 2018-11-13 10-52-07](https://user-images.githubusercontent.com/1583873/48405333-6396ac00-e732-11e8-8999-74d1a6838e3f.png)

**Comment by Sid911** [comment]
Working on it, sir.
