### ISSUE TITLE
There's an icon overlap when browser window is resized

### ISSUE THREAD

**Issue by Hackerbone** [fossasia/labs.fossasia.org#326]
The navbar icons are getting shifted to the next line when the browser window is resized.

![screenshot 2018-11-17 at 10 14 39 pm](https://user-images.githubusercontent.com/20267705/48663468-9f28d180-eab6-11e8-806c-ffd2fad0d154.png)

There is some margin and padding issues too..

**Im working on this**

**Comment by HarshCic** [comment]
@mariobehling can i work on this?
