### ISSUE TITLE
Add missing projects listed on frontpage to list on labs project section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#336]
There are a number of projects listed on the front page fossasia.org. Please ensure all projects are listed here as well in the sections.

![screenshot from 2018-12-09 07-59-17](https://user-images.githubusercontent.com/1583873/49694326-95136380-fb88-11e8-9208-b90d3ad3f981.png)

**Comment by jayantsudo24** [comment]
Hello @mariobehling, to work on this can you confirm me is there any other projects associated with fossasia.org except these 16.

**Comment by jayantsudo24** [comment]
Hello mariobehling, to work on this may you confirm me that only these 16 projects from fossasia.org needed to be shown.

**Comment by jayantsudo24** [comment]
Hello @mariobehling, except these 16 projects from fossasia.org is there any other project needed to be listed.

**Comment by HarshCic** [comment]
Can i go ahead with this one?
