### ISSUE TITLE
Open Event: Roadmap for Server/Frontend and Mobile App Integrations

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#341]
Below is a list of to dos and missing features for the Open Event project. Going through the list could be helpful for any developer who is interested in joining the project as well as for students interested to participate in GSoC.

Repository Links: https://github.com/fossasia?utf8=✓&q=open+event

Website: https://eventyay.com

Eventyay Version 2 Backend: https://api.eventyay.com

Eventyay Version 2 Frontend: https://next.eventyay.com

**Maintain and Administer System**
*   Maintain system
*   Ensure it runs
*   Move files to "volumes" instead of hosting them on Linux system
*   Ensure automatic deployments work 
    *   a) master to eventyay.com
    *   b) dev branch to dev.eventyay.com (for testing purposes)

**Bugs**
*   Fix reported bugs of system

**Login/Tickets**
*  Implement login/ticket buying process similar to other systems (same as Eventyay V1 and Eventbrite)
*  Enable ticket buying without login

**Payments**
*   Implementation of payment gateways in India, Google Wallet, Sofort Pay, Paylah, Wechat, Alipay
*   Add donation feature "pay what you want"
*   Implement missing functionalities for payment and sales sharing with platform
*   Implement account page
*   Implement "Pay invoice" for event organizers to pay to platform
*   Implement emails for different payment statuses, that can be administered/changed through the admin UI
*   Implement account page for payment overviews for users similar to Paypal for users
*   Implement admin overview of payment statuses for different roles in admin sales tab, e.g. marketing or superuser (limit accessible views depending on status)
*   Implement "marketing ownership" of events in admin UI Sales tab (Marketers/Sales can see only events related to them)
*   Automatically send out payment reminders. Different reminders can be defined in admin area. Frequency and details to be edited through the admin UI as well.
*   Send reminders to organizers to pay invoice
*   Limit account features if organizer does not pay invoice to platform, e.g. stop collecting money, stop access to event pages, stop access to view event dashboards

**Ticket flow**
* Simplify ticket buying flow to match eventyay V1 and Eventbrite: Not logged in user not able to buy ticket, anonymous user not automatically registered when buying ticket https://github.com/fossasia/open-event-frontend/issues/1913
* Ticket PDFs should be generated dynamically. 

**Wait List**
* Design and implement a waitlist for participants, e.g. where they can sign up and the organizer can allow users to register by sending them an access code or moving them to the “next level”

**User Area**
*   Define frontpage events by admin in admin area. Alternatively enable admin to set one event as frontpage.

**Mobile Version**
*   Make web UI work for mobile screens

**Web Generator**
*   Test and ensure web generator works with API version and make changes as needed

**Form Builder**
*   Create a form builder similar to Eventbrite, Google etc. for 
*   a) speaker data
*   b) attendee data

**Search/Explore**
*   Implement missing functionalities to ensure search and explore events work
*   Offer standard filters such as location, time/date, type, categories

**Groups and Recurring Events**
*   Implement groups similar to Meetup
*   Implement recurring events similar to Meetup
*   Implement a waitlist

**Roles**
* The entire permission and roles system needs to be refactored. For instance, there are apis for each entity. And all of them require organiser level access to fetch and create. Now if a non logged in user is to create an order. Order requires attendees, tickets, discount codes. Currently API of each of them does not allow a non registered user to access them. For discount codes, even registered users are able to do so. Also, most of them require user to be verified. A user who is placing an order for the first time, cannot be verified. 
*   Enhance user roles
*   Provide option to transfer event to another organizer
*   Implement Roles: Organizer, Co-Organizer, Track Organizer, Registration Manager, Check-In Assistant

**Images**
* In the server backend, the creation of various images needs to be a ‘celery’ task And become an asynchronous operation. Synchronously, it causes a server time out. 

**Server Backend Endpoints**
* There should be an end point which tells if various components of an event are available. For instance, if sessions are available. If speakers are available. I’m current implementation, just to check if speakers or sessions exist a significant number of them are loaded from backend which ruins the performance of frontend.

**Server Backend Errors Codes**
* Error codes need to improve, the messages should be user friendly, so they can be flashed to user directly, instead of adding a layer of language on the frontend while handling them.

**Scheduler**
*   Provide more fine-grained options in scheduler
*   Design Scheduler more similar to Google Calendar

**Public Pages and Web Generator**
*   Design public pages similarly to generator pages
*   Align CSS and design of generator pages and public pages

**Administration Area**
*   Enhance UI and add filters in all admin views
*  Provide a way to edit all system emails

**Security**
*   Implement Security tests and provide automated reports

**Startpage Sections and General UI**
*   Ensure start page shows events based on user location and/or profile
*   Implement additional sections for startpage including
    *   Signup section
    *   Featured events
    *   Other sections
    *   Mobile apps
*   Show search box as in Eventyay V1 on top bar

**Speed Optimization**
*   Optimize site and images for speedy loading of site

**Android Apps**
*   Ensure feature parity with backend/frontend
*   Implement check-in functionalities in organizer app
*   Make apps work with api.eventyay.com and update on playstore/fdroid
*   Enable check in by organizers and scan of participant data by exhibitors
*   Ensure system works in parallel with different organizers
*   Enable different roles, specifically registration staff (only has the rights to scan)
*   Implement roles and features in Android app and server/frontend
*   Add push notifications from organizer, implement it on server and app
*   Implement more analytics
*   Integrate with schedule and implement necessary changes in server and app
*   Provide option to add session to own schedule list

**iOS Apps**
*   Match all features of Android apps

**Venue Custom Map**
* Develop a venue custom map for reserved seating and integrate it into the ticketing process

**Prerequisite Requirements**

Flask, EmberJS, APIs, Web Technologies

**Possible Mentors**

Areeb Jamal, Niranjan Rajendran, Saptak Sengupta, Abhinav K, Dilpreet Singh, Mario Behling

**Repositories/Links**

Git https://github.com/fossasia?utf8=✓&q=open+event

**Comment by jishnujayakumar** [comment]
Hi, my name is Jishnu. I am from India. 

I would like to work on 

[1] Implementation of payment gateways in India, Google Wallet, Sofort Pay, Paylah, Wechat, Alipay.

[2] Add donation feature "pay what you want".

**Comment by Dharmesh-Poddar** [comment]
@mariobehling I would like to work on Public pages and web generator or Administration Area

**Comment by mariobehling** [comment]
Ok, this is great. Thank you for your interest! Anyone interested please start by joining the project and learn about the project by solving some bugs first for example. Once you are more familiar we will align on who would like to work on which area. Please choose your first issues at https://github.com/fossasia/open-event-frontend/issues. Happy coding!

**Comment by imrrahul** [comment]
@mariobehling  I would like to work on Startpage Sections and General UI. Thank you

**Comment by muarachmann** [comment]
@mariobehling very good initiative to organize work for a new year.
Interested in this 
Implement login/ticket buying process similar to other systems.
Enable ticket buying without login
 I will consider contributing. 👍 Happy coding to all

**Comment by harsh-jindal** [comment]
Hi @mariobehling I'm Harsh from IIT Patna, India.
I would like to work on:
1. Login/Tickets
2. Roles

**Comment by Subarna578** [comment]
Hey @mariobehling. I am Subarna Lamsal from Vellore Institute of Technology, Vellore.
I am interested in working on implenting login/tickets buying process.

**Comment by Shivam-nikhil** [comment]
Hi @mariobehling. I'm Shivam from IIIT Kalyani, India. I would like to work on form builder.

**Comment by Nayananga** [comment]
Hi @mariobehling. I'm nayananga from university of jaffna,Srilanka. I'm really interest in working with your iOS Apps which are open-event-ios and open-event-orga-iOS.i forked them already. Thanks in advance.

**Comment by anhanh11001** [comment]
@mariobehling 
Hello, I’m really interested in Open Event project here and I’m also currently contributing to Android Open Event app. I have a few question to clarify the requirements of the Android Apps:

•	What do you mean by “check-in functionalities” for organizer app. What do you expect the outcomes to look like? 
•	“Enable check in by organizers and scan of participant data by exhibitors”. From what I understand, this means that the organizer can scan the QR code from participants ticket and receive their information? Is it correct?
•	“Implement more analytics”. Can you specify what kind of analytics are we looking for. Is it like analytics/feedbacks on events (rating from participants + comments) or the analytics on the way users use the app (A/B testing, click rate,…)?
•	“Enable system works in parallel with different organizers”: So what is the current problems you are facing? What things show that the system now doesn’t work parallel with different organizers?

Thank you, I hope I can receive an answer soon so that I can polish my ideas and discuss with the mentors. Thank you! Have a nice day.

**Comment by mariobehling** [comment]
I think we can have a call for questions before GSoC. Generally, please have a look at other event systems. Our goal is to match functionalities. Please subscribe to our mailing list to receive info for GSoC hangouts: https://groups.google.com/group/open-event Thank you.

**Comment by dilum1995** [comment]
Hello @mariobehling,

I am Dilum from Sri Lanka I’m really interested in Open Event Orga iOS project. Actually, I have Stated working on the project a month back and I have pushed the code related to some general UI of the project, validate user account using email. also, I am currently working on the login and signin functionality. So, I would like to continue my contributions on Open Event Orga iOS.

Thank you

**Comment by abishekvashok** [comment]
@dilum1995 you continue working with it. Targeting the entire issue in a single pr, you may create sub issues and solve them in separate PRs. :) Keep up the good work

**Comment by anurag629** [comment]
Hi, I would like to develop/contribute Login/Tickets something similar to Eventbrite. I have knowledge of Python, Django, djangorestframework, react, ML,  DL, and C++. It will be great to hear from you guys.

**Comment by horizenight** [comment]
If the issues are still open I would like to work on it !
