### ISSUE TITLE
Implement search and data services in the Open Event server application, enable automatic import of events and enhance event analytics

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#345]
The aim of this project is to develop Open Event into a one stop resource for events and a big data hub holding information on all kinds of events across the web.

To achieve this we need to implement search and big data services in the server application. Another part of this is to enable automatic import of events from other platforms and enhance event analytics.

The project will include to add the ability to connect to a [query server](https://github.com/fossasia/query-server) deployment and query for events.

Also compare open issues in this area: https://github.com/fossasia/open-event-orga-server/labels/search%20project

**Open Event Orga Server**: The Open Event Orga Server enables organizers to manage events from concerts to conferences and meet-ups. It offers features for events with several tracks and venues. Event managers can create invitation forms for speakers and build schedules in a drag and drop interface. The event information is stored in a database. The system provides API endpoints to fetch the data, and to modify and update it. Organizers can import and export event data in a standard compressed file format that includes the event data in JSON and binary media files like images and audio.

**Communication**: Please join our mailing list to discuss questions regarding the project: https://groups.google.com/forum/#!forum/open-event. Our chat channel is on Gitter here: http://gitter.im/fossasia/open-event-orga-server

**Prerequisite Requirements**

Flask, EmberJS, APIs, Web Technologies

**Possible Mentors**

Areeb Jamal, Niranjan Rajendran, Saptak Sengupta, Abhinav K, Dilpreet Singh, Mario Behling

**Repositories/Links**

Git https://github.com/fossasia/open-event-orga-server

**Comment by prabhupant** [comment]
@mariobehling I'd love to work in this. Will be sending my proposal soon. Hope to be an even more integral part of FOSSASIA! :smiley:

**Comment by rpjayasekara** [comment]
@mariobehling I would like to work on this project, I think no one is working on this as a GSoC project. I think I have enough knowledge , Can you guide me to work on this project if no one is currently working on this.

**Comment by jsparmani** [comment]
@mariobehling I am quite interested to work on this project. Please assist on how should I start working on the project.
