### ISSUE TITLE
Make top menu exactly as fossasia.org on all labs pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#346]
The top menu on labs.fossasia.org has a few issues. Please identify all issues and make the menu same as fossasia.org, e.g.:

- [x] link logo to fossasia.org
- [x] fix Google Code-In submenu
- [ ] Make top menu exactly like fossasia.org
- [ ] Add summit link

![screenshot from 2019-01-30 21-18-46](https://user-images.githubusercontent.com/1583873/52010020-ae73c480-24d4-11e9-975c-d9a43bf8ee8c.png)

**Comment by Shreyanshnit19** [comment]
First two issues have been resolved [here](https://github.com/fossasia/labs.fossasia.org/pull/350#issue-249843822)
Let me know if any issues 
Thanks !

**Comment by realslimshanky** [comment]
@Shreyanshnit19 Thanks for the effort. Would you like to help with the remaining issues as well?

**Comment by Shreyanshnit19** [comment]
@realslimshanky Sure !

**Comment by realslimshanky** [comment]
Great. @Shreyanshnit19 would be waiting of your PR :)

**Comment by shatakshi-shukla** [comment]
I would like to take up the remaining tasks if available.

**Comment by ayusdas2000** [comment]
I resolved the last issue that is to take out the burger menu.
