### ISSUE TITLE
Add "ideas link" to projects menu item

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#347]
Link to "/ideas.html" in this repository.

![screenshot from 2019-01-30 21-24-36](https://user-images.githubusercontent.com/1583873/52010333-98b2cf00-24d5-11e9-9161-c1515313ddc3.png)

https://labs.fossasia.org/ideas.html

**Comment by RisingGeek** [comment]
is this issue resolved?
