### ISSUE TITLE
Implement features to create versatile custom distributions using Meilix and Debian

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#348]
The aim of this project is to get the autonomous system for the generation of live images of Meilix for plug and play use with the user specific settings

**Features to be Implemented**

- Modify default wallpaper 
- Add and remove apps from the live build using meilix generator
- Ability to choose the configuration for the DE (LXQT) like default theme , weather to keep notifications or not (https://github.com/fossasia/meilix-generator/issues/121)
- Add pre-made configurations for like OS with PEN tools , OS with media tools etc
- Feature for creating theme (to rebrand OS) which can change grub menu, plymouth , colors of the default theme
- give ability to user to get OS uploaded to cloud of his choice

**Prerequisite Knowledge**

Shell, Linux Kernel, Build Systems

**Possible Mentors**

Andre Rebentisch, Tarun Kumar, Harsh Lathwal

**Links**
* Website http://meilix.org
* Generator Repository: https://github.com/fossasia/meilix-generator
* Meilix Repository: https://github.com/fossasia/meilix

**Comment by tabesin** [comment]
https://github.com/fossasia/meilix/issues/111 Review Default file associations with apps
