### ISSUE TITLE
Implement a booking system for Badges

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#351]
Badges are currently generated in a limited number. Please implement the possibility to book more features and ways to generate more badges as a premium feature.

**Prerequisite Knowledge**

Flask, Python, EmberJS

**Possible Mentors**

Parth S, Manish, Yash Ladha, Mario Behling

**Repositories/Links**

Website: https://badgeyay.com
Git: https://github.com/fossasia/badgeyay

**Comment by sk9331657** [comment]
@mariobehling I will like to work on this. Will mention the workflow for this in My Proposal. :smiley:

**Comment by abhi40308** [comment]
@mariobehling I would like to work on badgeyay. Will be sending my proposal soon.

**Comment by sk9331657** [comment]
@mariobehling @gabru-md @ParthS007  @yashLadha Fossasia Summit 2019 was an awesome experience and Codeheat Ceremony was the best . Will send the proposal stating features that will be implemented in GSOC 2019.

**Comment by gabru-md** [comment]
Glad to hear that @sk9331657 
Start working on your proposals. All the best :+1:

**Comment by sk9331657** [comment]
> Glad to hear that @sk9331657
> Start working on your proposals. All the best

Thanks @gabru-md  . Will be highly delighted to work with you.

**Comment by nanspro** [comment]
Hello guys :smile: 
I have worked upon badgeyay two years back and i was one of the admin handling the repo. This was my first open source project on which i contributed a lot, and now i want to work on this as part of gsoc this year.
Will submit my proposal soon for review.
