### ISSUE TITLE
Develop Neurolab Firmware and OS packages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#354]
The goal of the Neurolab project is to develop an easy to use open hardware measurement headset device for brain waves that can be plugged into an Android smartphone and a software application and enables us to understand our brains better.

Our brains communicate through neurotransmitters and their activity emits electricity. The neuroheadset measures that electricity on the skin of the forehead and the software processes the signal so that it can translated into a visual or auditory representation. The data that can be collected can be analysed to identify mental health, stress, relaxation and even diseases like Alzheimer.

Current devices in the medical industry are usually not accessible by doctors due to their high pricing. They are also complicated to use. The idea of the device is to integrate it into a headband and focus on signals that can be obtained through the frontal lobe.

A difference to existing projects like OpenBCI is that it will not be necessary to 3D print large headsets. Instead we are focusing on creating a device that collects as much data as possible through the forehead. To achieve this goal we are using high-grade sensors and flexible electronics.

**Required Features to be Developed**

* Implement a firmware for alternative ICs to AD7173 and OPA2111
* Update Neurolab desktop app to using latest libraries and Java version
* Provide Neurolab desktop packages for Linux, Windows and Mac
* Automatically build desktop packages on each merged PR for all major platforms

**Required Knowledge**

C, Firmware development, Linux OS, Package management, Android

**Possible Mentors**

Padmal M, Eden Jay, Willi D., Hirose Ko

**Repositories and Issue Tracker**

Neurolab Android https://github.com/fossasia/neurolab-android
Neurolab Desktop https://github.com/fossasia/neurolab-desktop
Neurolab Firmware https://github.com/fossasia/neurolab-firmware
Neurolab Hardware https://github.com/fossasia/neurolab-hardware

**Comment by bw-space** [comment]
Is this project assigned to someone, already for the GSoC, as I want to contribute to this issue.
