### ISSUE TITLE
Develop Badge Magic iOS app with Bluetooth Functionality

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#356]
Badge Magic is an Android app to control LED name badges. The goal is to provide options to portray names, graphics and simple animations on LED badges. For the data transfer from the smartphone to the LED badge we use Bluetooth. The project is based on the work of Nilhcem.

The implementation in the Android app consists of manipulating bits. That may be tricky. A single bit error and nothing will work, plus it will be hard to debug. For those reasons, and since the specs are perfectly clear it is recommended to write unit tests before the code implementation.

Among the features that need to be implemented are:

* Implement a badge preview on the top of the screen
* Implement an in-app saving and export function for badges
* Implement animations
* Add feature to display bitmap
* Fix IllegalArgumentException when SEND button click 3 times
* Adapt app for different iOS versions
* Support Bluetooth and WiFi

**Required Knowledge**

Swift, iOS

**Possible Mentors**

Jogendra Kumar, Areeb Jamal

**Repository**

Badge Magic Android: https://github.com/fossasia/badge-magic-android

**Comment by tusharjindal353** [comment]
I am a GSOC 2019 applicant and I am interested in applying for this project

**Comment by fragm3** [comment]
@mariobehling @jogendra @iamareebjamal Can I send a proposal for creating Badge Magic app using React Native. Instead of having separate app for Android, iOS, one React Native app can be used. Shifting tech to React Native will be a good step, many big tech companies(Uber, Instagram, etc) are using it. The functionality above can be implemented using React Native.

**Comment by iamareebjamal** [comment]
We can't do low level stuff in React Native, project is already in Kotlin. We may extract common code and use Kotlin/Native multiplatform for shared code

**Comment by jogendra** [comment]
@fragm3 Since this project is using CoreBluetooth and Wi-Fi APIs which will be hard to implement in React Native. There is no replacement for Native.

**Comment by fragm3** [comment]
@jogendra @iamareebjamal I think, core API's for bluetooth, Wi-Fi can be implemented using React Native as well. Check out: [react-native-ble-manager](https://github.com/innoveit/react-native-ble-manager).

**Comment by siddharth952** [comment]
Is this project till open to be worked on? Is someone working on it right now?
