### ISSUE TITLE
Add space below lists on website

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#357]
The space below lists is not following design, e.g. on the ideas list https://labs.fossasia.org/ideas.html

![screenshot from 2019-02-13 03-41-56](https://user-images.githubusercontent.com/1583873/52675825-7727fd80-2f41-11e9-8bb0-00920562a8e0.png)

**Comment by sarthak247** [comment]
@mariobehling I'm interested in doing this. Can you guide me from where should I start?

**Comment by shatakshi-shukla** [comment]
I am new to open source.Kindly check the updates and share your feedback for the same.

**Comment by realslimshanky** [comment]
@shatakshi-shukla please check reviews on your PR.
