### ISSUE TITLE
Enhance Integration of Voice/Audio Features with Hardware Platform

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#359]
SUSI.AI uses Raspi and the Respeaker Voice Hat. Successful user interactions depend a lot on the environment and skills being used. Changing the hotword sensitivity does not result in acceptable outcome as the device switches on very quickly even though the hotword was not very similar to the actually trained hotword. The goal of this project is to improve this feature. 

**Related Features**

* Improving hotword recognition
* Implement automatic sound control
* Automatically adjust sensitivity and volums

**Required Knowledge**

Linux OS, Package management, Voice Recognition, AI Algorithms, PocketSphinx, Flite

**Possible Mentors**

Sanskar Jethi, Michael Christen, Hong Quan, 

**Repository**

SUSI Linux: https://github.com/fossasia/susi_linux

**Comment by naman653** [comment]
Why there are no ideas for Susi android. It had lots of severe bugs to solve and also some features like voice input, etc to be improved. Also, need to make UI a bit smoother and more interactive.
