### ISSUE TITLE
Develop Hotword Library with Web Controls

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#360]
SUSI.AI currently uses the Snowboy Hotword detection. A number of features are missing and pull requests from our developers were not merged (e.g. [here](https://github.com/Kitt-AI/snowboy/pull/493). In order to improve the hotword features of SUSI.AI we need to develop an independent library and web control system.

Please fork the Snowboy Hotword library and propose ways to set it up incorporating our community PRs. Develop features to create the library for use in SUSI.AI as a binary through a web system similar to Snowboy.

**Prerequisite Knowledge/Technologies**

NodeJS, Voice Recognition, C++, Python, Shell, Javascript, Makefile, HTML, CSS

**Possible Mentors**

Quan, Michael Christen

**Repositories**

Snowboy: https://github.com/Kitt-AI/snowboy
Website: https://github.com/Kitt-AI/Kitt-AI.github.io

**Comment by shabnam99** [comment]
hello,
I want to go with this project in GSOC. Any suggestion please?

**Comment by Aakash-DD** [comment]
@mariobehling  Can u give just little more details..... for this
