### ISSUE TITLE
Feature Completion and Standardization of SUSI.AI Web Projects 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#369]
SUSI.AI web clients have made a big step forward. We now need to make the project more stable and feature complete. Please research and propose missing features and standardize and improve the web projects of SUSI.AI. Also collaborate on getting support of functionalities in the server component. Below are a few ideas for improvements:

**Add missing Features e.g.**
* Implement Organizations similar to GitHub
* Make Admin section feature complete (assign roles, implement pagination)
* Fix preview functionality in web client
* Add open functionalities according to issue tracker for settings section
* Thouroughly test and fix issues in bot framework
* Complete features in bot framework (Allow bot only on own site, Include SUSI default skills, Enable bot in my devices, Enable bot for other users, List the chatbot publicly)
* Discuss and implement unification of admin, accounts, web chat in one UI following similar approach to Wordpress
* Implement offline features and synchronization of skills with offline deployment on SUSI.AI Smart Speaker
* Fully implement conversation view in skills
* Fully implement theming
* Implement cookie policy info
* Implement rate limit flow and UI to control API access
* Implement additional settings for all SUSI.AI components
* Implement automatic image scaling e.g. of user profile images
* Implement 2FA authentication
* Implement a skill process to enable/disable skills on personal accounts (Including a way to define system skills - always on skills - by the admin in the admin UI)

**Improve and Standardize**
* Implement mobile views for all pages
* Refactoring of SUSI.AI Web Projects. Remove duplicate code and make common/shared components for same repo and also across repositories.
* Integrate Redux in all SUSI.AI Web repositories and move from Flux architecture to Redux.
*  Integrate Styled components for styling.
*  Standardize the repo structure as per React standards.
* Upgrade React, Material-UI versions. (May need to maintain separate branch for it).
* Work on the documentation of the project.

Technologies: HTML, Javascript, CSS, React-JS, Java, JSON

Repositories: https://github.com/fossasia?utf8=✓&q=susi

**Comment by harsh-jindal** [comment]
@mariobehling I would like to work on this.

**Comment by fragm3** [comment]
@mariobehling I would love to work on these issues, will be sending GSOC draft.

**Comment by Aakash-DD** [comment]
@mariobehling will be sending Proposal soon

**Comment by prateek76** [comment]
@mariobehling I have sent a draft proposal please review.

**Comment by Atharva-001** [comment]
@mariobehling I would love to work on these issues, especially on the conversational bugs in the SUSI AI Assistant
