### ISSUE TITLE
Susper Search Server: Develop Susper Frontend Bundle with Yacy Grid

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#370]
Susper is a front-end for the new Yacy-Grid search server. However, the components haven't been bundled together yet and some functionalities are not implemented yet. Please set up both projects, list missing API support implementations and take issues from the trackers into account to define the specifics of the project. The goal is to achieve a susper search project with frontend and backend that is deployed to FOSSASIA servers. 

Work on the project includes integration of front-end and backend, improvements of frontend to match state of the art search interfaces, inclusion of SUSI.AI rich type answers and writing deployment scripts and installation documentation.

Technologies:

Java, Javascript, JSON, Linux, Cloud technologies, HTML, CSS, Shell Script

Repositories:

* https://github.com/yacy
* https://github.com/fossasia/susper.com

**Comment by ridhishjain** [comment]
@mariobehling I am writing proposal for this project

**Comment by sk9331657** [comment]
@mariobehling  Will like to work on this . Will be sharing proposal soon. :smile:
