### ISSUE TITLE
Implement Visual and Audio Gamification and Neuro-Feedback in Neurolab Android App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#371]
If someone speaks to another person, they would receive feedback, e.g. an voice reaction or something else. How could a reaction to brain waves look like? By controlling our brain waves we could use the computer (e.g. Android phone) to provide visual or audio feedback to our brain activities. People are actually able to control certain brain activities. They can even improve their control and train themselves. This is used for example in meditation practices.

How can visual and audio feedback look like?

Visual: One a device receive certain brain wave signals it could output specific images or visuals on a screen, e.g. change the color, position of an object etc.

Audio: The same applies to audio, once a device receives a certain brain wave signal it could play specific audio signals, e.g. relaxing sounds of ocean waves. If received brain wave signals indicate that the user is meditating we could use ocean sounds to enforce this meditation practice.

There are already applications on the market that try to achieve similar things. Please research existing applications and propose games in the Neurolab Android app.

Technologies: Android, Kotlin, Java

Repository: https://github.com/fossasia/neurolab-android

Compare Existing Apps:
* https://play.google.com/store/apps/details?id=com.emotiv.insightapp
* https://play.google.com/store/apps/details?id=com.emotiv.mentalcommandsapp
* https://play.google.com/store/apps/details?id=com.sonicPenguins.museMonitor
* https://play.google.com/store/apps/details?id=com.neurosky.unitythinkgear
* https://play.google.com/store/apps/details?id=com.neurosky.hafiz
* https://play.google.com/store/apps/details?id=com.neurosky.tutorialplus
* https://play.google.com/store/apps/details?id=com.tkprof.eegreader
* https://play.google.com/store/apps/details?id=com.myr.mymuse2017
* https://play.google.com/store/apps/details?id=com.interaxon.muse

**Comment by Krish-bhardwaj** [comment]
I am interested to fix this issue. I request you to allow me to fix it. can you assign me this issue
