### ISSUE TITLE
Website: Fossasia-Header image is not optimised for deployment purpose

### ISSUE THREAD

**Issue by kushthedude** [fossasia/labs.fossasia.org#373]
#### Issue Description

Fossasia-Header image is not optimised for deployment purpose, It's not compressed for the deploy usage and its getting used at its original size of 5.8 MB.

#### Solution Propose
Optimise the image.

**Comment by CoDeRgAnEsh** [comment]
I've used a 512 x 512 image scale but the image was not resolved quicker, Think some tech stack has been involved in background that causes delay . . .
