### ISSUE TITLE
Website: GitHub API generated links don't direct to the right area anymore

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#376]
Clicking on the link list of the GSoC ideas does not direct to the correct area on https://labs.fossasia.org.

![Screenshot from 2019-12-12 12-48-33](https://user-images.githubusercontent.com/1583873/70710114-c7e1c180-1cde-11ea-8a71-71d790430f3a.png)

**Comment by anishagg17** [comment]
I have checked out every link .They all are working fine.
Can you describe the problem more briefly

**Comment by anishagg17** [comment]
Actually it's working fine in safari but not in google chrome.
![Screenshot 2019-12-13 at 1 37 33 PM](https://user-images.githubusercontent.com/43617894/70782729-b9aea680-1dad-11ea-95f9-49e1ca4bf8f8.png)
Also when we click on this gsoc link a huge amount of space is added in between these two sections:
FOSSASIA Projects
Project Ideas for Coding Programs and Google Summer of Code
