### ISSUE TITLE
Implement Additional Instruments, Improve Usability and Import/Export Features in PSLab Android

### ISSUE THREAD

**Issue by techyay** [fossasia/labs.fossasia.org#378]
The PSLab app has made substantial improvements and follows a common design and standards now. The next step in the development of the app is to add:
* more instruments
* sample datasets and improve import/export and mapping features
* support for online storage, e.g. Google docs, Nextcloud, web services with group features (e.g. show data of different users in one spreadsheet)

**Comment by Krish-bhardwaj** [comment]
I am interested to fix this issue. I request you to allow me to fix it. can you assign me this issue
