### ISSUE TITLE
Instruments for PSLab Desktop, Map Views, Sample Data, User Support, System Integration

### ISSUE THREAD

**Issue by techyay** [fossasia/labs.fossasia.org#379]
In this project the goal is to move forward with the next version of Pocket Science Lab Desktop and achieve a more complete feature set and compatibility with the Android app. Important features of this version should include:
* add instruments
* implement and improve mapping features and views
* add sample data sets and previews
* improve user support and documentation features
* add search features
* implement multi-user mode

**Comment by Krish-bhardwaj** [comment]
I am interested to fix this issue. I request you to allow me to fix it. can you assign me this issue
