### ISSUE TITLE
Autodeploy Yaydoc to Hetzner Cloud with Kubernetes or another solution

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#380]
Autodeploy [Yaydoc](https://github.com/fossasia/yaydoc) to [Hetzner Cloud](https://www.hetzner.com/cloud) with Kubernetes or another solution. 

Yaydoc used to be deployed using Google Cloud with Kubernetes, which has a very high price now. Alternatively there are providers like Hetzner.

Please make Yaydoc work with Hetzner Cloud. Document your setup and share it with the team. Add the setup to the Yaydoc repository at https://github.com/fossasia/yaydoc

The following links could be helpful.
* https://github.com/hetznercloud/cli
* https://github.com/hetznercloud/csi-driver
* https://github.com/hetznercloud/awesome-hcloud

**Comment by MukulMaheshwari** [comment]
I would like to work on this issue. Can u please elaborate "or another solution". Is Hetzner is the appropriate solution ? Please brief me. Thanks
