### ISSUE TITLE
Website: Update Social Media Message on All FOSSASIA site repos in social media section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#388]
The social media section of FOSSASIA has an outdated message, if a user clicks on the social media icons. Substitute this message with something generic about FOSSASIA, e.g. as follows:

"FOSSASIA develops #OpenSource software and #OpenHardware with a global developer #community from its base in #Asia. Join us at https://fossasia.org"

![Screenshot from 2019-12-13 12-47-01](https://user-images.githubusercontent.com/1583873/70798381-18245680-1da7-11ea-943f-e4a4a0371a3b.png)

**Comment by huonggiangbui** [comment]
Hi, I wanna solve this issue and I am working on it

**Comment by Dishebh** [comment]
@mariobehling you want to change the message that appears on the social media site (like tumblr) after clicking on them?
Like the one appearing at the top in the pic below...?
![Screenshot from 2019-12-20 12-49-10](https://user-images.githubusercontent.com/43489708/71237318-3d750f80-2327-11ea-931f-3cba63691f50.png)
