### ISSUE TITLE
Website: Change "Github" embedded script in index.html to separate file

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#389]
The script to collect issues from GitHub is embedded into the html. Please move the script into the "js" folder and update the links. Ensure the script still works.

![Screenshot from 2019-12-13 13-14-39](https://user-images.githubusercontent.com/1583873/70799730-bbc33600-1daa-11ea-8991-6f2b2b37609d.png)

**Comment by darshancool25** [comment]
Hi, I would like to work on this issue.
