### ISSUE TITLE
Website: Make width of "ideas" section same as other areas

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#391]
The width of the "ideas" section is not the same as other areas. Please adjust this to be the same.

![Screenshot from 2019-12-13 13-33-25](https://user-images.githubusercontent.com/1583873/70800733-4442d600-1dad-11ea-8e78-796a7eaf10a0.png)

**Comment by darshancool25** [comment]
Hi, I would like to work on this issue.

**Comment by codedsun** [comment]
@darshancool25 Please go ahead.

**Comment by darshancool25** [comment]
I forked the repo..... But I am not able to find the section of code associated with the ideas section.....How can I make sure i have right copy of the code? I am new to making contributions, please help me out here.

**Comment by Dishebh** [comment]
@darshancool25 try finding it out in the index.html file
