### ISSUE TITLE
Website: Change the gray color of the ideas section to match the "Connect to FOSSASIA" section

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#392]
The gray background of the ideas section is slightly darker than other areas, e.g. "Connect to FOSSASIA".

Please adjust the background color to the same slightly lighter gray.

![Screenshot from 2019-12-13 13-37-19](https://user-images.githubusercontent.com/1583873/70800957-dcd95600-1dad-11ea-8171-2f9796bb4cb9.png)
![Screenshot from 2019-12-13 12-47-01](https://user-images.githubusercontent.com/1583873/70800958-dcd95600-1dad-11ea-90ff-fa459fa0e4f3.png)

**Comment by darshancool25** [comment]
Hi, I would like to work on this issue.
