### ISSUE TITLE
Website: Fix map enlarge/smaller feature on FOSSASIA Summit pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#394]
1. The plus/minus sign on all maps of FOSSASIA Summits does not work. Please fix it.
2. Please enable the user to view the map in a separate page.

![Screenshot from 2019-12-13 16-09-34](https://user-images.githubusercontent.com/1583873/70809876-fcc74480-1dc2-11ea-8c67-491037bba8de.png)

**Comment by anishagg17** [comment]
are we allowed to replace this map component with another one?

**Comment by mariobehling** [comment]
Best would be to fix the existing map.

**Comment by HellWolhardZeli** [comment]
I'll work on this

**Comment by HellWolhardZeli** [comment]
This issue should be part of the following repo right?
 https://github.com/fossasia/summit.fossasia.org

**Comment by anishagg17** [comment]
@mariobehling  I have already fixed it 
please look onto: https://github.com/fossasia/summit.fossasia.org/pull/28
