### ISSUE TITLE
Website: On Mobile Screens get rid of horizontal scrolling

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#397]
On mobile screens there is a horizontal scroll of the site. FOSSASIA.org does not have that horizontal scrolling. Please check what are the differences and follow the main page fossasia.org to avoid horizontal scrolling.

![Screenshot_20191214_102901_com android chrome](https://user-images.githubusercontent.com/1583873/70846755-b0304780-1e5c-11ea-9938-112da3c8ecdb.jpg)

**Comment by Chaitanyassr** [comment]
I would like to work on this issue.

**Comment by Dishebh** [comment]
@mariobehling I think this issue is taken care of now.

**Comment by chinmaikaveti2001** [comment]
Hi! Can u please assign this issue to me..?

**Comment by hritik2002** [comment]
Is this issue resolved ?
Can I work on this issue ?
maintainers ... please reply !
