### ISSUE TITLE
Markdown doesn't work on project page

### ISSUE THREAD

**Issue by andibraeu** [fossasia/labs.fossasia.org#40]
I created a new project page, on github it's formatted in the right way: https://github.com/fossasia/labs.fossasia.org/blob/gh-pages/_posts/2015-03-08-toolbox-fossasia-api.md

but the result doesn't work: http://labs.fossasia.org/posts/toolbox-fossasia-api.html

can someone please fix it?

**Comment by samarjeet27** [comment]
@andibraeu the link is working

**Comment by RoonyH** [comment]
@samarjeet27 the link is working but formatting is wrong. for example see bulletpoints. Would be great if you can take a look.

**Comment by samarjeet27** [comment]
Fixed in https://github.com/fossasia/labs.fossasia.org/pull/41
