### ISSUE TITLE
Website: Update new FOSSASIA Address

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#407]
The new FOSSASIA Address in Singapore is:

12 Eu Tong Sen Street #08-169 Singapore 059819

Please update it and add a link to OpenStreetMap as on https://fossasia.org

**Comment by makoteq** [comment]
Can i work on this issue?

**Comment by kumuditha-udayanga** [comment]
@mariobehling the changes have been done please review #408  😇

**Comment by SuryanshShahi** [comment]
Hi , I would like to work on this issue

**Comment by SuryanshShahi** [comment]
@mariobehling the changes have been made, please review #448
