### ISSUE TITLE
Project description section is too long

### ISSUE THREAD

**Issue by Sid911** [fossasia/labs.fossasia.org#416]
## Issue
When I first Launched the website seeing that long bar at the right side made me feel tried without even scrolling 😂.

![image](https://user-images.githubusercontent.com/27860105/72011502-06d44a00-3280-11ea-937c-78eabb9d0aca.png)

A site shouldn't be really long from the get go, and from tracking down the longest section is the project section which is dynamically being generated from the github api using Jquery.

## Solution
I think we should have a **accordion** type feature where only the project names are visible at first and when user clicks on the project he should be able to see the issues he/she can work on. As already in this section a brief about projects is being given (bellow screenshot) , there should be no problem if the extra description is hidden at first.

![image](https://user-images.githubusercontent.com/27860105/72011808-9bd74300-3280-11ea-8da3-f963bb6423d5.png)

## Are you working on this?
Yes I am Working on this 😇

**Comment by Sid911** [comment]
@mariobehling I any suggestions if I should work on this or not would be nice 😇.

**Comment by mariobehling** [comment]
Low priority at the moment as we have tons of other stuff to attend to. Therefore closing it. Thanks.

**Comment by Sid911** [comment]
@mariobehling I have already worked on it and it's almost done.. I was making more changes to some bugs.. it there an issue if this gets merged? 😅
