### ISSUE TITLE
Add yaydoc.org into dropdown menu on all FOSSASIA.org Github pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#417]
Yaydoc is running on yaydoc.org. Please add the link to the FOSSASIA dropdown menu into the "projects" tab above "Meilix".

![Screenshot from 2020-01-09 16-51-59](https://user-images.githubusercontent.com/1583873/72063755-68d49400-3300-11ea-8709-b9e73aa7321a.png)

**Comment by NishithP2004** [comment]
Working on it

**Comment by NishithP2004** [comment]
PR: https://github.com/fossasia/fossasia.org/pull/640

**Comment by SARTHAK1SINGH** [comment]
@mariobehling can i work on this issue.

**Comment by NishithP2004** [comment]
I have already done that

**Comment by Dishebh** [comment]
@mariobehling pls close the issue, if it has been resolved.
