### ISSUE TITLE
Website : Add a toggle for night/dark mode of the website.

### ISSUE THREAD

**Issue by wimpywarlord** [fossasia/labs.fossasia.org#422]
I wish to make a toggle that enables a dark/night mode for the website changing the color scheme from orange and white to  dark grey and warm white.

This should give you a fair idea:
<img src="https://media.giphy.com/media/CxKDjNN5YiHkI/giphy.gif">

**Comment by mariobehling** [comment]
Out of scope and out design is red. So, does not seem suitable. Therefore closing it.
