### ISSUE TITLE
text Over flow and  is not responsive overlapping to right screen in MObile View

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/labs.fossasia.org#431]
![fossaisa lab](https://user-images.githubusercontent.com/65535360/86592942-f6442880-bfb1-11ea-8301-4c7980f23a47.PNG)

link is not responsive overlapping to right for the better understanding plz see in the screenshot

**Comment by psyduck1203** [comment]
is this issue solved ?

if no i would like to work on this !

**Comment by Raunaksingh100** [comment]
@psyduck1203 you can work on this issue ...........

**Comment by psyduck1203** [comment]
I just saw that this issue is solved.

**Comment by Raunaksingh100** [comment]
@psyduck1203 not solved in galaxy fold screen

**Comment by psyduck1203** [comment]
okay, ill see to it.
