### ISSUE TITLE
links not responsive in mobile view (BUG)

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/labs.fossasia.org#436]
### Descriptions
link is not responsive in the mobile view see in the screennshot given below for the better understanding..............

![lab 1](https://user-images.githubusercontent.com/65535360/89313292-f0fff980-d695-11ea-98ab-79f7fe4ef9c1.PNG)

**Comment by NermatiShravanReddy** [comment]
I'd like to resolve it.

**Comment by Raunaksingh100** [comment]
@NermatiShravanReddy  you can work on this issue.............
