### ISSUE TITLE
need padding in link in the mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fossasia/labs.fossasia.org#437]
![need padding](https://user-images.githubusercontent.com/65535360/89384595-edaf5100-d71b-11ea-9060-2fddca05c931.PNG)

**Comment by NermatiShravanReddy** [comment]
Can you assign this issue to me, I'd love to work on it.

**Comment by Raunaksingh100** [comment]
@NermatiShravanReddy  find some other issues i already working on this..................
