### ISSUE TITLE
Categorize GSoC Ideas according to topics/projects and show them "bundled"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#44]
1) Categories:
* loklak
* FashionTec
* Free Networks
* Small Talk
etc.

2) Show "Table of Contents" that "anchors/links" to the area of the page

**Comment by mariobehling** [comment]
So, we need something like that
* On top table of contents
* in the main area heading generated from category in projects
<h2>loklak search</h2>
Project xyz
Project uyl
Project jho
<h2>Free Networks</h2>
Project lop
Project jjkj
<h2>Steam</h2>
Project agc
Project hhh

**Comment by samarjeet27** [comment]
@mariobehling should this be on the main page or both the open and closed pages ? We could add a ```category``` in the yaml frontmatter of the post to achieve this.

**Comment by samarjeet27** [comment]
Done in https://github.com/fossasia/labs.fossasia.org/pull/49

**Comment by mariobehling** [comment]
Ok, very good.

Now, instead of writing a "table of contents", we need a table of contents on top. The actual thing.

Please change categories to "h2" and projects heading to "h3".

**Comment by mariobehling** [comment]
See for example a wiki. On the top is a table of contents linking to all projects on the page. http://wiki.freifunk.net/Ideas

**Comment by samarjeet27** [comment]
@mariobehling added a table like the freifunk's ideas and updated the heading tags in https://github.com/fossasia/labs.fossasia.org/pull/50

**Comment by samarjeet27** [comment]
Done in https://github.com/fossasia/labs.fossasia.org/pull/54

**Comment by mariobehling** [comment]
Generate categories from "Category" in posts automatically instead of hard-coding categories.

**Comment by mariobehling** [comment]
Currently Categories do not show up.

**Comment by samarjeet27** [comment]
It shows up locally after https://github.com/fossasia/labs.fossasia.org/pull/63

But there are no changes in the labs.fossasia.org site

![screen shot 2015-03-18 at 2 40 34 pm](https://cloud.githubusercontent.com/assets/2987087/6705635/d41d21d0-cd7c-11e4-8c87-13acbe18d11b.png)

**Comment by RoonyH** [comment]
I made cloudflare rocket loader ignore custom.js script in 90dd23f6a03976a9 and it seems categories are showing now. So It was because for some reason cloudflare was serving an old version of the file. @mariobehling could you invalidate cloudflare cache for this file? so we can have it loaded from cloudflare again.

**Comment by samarjeet27** [comment]
@RoonyH I tried that too in https://github.com/samarjeet27/labs.fossasia.org/commit/c1df95372b54f80fe091d3ec52cd68ef7e6a34b8 but the script doesn't work then because it can't find jQuery.
see this - 
![screen shot 2015-03-19 at 7 03 15 pm](https://cloud.githubusercontent.com/assets/2987087/6731405/c71e0dde-ce6a-11e4-9dd0-34e3b5ea962a.png)
maybe it's because all the other libraries are loaded asynchrously

**Comment by RoonyH** [comment]
@samarjeet27 I don't think that attribute makes sense in samarjeet27.github.io domain. Its not served through cloudflare.

Btw categories that does not have any projects under them show up in "Smaller projects that you can work on " section. You know a way to fix it?

**Comment by samarjeet27** [comment]
@RoonyH that's the console output of labs.fossasia.org and not my repo's site. The custom.js contains some code which removes the categories which do not have a project in it. All the undesired categories show up because the script is not able to run

**Comment by RoonyH** [comment]
@samarjeet27 ah. understood. the link to your repo confused me. Yeah that's probably it. We need cf cache updated. Anyway why use js? Can't this be done on the server in the build time?

**Comment by samarjeet27** [comment]
@RoonyH @mariobehling guess the cf cache has been updated, seems to work now.

**Comment by ty221** [comment]
CF maximum cache is 5 days. Sometimes it is shorter. CF has own algorihtms
to determine proper caching for files. If something remains unchanged, I am
sorry. We can purge cache manully, but doing that after each commit will be
bit tiring and likely impossible. I gonna read Cloudflare API
documentation, we can write a script to automatize cache purging.

sob., 21 mar 2015 o 18:47 użytkownik Samarjeet <notifications@github.com>
napisał:
