### ISSUE TITLE
Change "Home" to link to labs.fossasia.org and add tab "Blog" to "tab menu"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#45]
![screenshot from 2015-03-16 14 10 28](https://cloud.githubusercontent.com/assets/1583873/6661378/5b3b1caa-cbe6-11e4-9ab8-5d56fe13d988.png)

**Comment by samarjeet27** [comment]
Done https://github.com/fossasia/labs.fossasia.org/pull/46
