### ISSUE TITLE
Improve table of contents layout

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#56]
Change the table layout to appear without bullets. Set up to table of contents to work with section headings of project headings that are indemned.

Community Tools
    Develop the FOSSASIA Event App
    Timeline and Search Navigation for loklak.net
    Extend toolbox for FOSSASIA (and Freifunk) API
FashionTec
    Develop a library to support knitting machines
    Develop a gui to support knitting machines
....

**Comment by samarjeet27** [comment]
Done in https://github.com/fossasia/labs.fossasia.org/issues/70
