### ISSUE TITLE
Add grey table as in overview page to project pages

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#59]

**Comment by sudheesh001** [comment]
@mariobehling Can you describe more about this issue ? The grey table that's used int he overview page lists the project mentor, potential links etc.., Not all projects have these details which could be made into a table on the project page ? What is the expected solution there ?

**Comment by mariobehling** [comment]
I do not understand your question. Here is the screenshot of a table
![screenshot from 2015-03-23 16 18 05](https://cloud.githubusercontent.com/assets/1583873/6783109/56b2c4ca-d178-11e4-9cc9-19d3988bfd60.png)

That table should also be on the project page here for example: http://labs.fossasia.org/projects/fossasia-event-app/

**Comment by ty221** [comment]
Fixed in https://github.com/fossasia/labs.fossasia.org/commit/7ab4f7a510b1389a6330420053dc94a363cf92df 

Table has been added.

**Comment by mariobehling** [comment]
Thanks a lot. Please remove the horizontal line before the table.
