### ISSUE TITLE
Add all content to overview "ideas page" - no need to click many times. Just add all the text to the overview page as well

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#60]

**Comment by ty221** [comment]
Did you mean something like that? :D

**Comment by mariobehling** [comment]
Thanks for the improvement. 
a) Please remove the large space between the text and the table.
b) Please increase the space between the table and the next project heading.

![screenshot from 2015-03-23 23 40 09](https://cloud.githubusercontent.com/assets/1583873/6792204/28fb8c40-d1b6-11e4-958b-220306d3214d.png)
