### ISSUE TITLE
Increase table of contents to use all available width + do not indent first headings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#71]
e.g. do not indent "community tools"

**Comment by mariobehling** [comment]
Please try to avoid list tags <ul> and <li> instead just use line breaks. Reason: If we change the style for lists, we might change other parts of the site and divert from the style of other FOSSASIA sites.

**Comment by samarjeet27** [comment]
@mariobehling you mean to avoid list tags in the table of contents ?

**Comment by mariobehling** [comment]
I mean do not make it into a list. I think it is better to use just line breaks. No "<ul>" tags.

**Comment by samarjeet27** [comment]
Done in https://github.com/fossasia/labs.fossasia.org/pull/76
