### ISSUE TITLE
Implement automatic conversion of links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#75]
E.g. check out here: http://labs.fossasia.org/projects/knitting-machine-library/
Links are not automatically made into clickable links.

**Comment by samarjeet27** [comment]
@mariobehling, they need to be formatted as links in markdown. Jekyll doesn't contain any methods to convert them automatically.
Fixed links in https://github.com/fossasia/labs.fossasia.org/pull/76

**Comment by mariobehling** [comment]
Thanks! Such a pity, cause in the preview they are converted automatically.

**Comment by samarjeet27** [comment]
@mariobehling, in which preview ?

**Comment by mariobehling** [comment]
github preview here for example: https://github.com/fossasia/labs.fossasia.org/blob/gh-pages/_posts/2015-03-04-ayab-port.md
