### ISSUE TITLE
fields for subscribe are dissimilar on different pages

### ISSUE THREAD

**Issue by SaptakS** [fossasia/labs.fossasia.org#84]
In the home page (http://labs.fossasia.org/), the subscribe form has two input fields- name and email. But in all other pages, the subscribe form has only one input field - email

**Comment by samarjeet27** [comment]
Are you sure ? There are only 2 pages in the site other than the homepage i.e the ideas and archive and both show the Name and Email field in the subscribe form on my system. See the screenshot below -


**Home Page**


<img width="965" alt="screen shot 2015-09-24 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/2987087/10070739/2253be8c-62d2-11e5-8eeb-f07ee0ec4e04.png">


**Ideas Page**


<img width="1004" alt="screen shot 2015-09-24 at 3 36 56 pm" src="https://cloud.githubusercontent.com/assets/2987087/10070752/3a1117ea-62d2-11e5-8c7e-3b438445bd0c.png">

**Comment by SaptakS** [comment]
what about the other parts such as the events and code of conducts?? Those doesn't come under this website?? http://blog.fossasia.org/events

**Comment by samarjeet27** [comment]
Oh Okay. But that's a separate codebase and not part of this repo.

**Comment by SaptakS** [comment]
Ok. I saw that.
