### ISSUE TITLE
Modal for FOSSASIA update form

### ISSUE THREAD

**Issue by harjot4995** [fossasia/labs.fossasia.org#85]
The form for FOSSASIA updates redirects to a page at http://fossasia.createsend.com/t/t/s/ for Response  message.

![fossasia](https://cloud.githubusercontent.com/assets/8307322/11321810/06f1112c-90f3-11e5-93fe-74d0766e0bc3.png)

Having a Modal window would improve UI and Styling.

**Comment by tradzik** [comment]
@harjot4995  Thanks for your report! Do you suggest we should add somekind of prompt instead of redirection? I like current version, but we can change it if it is better.

**Comment by harjot4995** [comment]
@tradzik There's no problem the way it works but I thought it might be better if a prompt would display the message rather than redirecting to another page.

**Comment by tradzik** [comment]
@harjot4995 Thanks for clarificaiton. @mariobehling Does this mailing service provide us a tool to display a prompt or we should write that at our own?

**Comment by harjot4995** [comment]
@tradzik Let me know if I can also contribute, I'm looking for an opportunity.

**Comment by tradzik** [comment]
@harjot4995 Sure, your contribution will be very appericated! If you want to work on this issue, you can try to design a modal window and submit pull request to this repository, or if you prefer working on something different, you can pick up something to work on from our list of issues - https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Afossasia+

**Comment by opg7371** [comment]
what kind of a prompt..i would also like to contribute to your code...pl walk me through the coding styles in this one.@tradzik

**Comment by alan-aipe** [comment]
@tradzik Is this issue still open?
