### ISSUE TITLE
Fix content of ideas.md

### ISSUE THREAD

**Issue by vipul-sharma20** [fossasia/labs.fossasia.org#86]
the [ideas.md](https://github.com/fossasia/labs.fossasia.org/blob/gh-pages/ideas.md) file does not look right. I think the ideas section contains code of some templating language which should be fixed and the correct content should be added using markdown syntax.

**Comment by aryasaatvik** [comment]
@vipul-sharma20 the site is built with jekyll which uses liquid template engine requires the syntax in ideas.md
ideas.md is basically a webpage on http://labs.fossasia.org/about
it is not supposed to be a readme.md sort of page, therefore this issue is not valid

**Comment by vipul-sharma20** [comment]
@aryasaatvik Thanks for the info. This clears everything. Closing the issue
