### ISSUE TITLE
OpenCoin Digital Cash App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#87]
OpenCoin is a true digital cash system, similar to the former DigiCash/eCash based on tokens and providing real anonymity. A prototype wallet app is already available and has been written in JavaScript. Project scope is to implement a mature wallet with additional features (e.g. p2p transactions, encrypted wallet, QR codes), better look and feel and platform independent (e.g. C, JavaScript+PhoneGap) Make yourself familiar with the OpenCoin protocol Agree the feature set Develop and test the wallet

Categories: Peer to Peer Technologies and Cryptography, OpenCoin Digital Cash App

Project: http://opencoin.org , https://github.com/OpenCoin

Getting Started:
- Make yourself familiar with the OpenCoin protocol
- Agree the feature set
- Develop and test the wallet

Mentors: Jan Suhr, Joerg Baach
Skill Level: Medium
Skills: Scala programming language, Twitter's Finagle server, SBT build tool, Optional - Eclipse IDE is recommended, Optional- Coins are stored in a SQL database via squeryl library

**Comment by naveenjafer** [comment]
@mariobehling  Hi, I have a few questions, it would be great if you could help me out. 
1) The prototype wallet that you have mentioned about, could I have a link to it's repo? Or is this what you mentioned? https://github.com/OpenCoin/opencoin-js I am well versed with JS and a strong hold of cryptography along with a sound SQL background. 
2) Are you looking for an app for mobile or desktop environment? If it is a desktop environment that you are looking for then the Electron framework would be a really good candidate for the same.

**Comment by singbird81** [comment]
@mariobehling I am familiar with Android and iOS native developement.
May I ask this project is for app front-end side or server side? I would be glad if I can contributed to it. :)

**Comment by rishsethia** [comment]
@mariobehling I am android developer and really wanted to do this project as part of GSOC , if we can develop it platform specifically for android!

**Comment by sumitbhanu** [comment]
how can i contact mentors ?

**Comment by Zakwani** [comment]
@mariobehling I am new and want to start conributing this opensource project.Can you give me your best responce?

**Comment by mayanksingh0597** [comment]
@mariobehling How should i contact you.being new to opensource I need to know how can I Contribute to this project.

**Comment by yasirunilan** [comment]
@mariobehling How can I contact the mentors??

**Comment by milankarunarathne** [comment]
Hi @mariobehling, it's really nice to meet you here. I'm glad that you have consider about my previous suggestion during GSoC 2016 OpenCoin project. I'm looking into contributing to this project. Tried to contact Jan and Joerg, but unable to get a reply from them. Waiting for any notification about the project.
