### ISSUE TITLE
Improve the tooling for the sTeam collaboration platform

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#88]
Open sTeam is a collaboration platform developed at the University of Paderborn in germany. It is no longer developed at the university, but still in use.

One of the shortcoming of sTeam are development tools. sTeam supports a remote commandline and editing interface, and prototypes for exporting the sTeam database to git.

In this project you will create new and improve existing commandline tools such as: database import and export to and from git TLS support for the remote commandline client a vim plugin for remote editing of database contents packaging to simplify the deployment of sTeam and more…

The goal of the project is to make sTeam development better for commanline users. sTeam is written in Pike, a programming language similar to Java and python. Pike is not hard to learn so you will have no trouble writing Pike code within a few days. sTeam runs only on Linux and to work on this project you need to be familiar with GNU/Linux and the Linux commandline. you should also be familiar with git and vim or emacs

Mentors: Martin Bähr, Aruna Herath, Chris Angelico
Skill Level: medium
Skills: familiarity with a language like python, ruby, java...

**Comment by rohangoel96** [comment]
@mariobehling , I'm familiar with both JAVA and Python and am comfortable using linux. I would be glad if I am allowed to work on this.

**Comment by mariobehling** [comment]
At the moment we are still collecting the ideas. In order to have a nice ideas site, this issue is the top priority: https://github.com/fossasia/labs.fossasia.org/issues/89

**Comment by anirudhk68** [comment]
@mariobehling , I'm familiar with JAVA ,Python and web development. i am comfortable using linux. I would be glad if I am allowed to work on this.

**Comment by eMBee** [comment]
a requirement to participate in GSOC is the ability to form independent thought and communicate on your own without copying others.

**Comment by ashutoshsaboo** [comment]
@mariobehling Hi! I am new to open source, but recently I have been working and actively involved with several open source organizations, trying to solve bugs. I usually prefer Python/Java/C/JavaScript as my mode of programming, as I am a bit acquainted with these. I would like to work and contribute towards this project? How do you suggest I must start? Or would you suggest me some other bugs to work on, before starting this?

Some guidance from your side would be appreciated, since I am new to open source. @mariobehling 

Thanks! :)

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by casyazmon** [comment]
@mariobehling  Hi! am a second year under graduate computer engineering student and i have been using the  linux OS for some years now. I have Java, Python and  C programming skills. I am very much interested in open source projects and will like to contribute towards the development of this project. Please i will like to know more about the project and how to start contributing.
Thanks.

**Comment by ajinkya007** [comment]
@mariobehling @eMBee Hello, I would like to work on this STeam project. I have been experimenting with different flavours of linux because of which I have familarity with cli, vim and git. I have programming skills in C++,Java and Python. Since pike is a dynamic language with oop paradigm, I would like to explore it more. Looking forward to contribute to this project.
Cheers! :)

**Comment by kvk30** [comment]
@mariobehling  Can you please provide me source code link ? Want to work on this project for GSOC 2016 . I have good knowledge in python , ruby , java .

**Comment by rajatthakur** [comment]
Hello, I am interested in this project. I have good knowledge of languages like Python and C++. Also I saw the syntax of Pike language which is very easy to take up. I would like to work on this project for this gsoc.

**Comment by Sandeep-AnilKumar** [comment]
Hello, I am a graduate student from University of Illinois at Chicago. I am majoring in computer science and my interest lies in programming languages, and I have worked extensively on Java and JavaScript. I would like to work on this project and would like to learn Pike as well. I will be applying formally soon, and contributing to the project independently too. Thanks,

Cheers!

**Comment by ajinkya007** [comment]
If you are interested in the project please submit a proposal for the same following the guidelines mentioned in the wiki page https://github.com/societyserver/sTeam/wiki/GSOC-proposals . You need to show your interest in the project, tell mentors about your background and show them how you will achieve the goals you have set for the project.

**Comment by rajatthakur** [comment]
https://docs.google.com/document/d/1wPDsjfUS8vbpzydi9GqfI9J-zbIS7JL1ZleGRk_42Qg/edit?usp=sharing

On Fri, Mar 25, 2016 at 1:41 PM, Ajinkya Wavare <notifications@github.com>
wrote:

> If you are interested in the project please submit a proposal for the same
> following the guidelines mentioned in the wiki page
> https://github.com/societyserver/sTeam/wiki/GSOC-proposals . You need to
> show your interest in the project, tell mentors about your background and
> show them how you will achieve the goals you have set for the project.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/fossasia/labs.fossasia.org/issues/88#issuecomment-201194457>
>



-- 
Regards,
Rajat Kumar <http://www.facebook.com/rajatdumka>
CSE, BKBIET, Pilani
<https://in.linkedin.com/in/rajatthakur>

**Comment by jig08** [comment]
@rajatthakur I hope you have submitted your final/draft proposal at [summerofcode.withgoogle.com](https://summerofcode.withgoogle.com/) for review.

**Comment by mariobehling** [comment]
Thank you for participating in this year's GSoC!
