### ISSUE TITLE
Create or improve the GSoC-Idea page with a sorted list of issues using the GitHub API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#89]
**Objective**

Create or improve the GSoC-Idea page with a sorted list of issues tagged with the label "GSoC" in the [issue tracker of labs.fossasia.org](https://github.com/fossasia/labs.fossasia.org/). Please use the [github API](https://developer.github.com/v3/issues/) to get the data

**Requirements**

- use Github API https://developer.github.com/v3/issues/
- website is http://labs.fossasia.org

**Expected Outcome**

- sorted list of [issues in this repository](https://github.com/fossasia/labs.fossasia.org/issues) labeled "GSoC"
- if possible create a tabel of contents 
- in the detailed issue list include description
- include on bottom "read more" which links to the issue itself in the tracker
- only show "open issues"
- the page should be named "GSoC16", please make a pull request to https://github.com/fossasia/labs.fossasia.org

**Links**

- issue tracker https://github.com/fossasia/labs.fossasia.org/issues
- issues labeled "GSoC" https://github.com/fossasia/labs.fossasia.org/labels/GSoC

**Comment by SaptakS** [comment]
I would really like to work on this..

**Comment by SaptakS** [comment]
Should I modify the ideas.md or ideas.html?

**Comment by mariobehling** [comment]
@SaptakS just create a temporary gsoc.html Thank you

**Comment by mariobehling** [comment]
So, I have added the new site at https://github.com/fossasia/labs.fossasia.org/tree/gh-pages/new

There are two files gsoc.html and archive.html. The first goal is to replicate the tables of content and content as shown in the original page (but using the data from github instead).

![screenshot from 2016-01-22 22 01 05](https://cloud.githubusercontent.com/assets/1583873/12522902/b8f1f50e-c153-11e5-9330-7ad3e290b727.png)

**Comment by rohangoel96** [comment]
I am working on this

**Comment by rohangoel96** [comment]
@mariobehling , I'd like to work on this but which file do I edit? gsoc.html or archive.html? Also, the new page that I create as to look like the image that you have posted above, right?

**Comment by mariobehling** [comment]
@SaptakS Already got this started. Please check out gsoc.html and archive.html to implement the functionality.

**Comment by mariobehling** [comment]
Here is a link to gsoc.html labs.fossasia.org/new/gsoc.html
As you can see, there are lots of things to do. At first get the URLs working, make a "read more link" etc. Later on the site should be plugged into the design of labs.fossasia.org/new/

**Comment by rohangoel96** [comment]
I'll try my best

**Comment by mariobehling** [comment]
@SaptakS @rohangoel96 I have added a page in new design as ideas.html 

Please help to insert the ideas here "<ADD GSOC PROJECTS LIST>" on line 139. Cheers. If possible keep the rest of the page unchanged, so I can edit these paragraphs independently. Cheers.

**Comment by Abhi2424shek** [comment]
@mariobehling I see can I too help out! It's my task at GCI so I would give out a PR in a short while. OK!

**Comment by rohangoel96** [comment]
Anything else that I can work upon @mariobehling

**Comment by Abhi2424shek** [comment]
It would be nice to do the other tasks or improve the design of the table, or something else. But please do start only on issue stated by the mentor! :) - Happy coding @rohangoel96. cheers.

**Comment by mariobehling** [comment]
Good job! Let's make a small improvements. 

- [ ] Please expand the width of gray area in line with the site design. Please see below.

![screenshot from 2016-01-26 01 00 27](https://cloud.githubusercontent.com/assets/1583873/12568778/df21ecb2-c3c8-11e5-8d91-4b1f6d7b2fb4.png)

- [ ] Also check that the area uses the maximum width on mobile devices with small screens.

**Comment by rohangoel96** [comment]
I am working on it, @mariobehling
