### ISSUE TITLE
Timeline and Search Navigation for loklak.net

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#93]
**About loklak**

loklak is free software hosted on loklak.org which provides message search results from twitter in json format. 

**Task**

loklak is a complete search engine back-end solution with a JSON api. What is missing to provide a search web page is a web page design showing the json search results as timeline in the style of a twitter search result. 

Basically it should look like https://twitter.com/search?src=typd&q=fossasia in the right column while the left column has to provided new/other search navigation tools. The data to be presented will all be within the json API of loklak. The timeline web page must also provide - switching off the left navigation columns and switching on self-refreshing which turns the timeline into a twitterwall - some kind of animation when selecting navigation options in the left column (i.e. fade-in and fade-out of select options)

**Skill Set**

The applicant should have the following skills - advanced JavaScript skills - proven ability (show an example of your work) to write AJAX web applications - confident with bootstrap css Nice to have - backbone.js (usage of backbone.js is not a must be you may consider it) - overall web design skills

**Potential Mentors** 
- Michael Christen
- Mario Behling

**Links**
- [Website](http://loklak.net)
- [Github Repo](http://github.com/loklak)
- [Mailing List](https://groups.google.com/forum/#!forum/loklak)

**Comment by manishbisht** [comment]
@mariobehling  I'm intrested in this project. I am familier with HTML, CSS, Javascript and PHP. I have developed the whole website of http://www.run4offers.com. I have the advanced level in bootstrap. I will love to complete this project. :)

**Comment by aayusharora** [comment]
Hi,@mariobehling ,I am contributing to Fossasia from past one month with gci15 website and Open event webapp,I know HTML5,CSS3,Bootstrap,Materialise CSS and Angular JS .I will like to contribute into this. :)

**Comment by nishnik** [comment]
@mariobehling I have developed these two websites:

- [Code-O-Soccer](http://event.krssg.in/)

- [KRSSG](http://krssg.in)

and I am quite familiar with HTML5, CSS3, bootstrap, PHP and Javascript. Apart from it I assure you about my abilities to google. Furthermore, I have good hold on scraping websites (Example: [hello-flipkart](http://nishantnikhil.weebly.com/blog/hello-flipkart)) and have used many a REST APIs. I will like to contribute into this.

**Comment by rajansavaliya** [comment]
I want to work on this project. Where is issue related to this project? For working on this project for gsoc, I should do any projects (related to required skill ) which are available on github right now?

**Comment by amritsinghbains** [comment]
I made a twiiter social wall. It hosted on github. I would like to include other APIs from Facebook, Instagram, Snapchat etc

http://fillersocial.github.io/socialwall.html

**Comment by VishalRocks** [comment]
@mariobehling Hi. I have worked in PHP, HTML, Javascript, React, Meteor, jQuery, Rails etc and am very passionate about web development. I am interested to contribute for this project.

**Comment by gvaibhavraj2** [comment]
@mariobehling I have made the layouts for social wall and search timeline.For now I have made the design and will be using masonry library and other technologies like angular js,css to implement it.
![12755404_1009734942425878_363404778_o](https://cloud.githubusercontent.com/assets/7159037/13060492/e3ad14c4-d457-11e5-91bb-8aa4b36d64dd.jpg)
![12499303_1009734945759211_1396242684_o](https://cloud.githubusercontent.com/assets/7159037/13060498/ee502362-d457-11e5-8335-e84da9096cf4.jpg)

**Comment by milindra** [comment]
Want to contribute what modification should i do

**Comment by leonmak** [comment]
Hi, I used the loklak server to make a prototype of the [twitter wall with Meteor](http://meteortweetwall.meteor.com/)
Here's my repo: [https://github.com/leonmak/meteor-twitterwall](https://github.com/leonmak/meteor-twitterwall)

**Comment by leonmak** [comment]
Not sure if this is the right place to ask this, but are the mentors open to using MeteorJS for any of the loklak fossasia ideas?
I've been playing around with loklak server, and also created a prototype for a twitter wall, [meteortweetwall.meteor.com](http://meteortweetwall.meteor.com) ([github repo](https://github.com/leonmak/meteor-twitterwall))
I think meteor can also be used for the idea on "creating apps to track success of FOSS projects", because of it's realtime and cross-platform features.

**Comment by rishabhs95** [comment]
Hi @mariobehling, I am a student pursuing Bachelors in Information Technology from BIT, Mesra(India). 
I have experience in working with different Web APIs and implementing them on Web Applications using different frameworks(php, laravel, angularjs and nodejs). 
This is the second project which I am interested in and I would like to further discuss about this idea too. Please guide me about the further steps needed to be taken.
