### ISSUE TITLE
Extend toolbox for FOSSASIA (and Freifunk) API

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#94]
Web development, Application Coding, UI Design, Statistics, Visualization

FOSSASIA API is set of tools to gather information about Open Source Communities. All data should be hosted and maintained by the communities itself.

As of now we have a lot of tools we can work with:

```
the Common Map, displaying the location and contact information of communities
a feed aggregator, to aggregate all rss feeds
a calendar collector as wordpress plugin
display lifetime events of all communities
```

Goal of this project is to extend the toolbox, create new tools or enhance existing ones. Possible parts could be:

```
Enhancements
    community map: show latest news and events of communities on a map
    filters: filter map by geolocation to receive news, events and other community related information only within a selected view
    use the Metacommunity field to group communities, e.g. international organizations with local groups
Extensions
    extend FOSSASIA API specs to provide information about services (e.g. web service, mail servers, etc), see api.freifunk.net for inspiration
    create a web service to get parts of API files, based on geo or content filters
    build an overview about API files and validate them
Visualization:
    a framework to easily building charts of API data
    Euler charts to display by countries, metacommunities, cities
    Pie-Chart: how to contact communities (Facebook, Jabber, IRC, usw..)
    list of services and their status
```

Mentors: Andre Rebentisch
Skill Level: Medium
Skills: HTML, CSS, Javascript, PHP, RSS, ICS

**Comment by rag594** [comment]
@mariobehling ,I'm familiar with javascript and python and would love to work on this project

**Comment by manishbisht** [comment]
@mariobehling I am intrested in this project. I am familier with HTML, CSS, Javascript and PHP. I have developed the whole website of http://www.run4offers.com. I am beginner in Python and love to learn the other i.e. RSS and ICS to complete this project. :)

**Comment by naveenjafer** [comment]
@andibraeu Hi, I am interested in knowing more details about what exactly you have in mind for the framework to build charts of API data. I have worked over the summer with visual aggregation of data from facebook and youtube for WATConsult and have good experience on the same

**Comment by aayusharora** [comment]
@mariobehling ,I am interested in this project, I have experience with frameworks of JS like Angular,For data visualisations ,I am interested in knowing more,I will love to work with D3.js.

**Comment by gvaibhavraj2** [comment]
@mariobehling Hi, I have previously worked on using API's data visualization in terms of bar_graphs,groups,stats etc. Also I have prior experience in frameworks like Django,Angular. I am interested in contributing to this tool.

**Comment by VishalRocks** [comment]
@mariobehling Hi. I have worked in PHP, HTML, Javascript, React, Meteor, jQuery, Rails etc and am very passionate about web development. Apart from this, I have worked with R and Octave for machine learning and statistics analysis. I am interested to contribute for this project.

**Comment by SaptakS** [comment]
@andibraeu @mariobehling I would really like to work on this project. I have worked in PHP, HTML, CSS, Javascript, jQuery, AngularJS, Django, FLask and various databases as well. Have experience of working with Github API(made the GSOC ideas page for FOSSASIA using github API) and Loklak API(mentored GCI tasks based on loklak server). I have also worked in the open-event project of FOSSASIA. I have contributed to the Sizzle project of jQuery where I added Sizzle.noConflict. I am really interested to work on new projects and learn new things. Would be really glad if you give me a chance to work on this project. Thanks.

**Comment by kamishettysreeja25** [comment]
@mariobehling I would like to work on this project . I have  experience in Python,HTML,CSS,Javascript.I have done 3-4 projects using these tools . I would love  to work on this project and would be really glad if you give me a  chance to work on this project.
Thank You

**Comment by uttpal** [comment]
@andibraeu @mariobehling I would like to conribute to this project, I am skilled in  javascript, python, Node.js, Flask, Django, Angular js, Mongo DB. Developed many Apps on MEAN stack [Feature Rich ToDo app](http://new-56605.onmodulus.net/ ). I am keen toward learning new technologies, please consider my request.

**Comment by PMArtz92** [comment]
@mariobehling i have good skills in UI design i would like to contribute this project.
