### ISSUE TITLE
Additional Plugins and Features for Knitting Machine Software

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#95]
Tasks:
- Projects have to be compatible to Ayab, Knitic, Passap, OpenKnit, others DIY knitting machines
- New plugins for the various hacks
- Implement features for pattern creation and pattern changes
- Add pro-features like: Set of repeating pattern drawing pixel, converting scans of sample slides to pixel patterns etc.
- We would love it if there is a generic, open format for knitting patterns
- In addition a function to control to the pixel / color data rate and e.g. also the type to use for the carriage as well as the width of the knitting mill (per line)

Links:
- Project: http://ayab-knitting.com/
- Issue Tracker: https://bitbucket.org/chris007de/ayab-apparat/issues?status=new&status=open
- IRC Channel: irc://irc.freenode.net/#ayab
- Twitter: https://www.twitter.com/AYABApparat
-  Reddit: http://www.reddit.com/r/ayab/

Mentors     Mario Behling, Duke
Skill Level     medium
Skills  Web
Links   http://ayab-knitting.com/

**Comment by PaliwalSparsh** [comment]
I am little bit confused as the Skills specified here are web on looking at the source code the code contains python and c++, would be great if you can clear that.

**Comment by ajinkya007** [comment]
Would be obliged to get a chance to work on this. Looking forward for having a great  coding summer.
Thanks!

**Comment by niksj** [comment]
I am very enthusiastic for this project.I have sound knowledge and experience in C,C++, python, JAVA and web development(Html, css, javascript, Jquery, php etc..). I have some hardware knowledge too (familiar with Arduino etc..), some knitting knowledge too.
